### ISSUE TITLE
Some non-XP programs cannot be started at all

### ISSUE THREAD

**Issue by avaxx** [Skulltrail192/One-Core-API-Binaries#1]
I get the message: "... not a valid Win32 application". Thank you very much.

**Comment by Skulltrail192** [comment]
Well, i'm working it. For XP, 2003 and x64. It is normal, i will made a hack or remake function.

**Comment by SSJ9899TDylan** [comment]
I can install this with your One Core API:
Firefox Quantum
You think that if I run Google Chrome in Windows 7 SP1's compatibility mode, it will update to the latest version?

**Comment by SSJ9899TDylan** [comment]
The Kernel Installer is still not working because now it instantly shuts down my virtual machine. Could you please fix this?

**Comment by SSJ9899TDylan** [comment]
I knew that it's still a project that's not finished, but thanks for fixing the kernel installer. Still getting the "not a valid Win32 application error.

**Comment by Skulltrail192** [comment]
It will be fixed today.

**Comment by SSJ9899TDylan** [comment]
Thank you!

**Comment by Skulltrail192** [comment]
You're welcome
