### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by SSJ9899TDylan** [Skulltrail192/One-Core-API-Binaries#10]
The last time that I used your Binaries, I got BSOD UNMOUNTABLE_BOOT_VOLUME at startup.

**Comment by Skulltrail192** [comment]
Are you installed Kernel update?

**Comment by SSJ9899TDylan** [comment]
Yes

**Comment by Skulltrail192** [comment]
So uninstall, i will fix then

**Comment by Skulltrail192** [comment]
I think this already fixed, please, confirm. And it truelly functional now.

**Comment by SSJ9899TDylan** [comment]
I’ll test it on my laptop. P.S You forgot to fix it for Windows Server 2003.

**Comment by SSJ9899TDylan** [comment]
I was installing those Binaries from an ISO file

**Comment by Skulltrail192** [comment]
I'm not tested with server 2003, only XP and it is fixed

**Comment by Skulltrail192** [comment]
Are you tested?

**Comment by SSJ9899TDylan** [comment]
Yes

**Comment by SSJ9899TDylan** [comment]
I don't know for sure because of how long it takes to get the updates

**Comment by SSJ9899TDylan** [comment]
When will you add support for .Net 4.6-4.6.2?

**Comment by Skulltrail192** [comment]
I do not know, it not only depends on me

**Comment by Skulltrail192** [comment]
For test these updates, install clean Windows XP SP3 and apply updates by folder, because it is more updated than release.
