### ISSUE TITLE
XP not start (stornvme load error)

### ISSUE THREAD

**Issue by posreadyxp** [Skulltrail192/One-Core-API-Binaries#102]
So, i tried install Windows XP (kermel mode framework 1.1, SATA (1), NVME (2), PAE 128GB, 256 bit AEX support (3), ntoskrnl_emu) + One core Api. And got error with load stornvme.sys driver (file is corrupted or not available)

**Comment by jonm58** [comment]
OCAPI Driver Installer problem
use NTOSKRNL_Emu storport.sys

**Comment by Skulltrail192** [comment]
stornvme is from ntoskrnl_emu?

**Comment by posreadyxp** [comment]
> stornvme is from ntoskrnl_emu?

If you question for me: No, it's custom driver from MOVAX-2Gen NVME driver (maybe other variants with pther nvme drivers works?)

**Comment by Skulltrail192** [comment]
I will replace storport driver with modded version to ntoskrnl_emu. It probably will solve.

**Comment by posreadyxp** [comment]
> I will replace storport driver with modded version to ntoskrnl_emu. It probably will solve.

OK. Ping me when replace it

**Comment by NEO-SPECTRUMAN** [comment]
> I will replace storport driver with modded version to ntoskrnl_emu. It probably will solve.

you need put warning to readme
so that users do not install another drivers

**Comment by Skulltrail192** [comment]
Users cannot install ntoskrn8.sys, others drivers can be install without problem

**Comment by Skulltrail192** [comment]
I hope solved on version 2.10.0.
