### ISSUE TITLE
Setting time gets offset

### ISSUE THREAD

**Issue by Demez** [Skulltrail192/One-Core-API-Binaries#104]
Occuring in VMWare - Hardware version 12

Running Windows XP SP3 - with unofficial SP4 install

After I install `one-core-api-app-base.exe`, I am unable to correctly set my time, changing it by a few hours

If I set the time here as shown:
![image](https://user-images.githubusercontent.com/30940677/194211189-e64fb8f9-609b-48d4-a5c6-cdaf675a710d.png)

Then click apply, the time gets offset (maybe by time zone? unsure, the hours it gets offset by sometimes change)
![image](https://user-images.githubusercontent.com/30940677/194211222-8e899971-a4b5-4c7a-8770-4d9fca79fc69.png)

**Comment by RUvlad1** [comment]
Same issue here, my time kept jumping to 02:07 even though it was actually 22:07
Trying to change the date also didn't do anything

**Comment by Legendary-Candice-Joe** [comment]
Bega peanutbutter

**Comment by Skulltrail192** [comment]
Same #172 and #111

**Comment by Skulltrail192** [comment]
Fixed on version 3.0.1
