### ISSUE TITLE
OCA Discord server?

### ISSUE THREAD

**Issue by RUvlad1** [Skulltrail192/One-Core-API-Binaries#107]
[ **Click to join!** ](https://discord.gg/eRcGuFtn6p)

idk if this is what I have to use to ask questions like this, this isn't an issue with One-Core-API or anything and just a general question
sorry in advance if I was supposed to used something else

Anyway, what if there was a Discord server made for One-Core-API related stuff? I think some people might prefer it over GitHub issues since you'll be able to directly chat with people. It could be also used for update announcements and such, maybe a channel where people can showcase various programs they managed to get working on XP, including any workarounds they had to use!

I could help set up and moderate the server if this will be considered, would be nice

**Comment by Skulltrail192** [comment]
Well, i don't know how create it. If you create, i can participe.

**Comment by RUvlad1** [comment]
> Well, i don't know how create it. If you create, i can participe.

Well as I already mentioned I can create and moderate the server
Could you send me a friend request on Discord so I could DM you when I'll start creating the server?
My name and tag is vl1#4881

**Comment by RUvlad1** [comment]
Here's what I made so far
https://discord.gg/eRcGuFt[](https://discord.gg/eRcGuFtn6p) n6p

It's still a bit incomplete and I think I'm gonna add more stuff when I get home, as of writing this I'm currently in college with my crappy mobile internet :P

**Comment by posreadyxp** [comment]
> Here's what I made so far https://discord.gg/eRcGuFt
> 
> It's still a bit incomplete and I think I'm gonna add more stuff when I get home, as of writing this I'm currently in college with my crappy mobile internet :P

Can You create new invite link? (unlimited invite link :>)

**Comment by RUvlad1** [comment]
> Can You create new invite link? (unlimited invite link :>)

Strange, I thought I made it permanent, here you go
https://discord.gg/eRcGuFtn6p

**Comment by RUvlad1** [comment]
Hey @Skulltrail192, could you add the Discord server invite to the readme?
Also, what's your username and tag? (Probably should've asked way earlier but oh well)

**Comment by Skulltrail192** [comment]
> Hey @Skulltrail192, could you add the Discord server invite to the readme? Also, what's your username and tag? (Probably should've asked way earlier but oh well)

Did! Already on Readme.md. Close issue.
