### ISSUE TITLE
Chromium 108 fails to launch on x86 XP...

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [Skulltrail192/One-Core-API-Binaries#108]
Tried installing it via the installer doesn't work, neither does manually extracting it.

**Comment by RetroSoftwareRepository** [comment]
Specifications for my system:
Socket 423 Pentium 4 (1.4 GHz) with 512 MB of RDRAM 
80 GB Seagate Barracuda IDE HDD with XP Black Edition SP3 installed 
Latest One Core API
PNY GeForce FX5500 AGP (128 MB)
FireWire 400 card
TV tuner/analog capture card
Turtle Beach Santa Cruz sound card

Interestingly enough it's actually pretty solid now compared to how it was previously with an older version of the API... no BSODs yet to speak of!

**Comment by Skulltrail192** [comment]
I think Chrome required SSE2, and first generation of Pentium 4 doesn't have. And, Chrome require a amount of memory very large. I only can launch Chrome with minimum 2GB of RAM, and 4 GB is recommended.

**Comment by RetroSoftwareRepository** [comment]
@Skulltrail192 actually it supports SSE2, as the equivalent Athlons only had SSE and 3DNow!

**Comment by RetroSoftwareRepository** [comment]
And actually to verify it does... it can run SlimJet browser, which requires SSE2 to run.

**Comment by RetroSoftwareRepository** [comment]
I had Chromium 100 running on my Socket 462 Sempron (which clearly doesn’t have SSE2)… although that was under 8 Consumer Preview.Sent from my iPadOn Oct 13, 2022, at 3:29 PM, Smu1zel ***@***.***> wrote:﻿

@Skulltrail192 actually it supports SSE2, as the equivalent Athlons only had SSE and 3DNow!

Chromium since 89 started requiring SSE3 for some reason. Edge doesn't have this requirement weirdly and my Socket 478 board running 7 could run Edge 106 just fine (the latest at the time). If Chrome 108 still doesn't run in a VM with a modern CPU, then it's a safe bet there's still more work to be done.

**Comment by WindowsCola** [comment]
> I had Chromium 100 running on my Socket 462 Sempron (which clearly doesn’t have SSE2)… although that was under 8 Consumer Preview.Sent from my iPadOn Oct 13, 2022, at 3:29 PM, Smu1zel ***@***.***> wrote:﻿ @Skulltrail192 actually it supports SSE2, as the equivalent Athlons only had SSE and 3DNow! Chromium since 89 started requiring SSE3 for some reason. Edge doesn't have this requirement weirdly and my Socket 478 board running 7 could run Edge 106 just fine (the latest at the time). If Chrome 108 still doesn't run in a VM with a modern CPU, then it's a safe bet there's still more work to be done. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

I guess that is related to the application api issue.This issue has happened since chrome 103.I recommend you try to install chrome 102 or try to run Microsoft Edge, a complete tutorial video is here: https://www.youtube.com/watch?v=Di1onSbU7hA&t=277s

**Comment by Stepman123** [comment]
> > run Microsoft Edge, a complete tutorial video is here: https://www.youtube.com/watch?v=Di1onSbU7hA&t=277s
How to run the debugger so that it reacts?  My browser crashes after 20 seconds, but the debugger does not launch its window.

**Comment by Skulltrail192** [comment]
Fixed at version  3.0.2. See chrome main thread: #178
