### ISSUE TITLE
Chromium 106 and higher crashes upon launching

### ISSUE THREAD

**Issue by RUvlad1** [Skulltrail192/One-Core-API-Binaries#109]
Crashes upon launching, though there's a chance that you'll see the Chromium window for a second before it closes

[debug.log](https://cdn.discordapp.com/attachments/1030465590491611136/1030466388462149732/debug.log)

![Windows XP Professional-2022-10-14-12-59-55](https://user-images.githubusercontent.com/60317461/195853970-d12b7fb1-2c1f-4333-accd-64b4123ef05b.png)

**Comment by Skulltrail192** [comment]
Fixed at version 3.0.2. See chrome main thread: #178
