### ISSUE TITLE
Launching a Windows 7 game while your screen resolution is set to 1080p causes a BSOD

### ISSUE THREAD

**Issue by RUvlad1** [Skulltrail192/One-Core-API-Binaries#110]
OS: Windows XP 32-bit

![image](https://user-images.githubusercontent.com/60317461/195983023-6e818305-aab7-43b2-9465-d8e8c8fd0606.png)

![image](https://user-images.githubusercontent.com/60317461/195983040-eebea919-f77d-4357-9eb3-ba1e82c3e827.png)

https://user-images.githubusercontent.com/60317461/195983048-1f18ba65-0a93-45dc-a1eb-15f25cb2ba65.mp4

**Comment by Skulltrail192** [comment]
What vmware version?

**Comment by RUvlad1** [comment]
> What vmware version?

16.2.4

**Comment by Skulltrail192** [comment]
Try set compatbility to vmware 12.

**Comment by Skulltrail192** [comment]
Fixed on version 3.0.1.
