### ISSUE TITLE
The time is broken when trying to change it.

### ISSUE THREAD

**Issue by Pokemonfan1000** [Skulltrail192/One-Core-API-Binaries#111]
After installing this, the time breaks. When you open up the Date/Time settings and change the time, after hitting apply, it changes it to something else that is incorrect. Changing the timezone also does not work as it too changes to a completely different time. Hitting Ok on the dialog box causes the time to change yet again. Hitting Cancel does not change the time. Hopefully this can get fixed.

**Comment by minediamonds304** [comment]
I have noticed this issue on x64 real an virtualised (I'm not sure if it occurs on x32) but it can be very annoying when using some browsers and apps

**Comment by Pokemonfan1000** [comment]
I can confirm this occurs with 32-bit (x86) on real hardware (Acer Aspire E1-531 with Sandy Bridge). My clock is 5 hours behind, saying it is 2:40 PM.

**Comment by Demez** [comment]
I had made a post about this here: #104

**Comment by Skulltrail192** [comment]
Fixed on version 3.0.1.
