### ISSUE TITLE
BSOD after installing one-core-api (Windows XP SP3 crash)

### ISSUE THREAD

**Issue by Cixert** [Skulltrail192/One-Core-API-Binaries#113]
After installing 2.10 version I have received BSOD when rebooting the Windows XP SP3 system.
STOP: 0x0000008E (...)
Luckily I was able to reboot into safe mode, uninstalled one-core-api and Windows started again.

To install I have followed some instructions that I have seen on a website in Spanish.
https://www.genbeta.com/windows/this-hack-has-managed-to-run-modern-windows-xp-applications-so-you-can-use-it-chrome-102

It says:
1-Convert XP to Windows embedded and apply Windows update
(I understand that this step is not necessary and I have not done it)
2-Paste the Windows Vista dll oleacc.dll into system32
I have done it, is it necessary?
3-On this website I have seen an order to install the APIs. You show another order in your instructions. Neither of these is possible. what is the correct order?

Genbeta spanish web:
Base Installer > New Installer (Additional DLLs) > D3d Installer > API-SET Installer > App Compat > Kernel Update.
Is there or isn't there an experimental kernel update? I do not see it.

Skulltrail192
Installation order of packages:

App Compat only: This package can be installed without any other packages;

Base first: Base-> D3d -> API-SET -> Driver Update -> App Compat-> Additional Dlls;

AppCompat first: App Compat -> Base -> Driver Update -> D3d -> API-SET -> Additional Dlls.

If I try to install D-3-d before API-SET, it gives an error and tells API-SET to be installed before.

**Comment by Smu1zel** [comment]
Is this a VM or real hardware? If it's real hardware, I'd recommend saying what CPU you have and stuff. Pentium 3s for example historically had issues according to some Reddit threads and it should've been fixed in 2.10 with the correct HAL being loaded.

**Comment by Cixert** [comment]
It is Intel Core i3 firt generation, I have 8 GiB RAM and SSD disk (Acer Aspire X3900 aka AX3900). If install I remember problems with winusb.sys

**Comment by Smu1zel** [comment]
> Real hardware. It is Intel Core i3 firt generation, I have 8 GiB RAM and SSD disk (Acer Aspire X3900 aka AX3900). If install I remember problems with winusb.sys

It looks like a "PAGE_FAULT_IN_NONPAGED_AREA" BSOD. If that's correct, it's probably this dreaded issue I should've probably reported earlier. Basically, if I give my XP VM like 3.5 GB or RAM or more, it becomes pretty unstable and crashes frequently. Going down to like 3GB fixes it but that isn't a long term solution for modern machines.

Does the machine at least get past the "Welcome" screen? Almost every time I've had this issue it crashes shortly before the security center bubble comes up, or when I stress the machine more (I had this happen a lot testing Minecraft 1.19.2). And everytime, it's the same page fault error.

**Comment by Skulltrail192** [comment]
> After installing 2.10 version I have received BSOD when rebooting the Windows XP SP3 system. STOP: 0x0000008E (...) Luckily I was able to reboot into safe mode, uninstalled one-core-api and Windows started again.
> 
> To install I have followed some instructions that I have seen on a website in Spanish. https://www.genbeta.com/windows/this-hack-has-managed-to-run-modern-windows-xp-applications-so-you-can-use-it-chrome-102
> 
> It says: 1-Convert XP to Windows embedded and apply Windows update (I understand that this step is not necessary and I have not done it) 2-Paste the Windows Vista dll oleacc.dll into system32 I have done it, is it necessary? 3-On this website I have seen an order to install the APIs. You show another order in your instructions. Neither of these is possible. what is the correct order?
> 
> Genbeta spanish web: Base Installer > New Installer (Additional DLLs) > D3d Installer > API-SET Installer > App Compat > Kernel Update. Is there or isn't there an experimental kernel update? I do not see it.
> 
> Skulltrail192 Installation order of packages:
> 
> App Compat only: This package can be installed without any other packages;
> 
> Base first: Base-> D3d -> API-SET -> Driver Update -> App Compat-> Additional Dlls;
> 
> AppCompat first: App Compat -> Base -> Driver Update -> D3d -> API-SET -> Additional Dlls.
> 
> If I try to install D-3-d before API-SET, it gives an error and tells API-SET to be installed before.

Try uninstall One-Core-API driver update.

**Comment by Cixert** [comment]
The BSOD is before the splash screen. It is not PAGE_FAULT_IN_NONPAGED_AREA.
I have uninstalled drivers update and then I get a new BSOD "RegOpenExA in KERNEL32 dynamic link library".
And now Windows does not start the system in "Safe" mode
So I have had to reset the registry from another operating system.
So I have reinstalled ONE-CORE-API, with the intention of uninstalling everything again.
I have installed it from normal Windows and I have rebooted directly to "Safe" mode, but when I have uninstalled half of "ONE-CORE-API" packages I have forgotten to check "do not reboot now" in an uninstall.
Then I got "RegOpenExA in KERNEL32 dynamic link library" BSOD again and had to reset the registry again.
At this point I have re-installed and re-uninstalled all the packages at once.
But now the system no longer starts, despite uninstalling everything, the BSOD "RegOpenExA in the dynamic link library KERNEL32" still appears.
From another operating system I see that not all the DLL libraries have been uninstalled.
I have had to manually remove the DLL v. 6.0 and copied libraries v. 5.1 from the "dllcache" folder.
Now the system boots up but when I open any program in Windows it shows the error procedure "RegOpenExA in dynamic link library KERNEL32" is not found

**Comment by Cixert** [comment]
I have restored all the original libraries that I could.
Now I no longer get the error "RegOpenExA in dynamic link library KERNEL32 is not found" when I open a file.
But Windows XP is not stable yet.
When I right click on a file and hit properties then explorer.exe crashes.
Although my Windows XP is in Spanish, some dialogs still appear in English.
For example the tools tab in device manager.
I can't find any more 6.0 version files on my system
please, what could be the problem?

**Comment by Skulltrail192** [comment]
> After installing 2.10 version I have received BSOD when rebooting the Windows XP SP3 system. STOP: 0x0000008E (...) Luckily I was able to reboot into safe mode, uninstalled one-core-api and Windows started again.
> 
> To install I have followed some instructions that I have seen on a website in Spanish. https://www.genbeta.com/windows/this-hack-has-managed-to-run-modern-windows-xp-applications-so-you-can-use-it-chrome-102
> 
> It says: 1-Convert XP to Windows embedded and apply Windows update (I understand that this step is not necessary and I have not done it) 2-Paste the Windows Vista dll oleacc.dll into system32 I have done it, is it necessary? 3-On this website I have seen an order to install the APIs. You show another order in your instructions. Neither of these is possible. what is the correct order?
> 
> Genbeta spanish web: Base Installer > New Installer (Additional DLLs) > D3d Installer > API-SET Installer > App Compat > Kernel Update. Is there or isn't there an experimental kernel update? I do not see it.
> 
> Skulltrail192 Installation order of packages:
> 
> App Compat only: This package can be installed without any other packages;
> 
> Base first: Base-> D3d -> API-SET -> Driver Update -> App Compat-> Additional Dlls;
> 
> AppCompat first: App Compat -> Base -> Driver Update -> D3d -> API-SET -> Additional Dlls.
> 
> If I try to install D-3-d before API-SET, it gives an error and tells API-SET to be installed before.

How do this step: 
Convert XP to Windows embedded and apply Windows update?

**Comment by mina354** [comment]
> > After installing 2.10 version I have received BSOD when rebooting the Windows XP SP3 system. STOP: 0x0000008E (...) Luckily I was able to reboot into safe mode, uninstalled one-core-api and Windows started again.
> > To install I have followed some instructions that I have seen on a website in Spanish. https://www.genbeta.com/windows/this-hack-has-managed-to-run-modern-windows-xp-applications-so-you-can-use-it-chrome-102
> > It says: 1-Convert XP to Windows embedded and apply Windows update (I understand that this step is not necessary and I have not done it) 2-Paste the Windows Vista dll oleacc.dll into system32 I have done it, is it necessary? 3-On this website I have seen an order to install the APIs. You show another order in your instructions. Neither of these is possible. what is the correct order?
> > Genbeta spanish web: Base Installer > New Installer (Additional DLLs) > D3d Installer > API-SET Installer > App Compat > Kernel Update. Is there or isn't there an experimental kernel update? I do not see it.
> > Skulltrail192 Installation order of packages:
> > App Compat only: This package can be installed without any other packages;
> > Base first: Base-> D3d -> API-SET -> Driver Update -> App Compat-> Additional Dlls;
> > AppCompat first: App Compat -> Base -> Driver Update -> D3d -> API-SET -> Additional Dlls.
> > If I try to install D-3-d before API-SET, it gives an error and tells API-SET to be installed before.
> 
> How do this step: Convert XP to Windows embedded and apply Windows update?

I think he means Convert XP to PosReady and apply Windows updates, because once PosReady updates trick is applied, XP Embedded updates are also offered as well, not just PosReady updates.

> Although my Windows XP is in Spanish, some dialogs still appear in English.

Well, One-Core-API is in English for now, so that's expected.

**Comment by Skulltrail192** [comment]
Well, please test again with newer versions. If get same issue, so, reopen this issue and share the windows ISO used and detailed steps.
