### ISSUE TITLE
Qualcomm Atheros AR5B125 64-bit Wi-Fi driver broken after installing 64-bit One-core-api

### ISSUE THREAD

**Issue by Pokemonfan1000** [Skulltrail192/One-Core-API-Binaries#114]
Hi! I set up an install of Windows XP 64-bit. I installed all of the drivers first including the Qualcomm Atheros AR5B125 WiFi driver. The AR5B125 driver worked just fine, however, after installing one-core api, the driver throws an Error 10 in Device Manager. Trying to reinstall it produces the same issue. A USB WiFi adapter with XP drivers works just fine and is what I'm using right now. Anyone have any ideas on how to get the AR5B125 driver working again? To reiterate, it worked just fine in vanilla 64-bit XP, but not after installing one-core api. Any help greatly appreciated!

**Comment by Skulltrail192** [comment]
Are you installed all one-core-api packages? If yes, try uninstall one-core-api driver update package

**Comment by Pokemonfan1000** [comment]
Yes, it is all installed. I installed the driver even before installing one-core api and it worked just fine. It doesn't break until after I install the one-core api. I can get Wi-Fi to work by way of a USB Wi-Fi adapter and Ethernet, but I would prefer the driver to work so I don't 1. lose out on a USB port and 2. Have to be tied to Ethernet.

**Comment by Skulltrail192** [comment]
How i said, try uninstall One-core-API Driver Update.

**Comment by Pokemonfan1000** [comment]
Whoops, I misread your post. I will try that and get back to you.

**Comment by Pokemonfan1000** [comment]
I uninstalled One-core-api driver update and the AR5B125 driver is still throwing a Code 10 error.

**Comment by Pokemonfan1000** [comment]
I can confirm Intel's Centrino line of WiFi cards, such as the Ultimate N-6300 work just fine after installing this, so if you have an Atheros card like mine above, you will want to swap it out for a Centrino card unless you want to use USB WiFi. Keep in mind, I did not swap out (even though I have a spare Centrino to do so), rather, this was done on a Dell Latitude E6530, which has the card already, and not the Aspire E1-531, which came with Centrino, but which I swapped out in favor of Atheros card.

**Comment by Skulltrail192** [comment]
Too old issue, will be closed. If keep getting error, open again.
