### ISSUE TITLE
BOSD After Install

### ISSUE THREAD

**Issue by jeanluc162** [Skulltrail192/One-Core-API-Binaries#115]
I'm experiencing a BOSD during boot (before login/welcome screen) after installing One Core API. Removing all external hardware did not bring any change. The PC reboots after a split second and no (mini)dump is created.
I've attached the system information.
[DxDiag.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9838043/DxDiag.txt)
[msinfo32.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9838044/msinfo32.txt)

**Comment by Skulltrail192** [comment]
Give the configuration, if is VM, real hardware and iso.

**Comment by jeanluc162** [comment]
Yes it was on real hardware, please refer to the attached text-files for the complete information.

The system is a stock (but completly patched) XP x64.

**Comment by Smu1zel** [comment]
> I'm experiencing a BOSD during boot (before login/welcome screen) after installing One Core API. Removing all external hardware did not bring any change. The PC reboots after a split second and no (mini)dump is created. I've attached the system information. [DxDiag.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9838043/DxDiag.txt) [msinfo32.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9838044/msinfo32.txt)

Well great, I guess that bug with Pentium IIIs still isn't fixed. The only pre SSE2 system I have is a Pentium 133, which can run XP, albeit slowly. I should maybe test in 86box to see if it crashes there too.

Basically, I haven't found any success stories of OCAPI on pre Pentium 4 hardware on Reddit. I think if you build it yourself with IA-32 instead of SSE2 it might work? Though SSE might not even be the issue here. Has anyone had any success on a socket 478 Pentium 4 here?

**Comment by Smu1zel** [comment]
Wait nevermind, x64 Pentium III Xeon?

**Comment by Skulltrail192** [comment]
> I'm experiencing a BOSD during boot (before login/welcome screen) after installing One Core API. Removing all external hardware did not bring any change. The PC reboots after a split second and no (mini)dump is created. I've attached the system information. [DxDiag.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9838043/DxDiag.txt) [msinfo32.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9838044/msinfo32.txt)

Are you using USB Wifi?

**Comment by Skulltrail192** [comment]
Well, since it is too old and all my test don't get BSOD, will be closed.
