### ISSUE TITLE
Steam problem Network

### ISSUE THREAD

**Issue by ghost** [Skulltrail192/One-Core-API-Binaries#116]
After install Steam and set compatability to Windows 7 or 10, Steam cant connect to server steam (show error cant connect to internet)

**Comment by Sleora** [comment]
Yeah me too, don't know why. It gives me the error on VMware. I'll try on real hardware.

**Comment by Rapaduraw** [comment]
i have the same problem here in real hardware

**Comment by Skulltrail192** [comment]
Same #149

**Comment by Skulltrail192** [comment]
Closing in  favor to Oficial Thread discussion.
