### ISSUE TITLE
Password for ZIP file

### ISSUE THREAD

**Issue by MSWinNT** [Skulltrail192/One-Core-API-Binaries#117]
What is the passcode?

**Comment by NEO-SPECTRUMAN** [comment]
where is zip with password?

**Comment by MSWinNT** [comment]
I downloaded it on Serv
![Screenshot 2022-10-27 125823](https://user-images.githubusercontent.com/116831825/198352760-3034d7e3-e46c-4d5a-822b-d34622ab822b.png)
er 2003 R2 Datacenter x64-bit, when I extract the files it shows enter password and here is the prove.

**Comment by MSWinNT** [comment]
Can someone help me please?

**Comment by NEO-SPECTRUMAN** [comment]
for installing OCAPI you don't need to download all repo with all trash
you need only this zip with installers inside
https://github.com/Skulltrail192/One-Core-API-Binaries/releases
![2022-10-27_201317](https://user-images.githubusercontent.com/88002487/198355804-386393a5-0400-4046-a9cf-b3ca8a34ce46.png)
![2022-10-27_201504](https://user-images.githubusercontent.com/88002487/198355837-a9e27201-deeb-4151-8239-45cf5f0ebdeb.png)

**Comment by Smu1zel** [comment]
Looks like you're cloning the repo here and extracting it, that's not adviced unless you're a dev willing to help out. Try the latest release under "Releases", though why you're getting promoted for a password I have no clue. Git clones and zip downloads from a repo aren't password protected.

The actual repo seems to be some assets used to package that XP patch looking installer that you get from releases.

**Comment by Skulltrail192** [comment]
One-Core-API binaries doesn't have any password. Download again and use winrar. Closing.
