### ISSUE TITLE
How to update One-Core-API on Windows XP?

### ISSUE THREAD

**Issue by dawid5635** [Skulltrail192/One-Core-API-Binaries#118]
I want to know how to update programs. Install like normally or something different?

**Comment by RUvlad1** [comment]
By update programs do you mean installing One-Core-API or updating a program that you installed with One-Core-API?

**Comment by dawid5635** [comment]
> By update programs do you mean installing One-Core-API or updating a program that you installed with One-Core-API?

yeah  updating a program that I installed with OneCoreAPI. Sorry for not commenting.

**Comment by RUvlad1** [comment]
> yeah updating a program that I installed with OneCoreAPI. Sorry for not commenting.

Just use the updater that came with the program if it has one, if it doesn't work then you might have to do it manually by either getting the latest installer and extracting it as an archive or install the updated version on a pc running 7 and copy over the installed files to XP

**Comment by Skulltrail192** [comment]
One-Core-API packages are distruibuted as Windows Hotfixes. So, if you want update, before you must uninstall the older update package (like d3d package).  After uninstall of old package, install the new version of package.

**Comment by dawid5635** [comment]
> One-Core-API packages are distruibuted as Windows Hotfixes. So, if you want update, before you must uninstall the older update package (like d3d package). After uninstall of old package, install the new version of package.

ok thank you! 
p.s. i am using this on vm and i can say that i am impressed.
