### ISSUE TITLE
CryptExtOpenCER Problem

### ISSUE THREAD

**Issue by jonm58** [Skulltrail192/One-Core-API-Binaries#119]
![image](https://user-images.githubusercontent.com/73036321/198838511-caeb39b5-35fd-4772-902f-e2786a96bbcc.png)
I can't open this Certificates

**Comment by jdpatdiscord** [comment]
have this same issue

**Comment by Skulltrail192** [comment]
Already fixed, will be avaliable on next release.

**Comment by Skulltrail192** [comment]
Fixed on version 3.0.1.
