### ISSUE TITLE
OCAB error when installing one-core-api-app-base

### ISSUE THREAD

**Issue by Sleora** [Skulltrail192/One-Core-API-Binaries#120]
Everything is in the title, I got an "OCAB - Access Denied" error at the end of the install for the App Base module which make my computer restart. I tried to install it in Administrator mode which do nothing. I suspect it might be because I installed the Windows XP - SP4 and made some incompatibilities but I'm not sure.

**Comment by kacperc99** [comment]
Can someone answer it? I have exactly the same problem and there is no solution on the internet.

**Comment by Skulltrail192** [comment]
Well, try version 3.0.0 or 3.0.1

**Comment by kacperc99** [comment]
> Well, try version 3.0.0 or 3.0.1

Do I have to uninstall old AppCompat? And if so, how do I do that?

**Comment by Skulltrail192** [comment]
No, you don't need

**Comment by Skulltrail192** [comment]
As there was no response following a new test, this topic will be closed

**Comment by olzzon08** [comment]
i have the same issues and i have the latest version of OCAB (3.0.5). Ive also tried the master one and it says that cmdl32.d is missing. ive tried to replace the file but to no avail so i tried the normal latest one thats not downloaded from the green code button and it just has the "Access denied" error
