### ISSUE TITLE
DELTARUNE.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by woot000** [Skulltrail192/One-Core-API-Binaries#121]
When running Windows XP Professional x86 on VMWare 16.2.4 with VMWare Tools and all One-Core-API binaries installed, attempting to run the [DELTARUNE Chapters 1 and 2 Demo](https://tobyfox.itch.io/deltarune) results in an Entry Point Not Found error:
```
The procedure entry point WinHttpWebSocketReceive could not be located in the dynamic link library WINHTTP.dll.
```
![image](https://user-images.githubusercontent.com/97068837/199362045-9ea8d064-c251-43ce-a7b3-a5e151edf424.png)

This occurs with and without the ampersand being in the path of the executable.

**Comment by huyloi101** [comment]
maybe WINHTTP.dll is old and is cant hold game

**Comment by Smu1zel** [comment]
This seems to be a Windows 8 function, and there seems to be a workaround for 7 [here][(url](https://steamcommunity.com/app/1671210/discussions/0/3281443422917249913/)). It, however, requires Steam to be functioning, which doesn't currently work.

**Comment by OptiJuegos** [comment]
Fixed by using an older version of the game (version 1.07) that has chapter 2
![Screenshot_1](https://user-images.githubusercontent.com/94207445/205962829-5eb301bd-1f43-410c-ae95-333ebd6e5fd5.png)

**Comment by kotyaralih** [comment]
@OptiJuegos any version of deltarune gives me a black screen, but the game is working (it just do not displays), do you know how to fix this?

**Comment by OptiJuegos** [comment]
You tried to use OpenGL Mesa?

**Comment by Skulltrail192** [comment]
This is a Win8+ game, right?

**Comment by Stepman123** [comment]
> This is a Win8+ game, right?

1.10 - Win7 x64+
0.6.6.6 - WinXP

**Comment by Stepman123** [comment]
> This is a Win8+ game, right?

1.10 - Win7 x64+
0.6.6.6 - WinXP

**Comment by Skulltrail192** [comment]
This is strange because WinHttpWebSocketReceive  is a Win8 function.

**Comment by Skulltrail192** [comment]
Test new version of One-Core-API

**Comment by Skulltrail192** [comment]
Closed due not response
