### ISSUE TITLE
BSOD after install (WinXP SP2 x64)

### ISSUE THREAD

**Issue by MeowIce** [Skulltrail192/One-Core-API-Binaries#123]
I am getting this BSOD after the installation of OCAPI.
Video: 
https://user-images.githubusercontent.com/70711319/201527332-a2b73263-9556-44ba-8da6-c816b0fb56e4.mp4

Installation order: **AppCompat first**: App Compat -> Base -> Driver Update -> D3d -> API-SET -> Additional Dlls.
Virtual Box 7.0
BSOD Message: `BAD_POOL_HEADER`
BSOD Stop Code: `0x00000019`
Memory: 512MB
CPU: i7 720Q

**Comment by Smu1zel** [comment]
Yet another memory related issue, starting to think some memory management stuff from ReactOS is getting inherited, causing all these issues. I myself have had IRQL_NOT_LESS_OR_EQUAL when I bump the memory over 3.1GB or so. This was on XP x86.

**Comment by Skulltrail192** [comment]
Are you using USB wifi?

**Comment by MeowIce** [comment]
> Are you using USB wifi?

It's a VirtualBox VM

**Comment by Skulltrail192** [comment]
Please, install latest version

**Comment by Skulltrail192** [comment]
> > Are you using USB wifi?
> 
> It's a VirtualBox VM

However, usb wifi can be recognized and used by VM.

**Comment by Skulltrail192** [comment]
Please test again with version 3.0.1. Seem fixed.
