### ISSUE TITLE
One-Core-API Binary is reported as Malware by Online Virus Scanner

### ISSUE THREAD

**Issue by ghostplant** [Skulltrail192/One-Core-API-Binaries#124]
Why?

**Comment by Smu1zel** [comment]
Which installer? I can assure you OCAPI is not malware, nor was it ever. It's likely the detection stems from the fact it's sort of packaged inside a XP patch, or the fact it patches critical system files to achieve its compatibility. Just note that some hardware can have issues, and if you encounter any, please report them here in "Issues". I myself have been able to get it to successfully install and boot on emulated systems as old as a Pentium MMX, but your milage may vary.

**Comment by ghostplant** [comment]
Yeah, I downloaded it from the release tab, and definitely we don't expect it should include some malware behaviors. But you can just try uploading the binary from release to https://www.virustotal.com/gui/home/upload. Files will go through a bunch of different virus scanning engine, and most of the engines report some problems in it.

**Comment by Skulltrail192** [comment]
Just ignore!

**Comment by NEO-SPECTRUMAN** [comment]
> Why?

because normal software usually doesn't wrap system files
it usualy do various malware
