### ISSUE TITLE
Cannot use LegacyUpdate

### ISSUE THREAD

**Issue by techguy16** [Skulltrail192/One-Core-API-Binaries#125]
I have OneCoreAPI installed in a VM and I tried to update it with the LegacyUpdate project, but it keeps throwing me this error:
`0x80248011 (-2145091567): Could not create a data store object in another process. `

According to the author of the LegacyUpdate project, this is a problem with OneCoreAPI

Can this be fixed?

**Comment by Skulltrail192** [comment]
What is LegacyUpdate?

**Comment by techguy16** [comment]
https://github.com/kirb/LegacyUpdate 
It is a revival of the Windows Update platform for Windows XP/Server 2003.

**Comment by RUvlad1** [comment]
A temporary solution would be to install Legacy Update before installing One-Core-API

**Comment by techguy16** [comment]
> 

Yes I could do that, but I am making custom ISOs with nLite that I want to have both OneCoreAPI and LegacyUpdate.

**Comment by Skulltrail192** [comment]
Seem fixed on version 3.0.1.

**Comment by Stepman123** [comment]
> Seem fixed on version 3.0.1.

Yes, it works.
