### ISSUE TITLE
VGMPlay 0.51.0 64-bit doesn't work on XP x64 edition

### ISSUE THREAD

**Issue by Epictyphlosion** [Skulltrail192/One-Core-API-Binaries#126]
The following error shows up upon starting the program
`The procedure entry point combase.RoActivateInstance could not be located in the dynamic link library api-ms-win-core-winrt-l1-1-0.dll.`

Program link: https://vgmrips.net/forum/viewtopic.php?t=112

![error1](https://user-images.githubusercontent.com/34047941/203270992-c94f88fe-bd78-4dd7-8ff1-9b55228143e5.png)

**Comment by Skulltrail192** [comment]
Now working:
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/f82da322-dcf1-488f-bade-42034f45fac3)
