### ISSUE TITLE
Some abnormalities when installed on POSReady 2009

### ISSUE THREAD

**Issue by sal-ammoniac** [Skulltrail192/One-Core-API-Binaries#129]
1 System Properties and Winver shows "Windows XP Embedded" rather than "Windows Embedded POSReady 2009" 
![屏幕截图 2022-11-29 182234](https://user-images.githubusercontent.com/116893674/204504134-79dad319-84f3-4fe3-9bb7-9112cbb92936.png)
![屏幕截图 2022-11-29 182416](https://user-images.githubusercontent.com/116893674/204504261-f279c3ee-18fe-4e53-9de8-7a94d86713e7.png)
2 The Dxdiag was partly broken?
![屏幕截图 2022-11-29 182522](https://user-images.githubusercontent.com/116893674/204504526-87a396d3-8c21-48a2-b679-3626b172ae2e.png)
3 Also,It breaks the MUI.

**Comment by sal-ammoniac** [comment]
So should compatiability with Windows XP Embedded（including POSReady 2009,Embedded Standard 2009,WinFLP）be taken into consideration for the further development?

**Comment by sal-ammoniac** [comment]
The solution of problem 1:
replace winbrand.dll with the one from original POSReady 2009.

**Comment by RUvlad1** [comment]
The 3rd issue is happening due to OCA not supporting MUI iirc, which could be also the reason why the 2nd issue exists

**Comment by sal-ammoniac** [comment]
> The 3rd issue is happening due to OCA not supporting MUI iirc, which could be also the reason why the 2nd issue exists

Thanks. Hoping these issues be solved later.

**Comment by Skulltrail192** [comment]
Same issue: https://github.com/Skulltrail192/One-Core-API-Binaries/issues/171

**Comment by Skulltrail192** [comment]
Same issue: https://github.com/Skulltrail192/One-Core-API-Binaries/issues/129
