### ISSUE TITLE
xp sp3

### ISSUE THREAD

**Issue by darkknight1025** [Skulltrail192/One-Core-API-Binaries#13]
trying to install .net 4.5 full in xp sp3
indicates windows module installer is not present and the program is not compatible with this os
yes all modules have been installed etc
updates are also uptodate
could you please update installer and install packages
instructions and an order of their installation would also be greatly appreciated
will you be able to import the lddm for ie9 and the later install as well

**Comment by Skulltrail192** [comment]
Well, only ignore this message and install. You need all packages, except Kernel update. Lddm and ie9 for now, not

**Comment by darkknight1025** [comment]
unfortunately you cannot ignore those messages on that platform .it stops the install and it will not continue past

**Comment by SSJ9899TDylan** [comment]
This is why we should port these things to XP

**Comment by darkknight1025** [comment]
keep in mind xp64/server 2003 have much in common and for kernel sake are similar enough where features from vista can easily enough be ported due to a similar structure
from what i can gather the research kernel was already integrated to probably assist with that

**Comment by Skulltrail192** [comment]
Why can i install without problems? Only set program compatibility to Windows Vista or above and be happy.

**Comment by SSJ9899TDylan** [comment]
Don’t give up

**Comment by darkknight1025** [comment]
im going to build 2 additional test beds,i use dated and real hardware not virtualized hardware,one build will be an old dell inspiron running xp media center edition 2005, and another xp pro sp3
the problem with .net is still consistent.reinstall update and begin again
please update docs and installers in both api,and api binaries

**Comment by darkknight1025** [comment]
windows module installer seems to be in some way responsible for those services required and subsequently    
correct library access be related .ie.trusted installer that could be a direction to look into

**Comment by SSJ9899TDylan** [comment]
Alright then. How about you guys even work on msu file support too?

**Comment by SSJ9899TDylan** [comment]
Hey,

I just signed the petition "Lucas Heights Community School: I want my
parents to STOP TAKING MY DEVICES AWAY!" and wanted to see if you could
help by adding your name.

Our goal is to reach 100 signatures and we need more support. You can read
more and sign the petition here:

http://chng.it/T6DGF2r2Kj

Thanks!
Dylan

**Comment by robertcollier4** [comment]
Perhaps upgrade of Windows Installer to 4.5 could be helpful? 4.5 update redistributable is compatible with XP.
https://support.microsoft.com/en-in/help/942288/windows-installer-4-5-is-available

**Comment by Skulltrail192** [comment]
> 
> 
> trying to install .net 4.5 full in xp sp3
> indicates windows module installer is not present and the program is not compatible with this os
> yes all modules have been installed etc
> updates are also uptodate
> could you please update installer and install packages
> instructions and an order of their installation would also be greatly appreciated
> will you be able to import the lddm for ie9 and the later install as well

For install .net Framework on Xp, you only need .Net Framework 2.0, 3,5 and 4.0 before install .net 4.5+ and ignore this warning. It will works fine

**Comment by darkknight1025** [comment]
That was already done prior,afterwards up until 4.0 is installed, once 4.5
goes in ,essentially it wipes out previous including current iterations,
resulting in incompatible requests/requirements for programs that require
the later.trying to bypass the system checks with files,will still result
in failure

**Comment by Skulltrail192** [comment]
Please, try install this sequence:

.Net Framework 2.0, 3.5, 4.0 (if not installed) and now, .net 4.5 with compatibility to Vista Sp2 or above. This works fine

**Comment by darkknight1025** [comment]
That was the sequence that I did,it would appear successful,however the
libraries would overwrite subsequently delete in on instance,and the
programs would also not function properly

**Comment by Skulltrail192** [comment]
Since .net framework 4.5 can be installed using Compatiblity Mode and 4.6= can be installed using alternative installer (see:  https://github.com/abbodi1406/dotNetFx4xW7. And avaliable like here: https://www.wincert.net/forum/topic/13805-microsoft-net-framework-472-full-x86x64-incl-language-packs-by-ricktendo/#comment-123251), this issue will be closed.
