### ISSUE TITLE
One Core API doesn't work at all (Tried 2 distros + Virtual) @Chromim-related

### ISSUE THREAD

**Issue by W1nKille3r** [Skulltrail192/One-Core-API-Binaries#130]
First of all i tried to install any modern Chromium related browser as: Google Chrome 60/Auto Installer; Chromium 102/Latest; Cent Browser Latest/Portable. All of them doesn't start at all or kicks with random error.

**nCore used distro:** https://soft-windows.info/15007-windows-xp-professional-sp3-ncore-v2205-x86-2022-rus.html
Tried: Update all drivers, updating OneCoreAPI, load legacy updates (seems like in this distro update center is deleted)
**Integrated Edition:** https://windows-soft.info/16767-windows-xp-professional-sp3-integral-edition-v202299-x86-2022-eng-rus.html
Tried: Same as listed but when im trying to install software from this distro - he drops random errors about vcruntime or modified dll.

In VirtualBox situation is same as native.

Please help me with that, maybe im doing something wrong because i have no idea why One Core API doesn't work at all.

My build
CPU: Intel Xeon e3 1270 v2
Motherboard: MSI H61M-E33/B3 (MS-7680)
GPU: GTX 770 2 GB VRAM
RAM: 2x4GB 1600Mhz (8gb summary)

**Comment by RUvlad1** [comment]
I've tried both nCore and Integral and I've been facing the same issue, however if I were to assume, that's probably because those custom builds use an outdated version of One-Core-API. I would strongly suggest using OCA on a clean, updated version of XP

**Comment by JakoDel** [comment]
> First of all i tried to install any modern Chromium related browser as: Google Chrome 60/Auto Installer; Chromium 102/Latest; Cent Browser Latest/Portable. All of them doesn't start at all or kicks with random error.
> 
> **nCore used distro:** https://soft-windows.info/15007-windows-xp-professional-sp3-ncore-v2205-x86-2022-rus.html Tried: Update all drivers, updating OneCoreAPI, load legacy updates (seems like in this distro update center is deleted) **Integrated Edition:** https://windows-soft.info/16767-windows-xp-professional-sp3-integral-edition-v202299-x86-2022-eng-rus.html Tried: Same as listed but when im trying to install software from this distro - he drops random errors about vcruntime or modified dll.
> 
> In VirtualBox situation is same as native.
> 
> Please help me with that, maybe im doing something wrong because i have no idea why One Core API doesn't work at all.
> 
> My build CPU: Intel Xeon e3 1270 v2 Motherboard: MSI H61M-E33/B3 (MS-7680) GPU: GTX 770 2 GB VRAM RAM: 2x4GB 1600Mhz (8gb summary)

A bit late, but the link you shared is NOT the official one for integral edition.

**Comment by Skulltrail192** [comment]
Test again with new versions

**Comment by Skulltrail192** [comment]
Since this thread is inative, will be close.
