### ISSUE TITLE
Add support for OpenShell and Better Explorer.

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [Skulltrail192/One-Core-API-Binaries#131]
Adding support for these would make modernizing XP's UI so much easier

**Comment by mina354** [comment]
Personally, I haven't used Better Explorer, but I have used Open Shell, and I like it's functionality (especially the start menus it offers), so yeah, I would like to see Open Shell.

**Comment by Skulltrail192** [comment]
Well, it's need interface/shell port, what i will not do for now.
