### ISSUE TITLE
Sometimes installers don't render UI elements

### ISSUE THREAD

**Issue by RUvlad1** [Skulltrail192/One-Core-API-Binaries#132]
Some installers (usually when they're run with Windows 7 compatibility) have missing UI elements that are un-clickable, navigating with keyboard using Alt + N for Next and such is possible however

![image](https://user-images.githubusercontent.com/60317461/206214896-287bffc7-031f-4229-8e58-975b01cc78cd.png)

So far I've seen this happen with the ShareX installer and the Resource Hacker installer

I'm using Windows XP x64

**Comment by Skulltrail192** [comment]
Well, its occours because Comctrl from XP missing some new button types, like Command Link and others. I will try add it

**Comment by Skulltrail192** [comment]
Well, for some strange reason, it's works fine on Windows XP 32 bits. I discovered what is related with comctl and will replace of Server 2003 with the XP.

**Comment by Skulltrail192** [comment]
It was fixed on Version 3.0.0
![Setup](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/149788e3-de7f-456a-86f5-afbf2e97d09e)

**Comment by Skulltrail192** [comment]
So, i will update version description and close issue.
