### ISSUE TITLE
Windows XP support for WDDM ?

### ISSUE THREAD

**Issue by Kevin0928000** [Skulltrail192/One-Core-API-Binaries#135]
I know it's extremely difficult for XP to support WDDM, but the current software seems to require this feature.
![01](https://user-images.githubusercontent.com/72051291/207212366-3baeffe3-30ec-44e9-9fbf-8b5cd2589114.jpg)

**Comment by Smu1zel** [comment]
> If we can figure out how WDDM works, I believe it will not be far to support Internet Explorer 9 in the future.

WDDM isn't necessarily needed for IE 9+ to work. XPDM drivers (the Win2000-XP graphics driver model) work on as far as Windows 7, and even IE11 works just fine. Whether it's hardware accelerated or not I don't know.

And that exact calculator from 7, and even the built in games, work just fine with XP drivers on my 7 machine (it's an ATI All-in-Wonder 9200 card).

**Comment by Skulltrail192** [comment]
These problems are not related with WDDM. I'm working to fix all.

**Comment by Skulltrail192** [comment]
Same #98
