### ISSUE TITLE
chromium no work on xp x64

### ISSUE THREAD

**Issue by LoliestHuhytre** [Skulltrail192/One-Core-API-Binaries#136]
the title explains it but if you need further explanation here it goes
so basically, everytime i download one-core api it no works
32 bit crashes
64 bit no launch
HELPPPPPPPPP

**Comment by LoliestHuhytre** [comment]
and yes i used the triggers or whatever its called

**Comment by RUvlad1** [comment]
Versions of Chromium higher than 102 do not work

**Comment by K4sum1** [comment]
I tried 100 using this video as a guide on x64, and it crashes immediately after opening

https://www.youtube.com/watch?v=N3BWBj_GIwM

**Comment by RUvlad1** [comment]
> I tried 100 using this video as a guide on x64, and it crashes immediately after opening
> 
> https://www.youtube.com/watch?v=N3BWBj_GIwM

Are you sure One-Core-API has been installed correctly? Which Chromium version specifically were you trying to run?

**Comment by K4sum1** [comment]
100, same one as the video, verified the same method using another x64 VM which didn't work. I also quickly made a x86 VM and the same method works there.

**Comment by Skulltrail192** [comment]
Same #57,109,

**Comment by Skulltrail192** [comment]
Test again. Now, working 64 bits version. 32 bits keep not working. See chrome main thread: #178
