### ISSUE TITLE
Office 2021 on Windows XP SP2

### ISSUE THREAD

**Issue by ALLMAC123** [Skulltrail192/One-Core-API-Binaries#138]
How do I run Office 2021 on Windows XP SP2?

**Comment by Smu1zel** [comment]
Doubt this is possible yet unfortunately, afaik it doesn't even support 7.

**Comment by bw134polska** [comment]
I don't know if Office 2013/2016 works with One-Core API on Windows XP SP3 (and XP Professional x64 SP2), leave alone SP2.

**Comment by Skulltrail192** [comment]
Office 2013/2016/2019/2021 isn't support by Windows XP or Server 2003. It is to do list. The topic will be closed.
