### ISSUE TITLE
Got BSOD on 32bit SP3. Uninstallation?

### ISSUE THREAD

**Issue by HexagonWin** [Skulltrail192/One-Core-API-Binaries#139]
Hi. I installed Windows XP SP3 32bit Integral Edition on my Dell Precision T3600.
System spec is following
- CPU : Intel Xeon E5-1650 (SandyBridge-EP)
- RAM : Samsung DDR3 ECC-REG 4GB*4=16GB (4GB in OS)
- HDD : 80GB Seagate Barracuda 7200rpm
- GPU : Nvidia GT720 2GB
It's a system that works well on vanilla XP when HDD is set to IDE mode but as I dual boot other OSes I installed integral.
After installing Integral Edition I installed the "Inexperience patcher" which patches some system DLLs and replaces WinXP logo/brandings/icons with Win2000's. Then after that I installed Korean language MUI (language pack) official by Microsoft. 

Then I installed OneCore API which caused the problem. I downloaded the latest "release" (from the release page), and installed OneCore API in this order:
`Base -> API-SET (d3d complained for api-set) -> d3d -> driver update -> app compat -> additional dlls`
I rebooted system when I was prompted to, didn't when I wasn't prompted. After installing everything however, no change was visible to me, and on the "Compatibility" tab of each exe/shortcut's "Properties" I got the plain options for Win2K SP4, Win 98, Win 95.. no such thing like vista or newer. I assumed that OneCore API wasn't even installed and that was a huge miss.

I then reinstalled the "Inexperience patcher" because some icons on explorer.exe were replaced with their XP variant again, probably because OneCore API installed a patched XP version of the DLL (should have thought of this). After installing Inexperience I rebooted as usual, and that gave me the issue. System boot takes much longer than usual on the boot screen, and after booting my system shows a BSOD before launching loginui (I have the "Use the new Welcome screen" disabled on Control.exe so it shows the Win2K style login screen). BSOD being about the loginui.

I'd like to know a way to uninstall one-core api or restore my previous system restore points (installer for each onecore api package showed "creating system restore point" while installing..).
I have Windows 7 on another hard drive in the system so I can access the WinXP drive without issues. However safe mode booting doesn't seem to work, as I've tried holding F8 or F5 while booting and it went straight to booting..

Any help appreciated.

**Comment by Doomguy-Palashov** [comment]
Bro. I think one core for now is only for windows x64.🙂

**Comment by JakoDel** [comment]
> Bro. I think one core for now is only for windows x64.🙂
> _This repositry contains binary releases of the One-Core-API project. These are compatible with Windows Server 2003 SP2, Windows XP SP3 and Windows XP x64 SP2._

How did you even come to that conclusion? windows xp sp3 is 32bit, this project is 100% compatible with 32bit xp.

**Comment by JakoDel** [comment]
> Hi. I installed Windows XP SP3 32bit Integral Edition on my Dell Precision T3600. System spec is following
> 
> * CPU : Intel Xeon E5-1650 (SandyBridge-EP)
> * RAM : Samsung DDR3 ECC-REG 4GB*4=16GB (4GB in OS)
> * HDD : 80GB Seagate Barracuda 7200rpm
> * GPU : Nvidia GT720 2GB
>   It's a system that works well on vanilla XP when HDD is set to IDE mode but as I dual boot other OSes I installed integral.
>   After installing Integral Edition I installed the "Inexperience patcher" which patches some system DLLs and replaces WinXP logo/brandings/icons with Win2000's. Then after that I installed Korean language MUI (language pack) official by Microsoft.
> 
> Then I installed OneCore API which caused the problem. I downloaded the latest "release" (from the release page), and installed OneCore API in this order: `Base -> API-SET (d3d complained for api-set) -> d3d -> driver update -> app compat -> additional dlls` I rebooted system when I was prompted to, didn't when I wasn't prompted. After installing everything however, no change was visible to me, and on the "Compatibility" tab of each exe/shortcut's "Properties" I got the plain options for Win2K SP4, Win 98, Win 95.. no such thing like vista or newer. I assumed that OneCore API wasn't even installed and that was a huge miss.
> 
> I then reinstalled the "Inexperience patcher" because some icons on explorer.exe were replaced with their XP variant again, probably because OneCore API installed a patched XP version of the DLL (should have thought of this). After installing Inexperience I rebooted as usual, and that gave me the issue. System boot takes much longer than usual on the boot screen, and after booting my system shows a BSOD before launching loginui (I have the "Use the new Welcome screen" disabled on Control.exe so it shows the Win2K style login screen). BSOD being about the loginui.
> 
> I'd like to know a way to uninstall one-core api or restore my previous system restore points (installer for each onecore api package showed "creating system restore point" while installing..). I have Windows 7 on another hard drive in the system so I can access the WinXP drive without issues. However safe mode booting doesn't seem to work, as I've tried holding F8 or F5 while booting and it went straight to booting..
> 
> Any help appreciated.

you'll probably have to make a fresh install, needless to say but backup your data first

**Comment by Smu1zel** [comment]
> 

Indeed it is of course, the latest release even worked on an emulated Pentium 1 with no ACPI.

**Comment by Smu1zel** [comment]
> Hi. I installed Windows XP SP3 32bit Integral Edition on my Dell Precision T3600. System spec is following
> 
> * CPU : Intel Xeon E5-1650 (SandyBridge-EP)
> * RAM : Samsung DDR3 ECC-REG 4GB*4=16GB (4GB in OS)
> * HDD : 80GB Seagate Barracuda 7200rpm
> * GPU : Nvidia GT720 2GB
>   It's a system that works well on vanilla XP when HDD is set to IDE mode but as I dual boot other OSes I installed integral.
>   After installing Integral Edition I installed the "Inexperience patcher" which patches some system DLLs and replaces WinXP logo/brandings/icons with Win2000's. Then after that I installed Korean language MUI (language pack) official by Microsoft.
> 
> Then I installed OneCore API which caused the problem. I downloaded the latest "release" (from the release page), and installed OneCore API in this order: `Base -> API-SET (d3d complained for api-set) -> d3d -> driver update -> app compat -> additional dlls` I rebooted system when I was prompted to, didn't when I wasn't prompted. After installing everything however, no change was visible to me, and on the "Compatibility" tab of each exe/shortcut's "Properties" I got the plain options for Win2K SP4, Win 98, Win 95.. no such thing like vista or newer. I assumed that OneCore API wasn't even installed and that was a huge miss.
> 
> I then reinstalled the "Inexperience patcher" because some icons on explorer.exe were replaced with their XP variant again, probably because OneCore API installed a patched XP version of the DLL (should have thought of this). After installing Inexperience I rebooted as usual, and that gave me the issue. System boot takes much longer than usual on the boot screen, and after booting my system shows a BSOD before launching loginui (I have the "Use the new Welcome screen" disabled on Control.exe so it shows the Win2K style login screen). BSOD being about the loginui.
> 
> I'd like to know a way to uninstall one-core api or restore my previous system restore points (installer for each onecore api package showed "creating system restore point" while installing..). I have Windows 7 on another hard drive in the system so I can access the WinXP drive without issues. However safe mode booting doesn't seem to work, as I've tried holding F8 or F5 while booting and it went straight to booting..
> 
> Any help appreciated.

I think if you power off the system while booting, you'll get a prompt on next boot with some options that should let you into safe mode.

**Comment by HexagonWin** [comment]
I successfully solved. On System32 folder there's a backup of the original DLLs in specially named folders. I copied them all back to their original folders and windows booted, I removed OCAPI in control panel to get rid of the uninstaller/backup dlls.
