### ISSUE TITLE
BSOD after installing drivers to videocard

### ISSUE THREAD

**Issue by Dev0xz02** [Skulltrail192/One-Core-API-Binaries#143]
![IMG_20230113_132315](https://user-images.githubusercontent.com/68699028/212292312-c2b9021d-b5ad-4941-a257-bc60e1cc657a.jpg)

**Problem is:** Windows crashes when installing drivers to videocard.

**Steps to reproduce the behavior:**

1. Install Windows XP x64 SP1 (ISO: https://disk.yandex.ru/d/Nbhm6dt8AU7ShQ)
2. Install OneCoreAPI 2.10.0 (latest at creating this issue)
3. Reboot, unpack drivers into folder (driver: https://disk.yandex.ru/d/WjOxfA065ya5iA)
4. Install driver using devmgmt.msc (folder: `%rootdrive%\NVIDIA\DisplayDriver\347.52\WinXP_64\International\Display.Driver`, where `%rootdrive%` insert your windows xp drive, dont let windows decide what to install!)
4. Reboot and see error

> Information about the PC:

**Videocard:** NVIDIA GeForce GTX 550 Ti
**Processor:** AMD Athlon(tm) II X2 250, 3.00 GHz
**RAM:** 6,00 GB

> Windows information:

**Windows Version:** XP Professional x64 Edition
**Build:** 3790.srv03_sp2_rtm.220902-0629
**Service Pack:** 1

###### gonna also try installing windows xp x86 sp3

**Comment by Dev0xz02** [comment]
**MiniDump file:** https://disk.yandex.ru/d/KAxQEBetlkFwXQ (look using BlueScreenView)

**Comment by JakoDel** [comment]
quite time-consuming, but try installing the gpu drivers before onecore-api on a fresh install

**Comment by sal-ammoniac** [comment]
try to install service pack 2 and videocard driver first

**Comment by Dev0xz02** [comment]
> try to install service pack 2 and videocard driver first

Hello, sal-ammonaiac. It's still BSOD's the computer, but in this time the error is different. Sorry, I cant attach the file right now, I'm not home in this time. Will attach when I will get to home. Sorry for long answer, I'm a busy man.

**Comment by Dev0xz02** [comment]
> quite time-consuming, but try installing the gpu drivers before onecore-api on a fresh install

Hi, JakoDel. Look what I'm answered to the another guy.

**Comment by Skulltrail192** [comment]
Are you installed all one-core-api packages?

**Comment by Dev0xz02** [comment]
> Are you installed all one-core-api packages?

woah, owner commented.
yeah, i install all one-core-api packages.

**Comment by Dev0xz02** [comment]
im no longer an Windows XP user whatsoever, so i'm thinking of closing this thread.

**Comment by Skulltrail192** [comment]
Since the reporter not use Windows XP anymore and not interestered and i cannot reproduce the error (i install gpu nvdia without problem), this issue will be closed.
