### ISSUE TITLE
.Net Framework apps doesn't work when WinXP isn't installed in C: drive

### ISSUE THREAD

**Issue by JW26T-Prj** [Skulltrail192/One-Core-API-Binaries#145]
If Windows XP isn't installed in C: drive, when i try to run any .NET Framework programs with One-Core-API, it says that .NET Framework isn't installed. It occours with .NET 2.0 to 4.8 apps.

**Comment by Skulltrail192** [comment]
Same #154 

It will be fixed on next release. However, for install .Net Framework 4.5+ you will need install .net 4.0 or lower or copy some files to System32.

**Comment by Skulltrail192** [comment]
Fixed on version 3.0.1.
