### ISSUE TITLE
i use chromium 100 on xp x86 sp3 but crash vmware

### ISSUE THREAD

**Issue by LoliestHuhytre** [Skulltrail192/One-Core-API-Binaries#147]
welp, i tried again, it crashes, i used the flags BUT no work, help me!

**Comment by LoliestHuhytre** [comment]
and i dont want to use chromium based browsers like chrome 360 or minibrowser
and i dont want to use kmelon or mypal

**Comment by LoliestHuhytre** [comment]
the flags are --no-sandbox --force-wave-audio --disable-exclusive-audio --ignore-certificate-errors

**Comment by LoliestHuhytre** [comment]
compability modes wont help

**Comment by jonm58** [comment]
What is you one core api version ?

**Comment by LoliestHuhytre** [comment]
idk what version since i clicked on green code button and not releases

**Comment by LoliestHuhytre** [comment]
but i DO have service pack 3

**Comment by LoliestHuhytre** [comment]
i think i use one core api 2.10.0

**Comment by jonm58** [comment]
i use Integral Edition 2022.9.9 and one core api 2.10.0 releases

**Comment by Stepman123** [comment]
Could it be a problem with the processor?
>In a policy document, the Chromium development team has announced that they are dropping support for all x86 CPUs which do >not have a minimum of SSE3 (Supplemental Streaming SIMD Extensions 3) support, starting in Chrome 89.

**Comment by Smu1zel** [comment]
> Could it be a problem with the processor?
> 
> > In a policy document, the Chromium development team has announced that they are dropping support for all x86 CPUs which do not have a minimum of SSE3 (Supplemental Streaming SIMD Extensions 3) support, starting in Chrome 89.

If OP is using like an Athlon XP or early Pentium 4, this might be the case. You can still technically use Chrome using Edge as it still supports SSE2 systems, but Athlon XPs and Pentium IIIs are out of luck.

**Comment by LoliestHuhytre** [comment]
no tips from yall work

**Comment by Legendary-Candice-Joe** [comment]
Real quick, its worth mentioning you should probably not --disable-exclusive-audio as chrome will most likely be silent. It was for me. Anyway is there any details about said crash? logs? What specific version of chromium are you using, as anything higher than 102 will crash.

**Comment by Skulltrail192** [comment]
Test new version. Chrome 103-109 was fixed at version 3.0.2. See too chrome main thread: #178
