### ISSUE TITLE
"Microsoft Malware Protection Commmand Line Utility has encountered a problem and needs to close."

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [Skulltrail192/One-Core-API-Binaries#148]
After installing Open Core API, I keep getting this message every 30 seconds or so, basically making my XP system unusable. How can I get it to just stop?

**Comment by Noxyntious** [comment]
Uninstall MS Security Essentials

**Comment by Skulltrail192** [comment]
Fixed at version 3.0.3
