### ISSUE TITLE
Portable Office Excel 2007 Russian - Getting ThinApp Error

### ISSUE THREAD

**Issue by Stepman123** [Skulltrail192/One-Core-API-Binaries#150]
This error occurs after installing One Core API.
![text](http://d.zaix.ru/xtQF.bmp)
https://i.postimg.cc/63xhKHR1/excell2.png Alternative link pic.

**Comment by Skulltrail192** [comment]
Can you share the link what i can download this program?

**Comment by Stepman123** [comment]
> Can you share the link what i can download this program?

https://www.upload.ee/files/15673086/Microsoft_Office_Excel_2007_Portable_Rus.rar.html

**Comment by Skulltrail192** [comment]
The fix will be avaliable on next release and on release of week on One-Core-API-Canary. I changed the title to improve identification. I advise creating issues with more specific titles.

**Comment by Skulltrail192** [comment]
Avaliable first on https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/tag/3.0.2-20230927-experimental

**Comment by Stepman123** [comment]
> Avaliable first on https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/tag/3.0.2-20230927-experimental

The same error.

**Comment by Skulltrail192** [comment]
Fixed on version 3.0.2.
