### ISSUE TITLE
Installation problem .NET 4.7 - 4.8.

### ISSUE THREAD

**Issue by Stepman123** [Skulltrail192/One-Core-API-Binaries#151]
.NET 4.5.2 and 4.6 installs fine.
.NET 4.7.2 - 4.8 crashes without errors. This happens at the moment when the final stage of the installation begins.
Windows XP Professional SP3 x86 - Integral Edition
I tried microsoft .NET installers and repack by D!akov.
OneCoreAPI 2.10.
![text](http://d.zaix.ru/xuaz.bmp)
https://i.postimg.cc/L4cd02GR/verifying.png Alternative link pic.

**Comment by JW26T-Prj** [comment]
This error is documented on the README file.

Standard .Net Framework Installers starting 4.6 ins't supported for now. You need a repacked version like did here: https://github.com/abbodi1406/dotNetFx4xW7. And avaliable like here: https://www.wincert.net/forum/topic/13805-microsoft-net-framework-472-full-x86x64-incl-language-packs-by-ricktendo/#comment-123251. Other versions are avaliable too, search on forum topics;

**Comment by Stepman123** [comment]
>Other versions are avaliable too, search on forum topics;

It seems to be installed normally, but my applications give errors. Which applications work with 4.5 - 4.8?

**Comment by RUvlad1** [comment]
> > Other versions are avaliable too, search on forum topics;
> 
> It seems to be installed normally, but my applications give errors. Which applications work with 4.5 - 4.8?

Latest ShareX requires 4.8, from what I've tried it works perfectly fine
