### ISSUE TITLE
.NET Framework 3.5 SP1 & .NET Framework 4.6 Fails to install.

### ISSUE THREAD

**Issue by fireahmedgamerYT** [Skulltrail192/One-Core-API-Binaries#154]
I attempted to install .NET Framework 3.5 and the installation didn't succeed. 
This is what I got
[02/22/23,21:30:12] Microsoft .NET Framework 2.0a: [2] Error: Installation failed for component Microsoft .NET Framework 2.0a. MSI returned error code 1603
[02/22/23,21:30:33] WapUI: [2] DepCheck indicates Microsoft .NET Framework 2.0a is not installed.

As for 4.6, it just tells me that the setup may fail because windows modules installer isn't available on my PC, I can continue but once it gets to installing it, it just poofs.

I have Windows XP installed on real hardware (Daulbooting with Windows 8.1), for .NET 4.6 I set compatibility for Windows 7 or Windows 10 (Anniversary edition), and both result in the same outcome.

Specs:
Intel Core 2 Duo 6300
4 GB RAM DDR2

**Comment by Stepman123** [comment]
Check it.
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework
InstallRoot = (There may be an incorrect value for the drive letter. )

**Comment by Skulltrail192** [comment]
Thanks, i will fix on next release.

**Comment by Skulltrail192** [comment]
Same #145 It will be fixed on next release. However, for install .Net Framework 4.5+ you will need install .net 4.0 or lower or copy some files to System32.

**Comment by Skulltrail192** [comment]
Fixed on version 3.0.1.
