### ISSUE TITLE
OCAB error while trying to install Base

### ISSUE THREAD

**Issue by kacperc99** [Skulltrail192/One-Core-API-Binaries#155]
Like in title, when I attempt to install base as the second, I keep getting OCAB error, which results in a failed attempt of reverting installation and, right after, system restart. There is basically no information about this error, but I saw that someone has or had the same issue as I do.

**Comment by Skulltrail192** [comment]
Well, what package what you installed before Base?

**Comment by kacperc99** [comment]
Only AppCompat, followed what the instruction said.

**Comment by Skulltrail192** [comment]
Well, since not more information provided, this issue will be close. If the reporter back to provide information, him reopen the issue.

**Comment by kacperc99** [comment]
I'm sorry, I currently do not have an access to my Windows XP PC and haven't noticed your message, could you reopen the thread? The issue still persists since March.
