### ISSUE TITLE
Chrome 109 on Windows XP

### ISSUE THREAD

**Issue by Saswat2005** [Skulltrail192/One-Core-API-Binaries#156]
How can I install Chrome 109 on Windows XP? Please help!

**Comment by piotr25691** [comment]
Doesn't 103 and above not work on XP even with OneCore installed lol

**Comment by Saswat2005** [comment]
I am not asking you anything about it. I am asking to @Skulltrail192 about Chrome 109, I want to install it, SkullTrail192, please help me.

**Comment by piotr25691** [comment]
> I am not asking you anything about it. I am asking to @Skulltrail192 about Chrome 109, I want to install it, SkullTrail192, please help me.

If this repo doesn't specify that it works, it just doesn't. @Skulltrail192 would tell you the same thing.

**Comment by bw134polska** [comment]
Currently Chrome/Chromium 103-109 are unsupported on Windows NT 5.1/5.2 systems with OneCoreAPI.

**Comment by Pokemonfan1000** [comment]
Google Chrome 102 is the highest currently supported, although, downloads are going to be broken (at least in Chrome 100 they are). To get around this, you will need Firefox 54 (as both Firefox 52 and MyPal 68 show a black screen when launched).

**Comment by piotr25691** [comment]
> Google Chrome 102 is the highest currently supported, although, downloads are going to be broken (at least in Chrome 100 they are). To get around this, you will need Firefox 54 (as both Firefox 52 and MyPal 68 show a black screen when launched).

Yet the guy went "didnt ask you, i asked @Skulltrail192" 💀

**Comment by NEO-SPECTRUMAN** [comment]
does it works?
https://github.com/win32ss/supermium/releases

**Comment by Skulltrail192** [comment]
Hello friends. Well, what i tested, chrome works "partially" until version 102. After this version, only open and close later. I'm not answer  several questions because i'm focused on a new feature, a modern installer for Windows XP/2003.

**Comment by Skulltrail192** [comment]
> > I am not asking you anything about it. I am asking to @\Skulltrail192 about Chrome 109, I want to install it, SkullTrail192, please help me.
> 
> kinda funny how you expect skulltrail to personally get in this thread and answer your question, and specifically him, nobody else
> 
> well, shame im not skulltrail i guess ![image](https://user-images.githubusercontent.com/60317461/238699567-e8415252-c29b-4c48-8883-7d4ee25981c4.png)

Well, how you did it?

**Comment by Saswat2005** [comment]
> Skulltrail192, can you help me out how can I get Office 2013 on Windows XP with your new OneCore API?

**Comment by Saswat2005** [comment]
Skulltrail192, can you help me out how can I get Office 2013 on Windows XP with your new OneCore API?

**Comment by Saswat2005** [comment]
> 

Not only that, but Office 2013 or newer versions of Microsoft Office.

**Comment by Skulltrail192** [comment]
> > Skulltrail192, can you help me out how can I get Office 2013 on Windows XP with your new OneCore API?

Well, i trying it too...I don't why Office not install on Windows XP, but, seem related with OS version (Office use msi installer, what not have compatbility mode page on Windows XP/2003;

**Comment by Saswat2005** [comment]
Well well well, it said "Error - This version requires the newer versions of Windows" when I tried to do on Windows XP, or Windows Server 2003, as well as Windows Server 2003 R2!

**Comment by Saswat2005** [comment]
Office 2013, works on Windows Vista by win32 method 

![Screenshot_2023-07-03-17-53-48-167_org mozilla firefox-edit](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/122409692/d33083d0-4a29-4402-a26b-479c1e4af6de)
![Screenshot_2023-07-03-17-54-02-022_org mozilla firefox-edit](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/122409692/8eaa5e3b-d3a2-4ef9-b8a6-c80243ff2182)
![Screenshot_2023-07-03-17-54-14-162_org mozilla firefox-edit](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/122409692/027db701-0951-4a15-8dae-806a316906a2)
![Screenshot_2023-07-03-17-54-29-565_org mozilla firefox-edit](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/122409692/7fc0c249-9892-468f-9437-4d609cdb89ec)
![Screenshot_2023-07-03-17-54-43-380_org mozilla firefox-edit](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/122409692/d2726164-1cb4-42b9-b3b7-6a60827e2805)

**Comment by Saswat2005** [comment]
We know Office 2013 cannot be fit on Windows XP as well as Windows Vista. It can be fit for Windows 7 or newer, but it worked on Windows Vista Extended Kernel by win32. But what about Windows XP?

**Comment by p1glynlol** [comment]
I almost got some Chrome 117 based browser on Windows XP.
![Windows XP Professional-2023-07-04-21-14-09](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/87266022/70d2f870-5f92-4187-87a4-df55dc6c2558)
But for some weird reason, Supermium lasts longer than Chrome 103-109 (probably due to my configuration) and i was able to go to about page. Then it crashes later.

**Comment by Saswat2005** [comment]
I will try on Windows XP as what given from MSFN how to install Office 2013 on Windows Vista.

**Comment by p1glynlol** [comment]
> 

Well, someone was able to got Office 2013 to install, but it doesn't work: https://msfn.org/board/topic/184658-office-2013-on-windows-xp/#comment-1243049

**Comment by Saswat2005** [comment]
Then I will try a different method or Skulltrail192's method.

**Comment by RUvlad1** [comment]
> Well, how you did it?

This guide shows how to do it, though for some reason it only works on 32 bit
https://www.youtube.com/watch?v=Di1onSbU7hA

**Comment by Saswat2005** [comment]
This is only for Google Chrome, Chromium as well as Supermium only.

**Comment by Skulltrail192** [comment]
Same #136. #57, #109

**Comment by p1glynlol** [comment]
Now there's a workaround for running Chrome/Chromium 103-109 including Supermium 117 and 118 on #178

I highly recommend waiting for next Supermium update (so that it can work on XP 100% with/without OCAPI) or the next One Core API update.

**Comment by Skulltrail192** [comment]
Fixed at version 3.0.2. See main chrome thread: #178
