### ISSUE TITLE
Random IRQL_NOT_LESS_OR_EQUAL_BSOD while using Windows XP x64

### ISSUE THREAD

**Issue by Pokemonfan1000** [Skulltrail192/One-Core-API-Binaries#158]
I've noticed that when I use Windows XP 64-bit for a long period of time with the kernel installed, it causes an IRQL_NOT_LESS_OR_EQUAL BSOD. I'm not sure what is causing it as no drivers (.sys) files are shown on the BSOD. I know the Qualcom Atheros AR5B125 2013 driver, which I have installed, is known to cause this BSOD, but 1. It has Code 10 in device manager and 2. It doesn't show athw.sys in the BSOD. Any help on this greatly appreciated!

**Comment by Pokemonfan1000** [comment]
I took out the Atheros WiFi card and put the Intel card in, which of course works as expected. It went fine, but after a while, the screen went black. No IRQL BSOD was visible, so idk what this was about.

**Comment by Skulltrail192** [comment]
BSOD with Wifi usb adapter is a known issue.

**Comment by Pokemonfan1000** [comment]
Hopefully I don't have to wait long for this release.

**Comment by Pokemonfan1000** [comment]
I installed version 3.0.0 and have had the laptop on for almost 30 minutes (if not 30 minutes exactly), and the IRQL_NOT_LESS_OR_EQUAL BSOD has not appeared yet. Perhaps version 3.0.0 fixed it (even though it says on the releases page for 3.0.0 that it's an issue)

**Comment by Pokemonfan1000** [comment]
I finally encountered the IRQL_NOT_LESS_OR_EQUAL BSOD, meaning it is not fixed in version 3.0.0. I will just wait for the new version that does actually fix it.

**Comment by Skulltrail192** [comment]
> I finally encountered the IRQL_NOT_LESS_OR_EQUAL BSOD, meaning it is not fixed in version 3.0.0. I will just wait for the new version that does actually fix it.

Is occoured with Wifi card or after some time?

**Comment by Pokemonfan1000** [comment]
It occurred after some time. It is not WiFi card related. There is a certain version of the Qualcom Atheros AR5B125 WiFi card driver that throws an IRQ BSOD (the 2013 driver itself is botched), but this happens even on vanilla XP and is not the fault of this Extended Kernel. Using an older version of AR5B125 drivers, such as 2012 or earlier will get rid of the BSOD. There is still the issue of Atheros cards throwing Code 10 after installing the kernel, however.

**Comment by Skulltrail192** [comment]
Fixed on version 3.0.1.
