### ISSUE TITLE
AVG breaks OCAPI

### ISSUE THREAD

**Issue by everythingeeb** [Skulltrail192/One-Core-API-Binaries#160]
Yesterday I tried installing One Core API on my ThinkCentre running Windows XP. Immediately after all programs would give me the same error and nothing except for Backup and System Restore would launch. After disabling AVG I can confirm that it breaks OCAPI when re-enabled and in order to use it, you have to get rid of AVG. This likely applies to Avast as well since they're the same thing.

**Comment by Skulltrail192** [comment]
This is latest version of AVG?

**Comment by Skulltrail192** [comment]
Please, remake your tests, because on my test it's works fine.
