### ISSUE TITLE
after installing base on win2003 r2 x64 datacener edition  No Boot

### ISSUE THREAD

**Issue by icinemagr** [Skulltrail192/One-Core-API-Binaries#162]
No boot.

**Comment by icinemagr** [comment]
fucking BS

**Comment by Skulltrail192** [comment]
Hello!
Please, tell more information about this issue. BSOD occours? WIndows only restart? Is Black Screen? 
Tell me too about:
- Windows Config
- Hardware Config (is VM or real hardware)
- Packages installed;

**Comment by Skulltrail192** [comment]
Since the user who reported the issue did not respond and in my tests the issue did not occur, this issue will be closed
