### ISSUE TITLE
Process hacker unable to terminate any process

### ISSUE THREAD

**Issue by vlOd2** [Skulltrail192/One-Core-API-Binaries#164]
When using OneCore API on Windows XP x86 SP3, Process Hacker is unable to terminate any processes, even when toggling off the usage of the kernel mode driver, it still is unable to terminate any process

**Comment by Smu1zel** [comment]
Can confirm, this issue has also been reported on the source code page of One-Core-API.

**Comment by KOLANICH** [comment]
https://github.com/winsiderss/systeminformer/issues/1642 is related

**Comment by Skulltrail192** [comment]
What is version of Process Hacker used?

**Comment by KOLANICH** [comment]
2.38 (the last one supporting XP) and 2.39 (with drivers copied from 2.38) - all the same.

**Comment by Skulltrail192** [comment]
I will try fix that on next release.

**Comment by Skulltrail192** [comment]
Fix will be avaliable on next release and will be avaliable on One-Core-API-Binaries-Canary

**Comment by Skulltrail192** [comment]
Fixed at version 3.0.2.
