### ISSUE TITLE
How to uninstall one core API??

### ISSUE THREAD

**Issue by Fjhhd6** [Skulltrail192/One-Core-API-Binaries#165]
by installing this program or dll(whatever), i got some issues with my pc, not being able to run some programs baffled me. due to my stupidity, I could have done something wrong and everything went wrong, but the operating system is stable, but there was a I want to go back to the normal version of OS, but I don't know how, does anyone know how to do this?

**Comment by RUvlad1** [comment]
Uninstall all the OCA packages from the control panel
I'm not sure if that fully works though, i'd just recommend reinstalling XP

**Comment by NEO-SPECTRUMAN** [comment]
it's recommended try OCAPI first on the copy of you OS
i still don't use OCAPI on main system
because it still very unstable
(but i use OCAPI libs to "patch" new software : )

**Comment by Skulltrail192** [comment]
> by installing this program or dll(whatever), i got some issues with my pc, not being able to run some programs baffled me. due to my stupidity, I could have done something wrong and everything went wrong, but the operating system is stable, but there was a I want to go back to the normal version of OS, but I don't know how, does anyone know how to do this?

By Windows Add/Remove programs and updates.
