### ISSUE TITLE
3.0.0 - after the update, windows does not start

### ISSUE THREAD

**Issue by Stepman123** [Skulltrail192/One-Core-API-Binaries#168]
I installed over version 2.10, after that booting is only possible in safe mode.
Then I removed OCAPI and now any download doesn't work.

2.10 was installed in this sequence: App Compat -> Base -> Driver Update -> API-SET -> D3d -> Additional Dlls
3.0.0 was installed in this sequence: x86: Branding -> Modern Setup -> Base-> API-SET -> D3d -> Driver Update -> App Compat-> Additional Dlls;

After reinstalling windows, what installation sequence should I choose? 
Hardware: Pentium-4 sse2 x86

**Comment by Skulltrail192** [comment]
BSOD or black screen? What version of Pentium 4? Is Standard ACPI or ACPI Uniprocessor/Multiprocessor?

**Comment by Stepman123** [comment]
At the Windows XP boot stage, the progressbar froze and nothing happens.
Pentium-4 single-core, 2.4 GHz, x32-bit, SSE2.
ACPI Uniprocessor. HT - Disabled.

**Comment by NS-Clone** [comment]
successfully updated from 2.10.0 to 3.0.0 in virtualbox

**Comment by Stepman123** [comment]
> successfully updated from 2.10.0 to 3.0.0 in virtualbox
What sequence did you use?

**Comment by Skulltrail192** [comment]
Send please screenshot of device manager with "computer" section expansed.

**Comment by NS-Clone** [comment]
> > successfully updated from 2.10.0 to 3.0.0 in virtualbox
> 
> What sequence did you use?

>Modern Setup:
>
>    x86: Branding -> Modern Setup -> Base-> API-SET -> D3d -> Driver Update -> App Compat-> Additional Dlls;

**Comment by NS-Clone** [comment]
> Remember:
> One-Core-API Modern Setup is a package designed to prepare 
so there is NO main setup mode?

**Comment by Skulltrail192** [comment]
> > Remember:
> > One-Core-API Modern Setup is a package designed to prepare
> 
> so there is NOТ new main setup mode? o_O

Is for prepare Windows to be installed on newer computers, using iso from Vista, Win7, Win8-8.1 and Win10. So, prepare to reseal, out-of-box to reinstall.

**Comment by Stepman123** [comment]
> Send please screenshot of device manager with "computer" section expansed.
I will answer in another topic. This can be closed, since the problem is not repeated.

**Comment by Skulltrail192** [comment]
Since the reporter told what the problem is not repeated, this topic will close.
