### ISSUE TITLE
After installing One-Core-API some 32-bit applications do not work in XP x64

### ISSUE THREAD

**Issue by sal-ammoniac** [Skulltrail192/One-Core-API-Binaries#169]
[issues.zip](https://github.com/Skulltrail192/One-Core-API-Binaries/files/12266707/issues.zip)
Because of the continously failing uploading of images,I have to use zip.
Sorry for that.

Version:3.0.0（Older version also have this issue）
Base first installation

**Comment by sal-ammoniac** [comment]
As this problem was recently found,I am sorry for not having preparing English examples

**Comment by Skulltrail192** [comment]
Tell whats packages installed. And what language is the system and the PC/VM config

**Comment by sal-ammoniac** [comment]
> Tell whats packages installed. And what language is the system and the PC/VM config

VM Config：RAM 8GB CPU 4 Cores
Installed on VMware Workstation 17，Host has a i5-7500 CPU.
All packages installed,with base first install order.
XP x64 had Chinese MUI and hotfixes installed.

**Comment by sal-ammoniac** [comment]
In another same config,while no patches or MUI installed,after installing One-Core-API,net framework 3.5 installation failed.
[1.zip](https://github.com/Skulltrail192/One-Core-API-Binaries/files/12268521/1.zip)

**Comment by Skulltrail192** [comment]
Are you intalled MUI before or after One-core-API?

**Comment by sal-ammoniac** [comment]
> Are you intalled MUI before or after One-core-API?

Before

**Comment by Skulltrail192** [comment]
Teste again. Maybe MUI not fully supported.
