### ISSUE TITLE
Readd vtdll.dll to fix interface pack compatibility

### ISSUE THREAD

**Issue by r3muxd** [Skulltrail192/One-Core-API-Binaries#17]
Currently, if you try to install the interface packs on any windows version with the latest one-core-api, you'll get an error about vtdll.dll. If you copy it from https://github.com/Skulltrail192/One-Core-API-Binaries/blob/master/Legacy/Repository/x86/System32/Base/vtdll/vtdll.dll to system32 (for x86) or to syswow64 (for x64), and if you're 64-bit, copy https://github.com/Skulltrail192/One-Core-API-Binaries/blob/master/Legacy/Repository/x64/System32/Base/vtdll/vtdll.dll to system32, and run "regsvr32 vtdll.dll", explorer will start.

Can vtdll.dll be added back into One-core-api-app-base to solve this issue?

**Comment by SSJ9899TDylan** [comment]
This is why I’m waiting until April next year before I install these binaries.
I’m saying that because the Embedded Posready Updates have better results with these binaries than just fully updating Windows XP.

**Comment by r3muxd** [comment]
This issue is only a problem if you install the interface packs, and by the looks of it, only 5219+. 5219+ interface packs have a number of issues, are unsupported, and the lack of vtdll is the least of their problems.

**Comment by SSJ9899TDylan** [comment]
Which interface pack did you install?

**Comment by r3muxd** [comment]
5270. Explorer errors with "This application failed to start because vtdll.dll was not found. Re-installing this application may fix this problem." After copying vtdll.dll, explorer starts with a broken start menu and crashy explorer windows, but at least it starts.

**Comment by SSJ9899TDylan** [comment]
Skulltrail192, we have a problem

**Comment by Skulltrail192** [comment]
Well, i recommend for now copy and rename ntext.dll to vtdll.dll, why the right way is update references on interface packs.
