### ISSUE TITLE
In 3.0.0 Wi-Fi no longer works

### ISSUE THREAD

**Issue by Stepman123** [Skulltrail192/One-Core-API-Binaries#170]
Version 2.10 worked fine with USB Wi-Fi (VID_148F&PID_7601).  The connection worked only with windows, and did not work through the RaConfig utility.  (endless attempts to get ip)
 Version 3.0.0 does not work with windows either.  No overview of wi-fi.

**Comment by Skulltrail192** [comment]
Send:
- Windows Config, Edition, updates, etc;
- PC config
- One-Core-API packages installed;

**Comment by Stepman123** [comment]
Report config: [https://files.catbox.moe/d415jh.mp4](url)
Mirror: [https://www.upload.ee/files/15556627/aida64_XgkWKAj9ie.mp4.html](url)
The problem appears after installing the Aditional Dlls 3.0.0. I think that with my hardwar this patch does not give anything useful. 

Therefore, I am now using this sequence:
Base-> API -SET -> Branding -> D3D -> -> -> App Compat-> Additional Dlls;
Although the video card does not support the DX10, but it seems that it does not cause problems.

Now Windows Wi-Fi is working it's not bad. The utility works poorly, as before.

**Comment by Stepman123** [comment]
Supplement.
I did a PCMark05 test before and after installing "Driver Update". You can see that after installation "Web Page Rendering" is missing:
[img]http://ipic.su/img/img7/fs/bug2.1691860337.png[/img]
It turned out that every time IE8 is launched, an error window pops up. No matter what I do this window always pops up at startup:
[img]http://ipic.su/img/img7/fs/bug.1691860827.png[/img]

**Comment by Pokemonfan1000** [comment]
Just a note regarding WiFi. Idk about Realtek or Broadcomm WiFi cards (Realtek USB WiFi works so long as you don't have it plugged in when booting up the system, but idk about the internal PCI-E card), but Atheros (AR5B125 and so on) do not work, while Intel Centrino WiFi (Centrino Ultimate6300, found in Latitude E6530's, and Centrino Wireless-N 105) works flawlessly. Just thought I'd point this out for anybody who may have one of the problematic WiFi cards (it should also be noted that these problematic cards work fine prior to the Kernel being installed, but break after installing it).

**Comment by OptiJuegos** [comment]
It happend to me too with a  TP-LINK

**Comment by Skulltrail192** [comment]
Same #174
