### ISSUE TITLE
The time is complety off with the time zone

### ISSUE THREAD

**Issue by ChrisSpartan** [Skulltrail192/One-Core-API-Binaries#172]
after the installation the time is just complety off to the time zone, it even changes sometimes and i have no idea why

**Comment by Stepman123** [comment]
https://github.com/Skulltrail192/One-Core-API-Binaries/issues/104
https://github.com/Skulltrail192/One-Core-API-Binaries/issues/111

It doesn't seem to work for anyone. My solution is this: 
1 disable Internet Time
2 Set the time zone and time, press only "ok" and the correction must be taken into account.

**Comment by ChrisSpartan** [comment]
i'm gonna try a english copy of windows xp since the one with time problems is a spanish copy

**Comment by ChrisSpartan** [comment]
welp, even on a english copy of xp the problems are still there and no disabling internet time didn't do anything

**Comment by ChrisSpartan** [comment]
ok now i know i had to install one core api in order like this: App Compat -> Base -> Driver Update -> API-SET -> D3d -> Additional Dlls just to get something like chromium to work and so there's no time problems even on a spanish copy of xp

**Comment by Stepman123** [comment]
>>App Compat -> Base -> Driver Update -> API-SET -> D3d -> Additional Dlls
 version 2.10?

**Comment by ChrisSpartan** [comment]
> > > App Compat -> Base -> Driver Update -> API-SET -> D3d -> Additional Dlls
> 
> version 2.10?

No, the latest version which is the 3.0.0

**Comment by Stepman123** [comment]
> No, the latest version which is the 3.0.0

D3d 3.0.0 - it requires installing branding. Refuses to install without it.

**Comment by ChrisSpartan** [comment]
> > No, the latest version which is the 3.0.0
> 
> D3d 3.0.0 - it requires installing branding. Refuses to install without it.

sorry for not noticing your comment but then just install branding and then D3d

**Comment by jonm58** [comment]
uh, disable internet time
and timezone to United States, then set it to your timezone
Maybe it will work?

**Comment by Stepman123** [comment]
> then just install branding and then D3d

Yes, I have tried reinstalling using this sequence: App Compat -> Base -> Driver Update -> API-SET -> Branding -> D3d -> Additional Dlls
But the problem persisted. However, it doesn't matter. It's like a puzzle - how to set the correct time. Not too difficult.

**Comment by Skulltrail192** [comment]
This problem is almost already fixed. The fix will be on end of month.

**Comment by Skulltrail192** [comment]
Already fixed, avaliable on next release.

**Comment by ChrisSpartan** [comment]
> Already fixed, avaliable on next release.

ok

**Comment by Skulltrail192** [comment]
Same #111

**Comment by Skulltrail192** [comment]
Fixed on version 3.0.1
