### ISSUE TITLE
Cannot install modern-setup virtualbox on XP sp3 (Virtualbox)

### ISSUE THREAD

**Issue by TK50P** [Skulltrail192/One-Core-API-Binaries#179]
I can't install modern-setup binary and it says:
![acpi](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/127497974/4a1107aa-28d3-4c62-812a-5acaea1be911)
even uninstall guest additions and enabled I/O APIC
What's wrong?

**Comment by jonm58** [comment]
> 我无法安装现代安装二进制文件，它说： ![交流接口](https://user-images.githubusercontent.com/127497974/269248869-4a1107aa-28d3-4c62-812a-5acaea1be911.png) 甚至卸载来宾添加并启用 I/O APIC 怎么了？
Did you reboot during installation?

**Comment by Skulltrail192** [comment]
You must update HAL before install Modern Setup Package or reinstall windows with I/O APIC option enabled before installation.

**Comment by zoli456** [comment]
Something wrong with it. I did everything correctly but still doesnt let me install it. I installed the Standard and it let me install but after that the system doesnt boot anymore.

**Comment by zoli456** [comment]
I fixed it: 
1. Installed the "Standard Pc" driver
2. Started the installler
3.  Reinstalled the "Advanced Configuration and Power Interface (ACPI) driver"
4. Installed and restarted and Windows boot correctly

**Comment by Skulltrail192** [comment]
So, the issue was solve. Now closing.
