### ISSUE TITLE
Problems with Windows Server 2003 R2 Standard Edition.

### ISSUE THREAD

**Issue by SSJ9899TDylan** [Skulltrail192/One-Core-API-Binaries#18]
I had multiple problems with the binaries:
1. Windows File Protection said that the files in the Base Installer were unrecognized.
2. While I was able to successfully install the Kernel Installer, after restarting, I actually can't open Windows 
Explorer due to DEP. On top of that, I can't even look for files to run within Task Manager.
That's my latest report from testing the binaries.
This clean install was even ready for the binaries.

**Comment by Skulltrail192** [comment]
> Windows File Protection said that the files in the Base Installer were unrecognized. 

This is normal, because installer replace system files. Maybe can be disabled on .inf, but, it not broken the installation.

**Comment by ManoaNosea** [comment]
yhe, use nlite to disable SFC, SFC is just a crap
