### ISSUE TITLE
GTA V not working on Windows XP x64

### ISSUE THREAD

**Issue by FlorianisonGitHub** [Skulltrail192/One-Core-API-Binaries#183]
![Windows XP Professional x64 Edition (One-Core API)-2023-10-01-16-19-31](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/111876654/200489e2-c57a-44bb-9aa3-49b30f8182e1)

Hello, I got One-Core API installed on Windows XP, but however, when I run GTA V, it doesn't work for now as it reads:

ERR_GFX_D3D_SWAPCHAIN_ALLOC_2: No DirectX 10 or 11 adapter or runtime found. Please install latest DirectX runtime or install a compatible DirectX 10 or 11 video card.

I checked DxDiag, and it reports it DirectX 11, but it's not working for now.

Any ideas would be appreciated?

I'm using VMWare SVGA II also on Windows XP x64.

**Comment by jonm58** [comment]
Wine:https://appdb.winehq.org/objectManager.php?sClass=application&iId=16807

**Comment by Skulltrail192** [comment]
I think Directx 11 game won't run on VM. You must try on Real PC.

**Comment by shark-vader** [comment]
> I think Directx 11 game won't run on VM. You must try on Real PC.

It has been done on vmware before, there are many videos on youtube showing it. I think the vmware windows xp graphics drivers are the issue, they lack certain functions needed for gta 5 to run. All the videos showing it running are on a Windows 7 vm or above.

**Comment by Skulltrail192** [comment]
> > I think Directx 11 game won't run on VM. You must try on Real PC.
> 
> It has been done on vmware before, there are many videos on youtube showing it. I think the vmware windows xp graphics drivers are the issue, they lack certain functions needed for gta 5 to run. All the videos showing it running are on a Windows 7 vm or above.

The Vmware Video driver for Windows 7 is 3d driver, with diretx10 capability. The Video driver for XP is a legacy, only Directx 9 and OpenGL 1 or 2 support. So, how i said, test on real machine.

**Comment by FlorianisonGitHub** [comment]
I can't afford to get a new machine to test GTA V on Windows XP x64 with One-Core API right now. And also, GTA V is not known to work outside of real hardware for GTA V on Windows XP x64 with One-Core API.

Let us know if anyone managed to get GTA V working on Windows XP x64 with One-Core API.

**Comment by Skulltrail192** [comment]
Vmware Driver not support required version of OpenGL. I recommend test it in **your** current machine. Doesn't need buy a new. Install Windows Xp and try run GTA V with or without OCA.

**Comment by Skulltrail192** [comment]
You can try in virtual machine with mesa driver for Windows. However, if run, i will run very slow.

**Comment by Skulltrail192** [comment]
The reporter of issue need test on Real hardware. Issue closed.

**Comment by EzioisAwesome56** [comment]
Couldn't decide if this should be in a new issue or not, so I'll just leave this here

Tested using Windows XP x64 w/ all post sp2 updates applies, using [OneCore API 4.0.0 preRTM hotfix 20241109](https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/tag/4.0.0-pre-rtm-hotfix-20241109-experimental) on real hardware. Hardware is an Intel Pentium E2220 (conroe) with 4gb of ram, and an ATI Firepro V4800 for graphics.

Game starts up fine, no directx errors. (you may need to install the june 2010 Redistributable however). The loading screen displays fine but once you actually get into the game, the majority of the game fails to render, besides HUD minimap and any system messages in the top left. Unsure if OCAPI is at fault or my graphics card, as it crashes shortly after, with the error report pointing to a dll from my video driver

but, the game does technically start, so that's a start atleast
![loading](https://github.com/user-attachments/assets/a2baa388-5914-4cc5-bd2c-8f3613bb936c)
![ingame](https://github.com/user-attachments/assets/57bc1551-d5d6-43dc-b45a-3c5622c7b91a)

**Comment by sambow23** [comment]
> Couldn't decide if this should be in a new issue or not, so I'll just leave this here
> 
> Tested using Windows XP x64 w/ all post sp2 updates applies, using [OneCore API 4.0.0 preRTM hotfix 20241109](https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/tag/4.0.0-pre-rtm-hotfix-20241109-experimental) on real hardware. Hardware is an Intel Pentium E2220 (conroe) with 4gb of ram, and an ATI Firepro V4800 for graphics.
> 
> Game starts up fine, no directx errors. (you may need to install the june 2010 Redistributable however). The loading screen displays fine but once you actually get into the game, the majority of the game fails to render, besides HUD minimap and any system messages in the top left. Unsure if OCAPI is at fault or my graphics card, as it crashes shortly after, with the error report pointing to a dll from my video driver
> 
> but, the game does technically start, so that's a start atleast ![loading](https://private-user-images.githubusercontent.com/21185626/385080424-a2baa388-5914-4cc5-bd2c-8f3613bb936c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNzEwNTYsIm5iZiI6MTczMTM3MDc1NiwicGF0aCI6Ii8yMTE4NTYyNi8zODUwODA0MjQtYTJiYWEzODgtNTkxNC00Y2M1LWJkMmMtOGYzNjEzYmI5MzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDAwMTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyYWU0OTEyNWQ5NDU3M2U1YzI2MjNmOTE2ODVmZDRkNWZiZjYxYmRlNWE0NTVmZmVhYmIzNTQ3YzQ2NDgzNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x48ZWfTpLanNRHxcJ-etfpHmGrAEj3qyYY0wODuKSns) ![ingame](https://private-user-images.githubusercontent.com/21185626/385080433-57bc1551-d5d6-43dc-b45a-3c5622c7b91a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNzEwNTYsIm5iZiI6MTczMTM3MDc1NiwicGF0aCI6Ii8yMTE4NTYyNi8zODUwODA0MzMtNTdiYzE1NTEtZDVkNi00M2RjLWI0NWEtM2M1NjIyYzdiOTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDAwMTkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5MmZiNmEyMzg4ZmY1YjYxMjU5OTBmZjg3YTQ3NGQwYmRhNDhmNWQzZTQ2MmFkMTBlZTMyMTZjYzc5Yzk3NTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3t0Z8wMLhg2A0s1Pme-gEt96QOL44Ceen6_q3nXxtsI)

You're most likely running into issues with WineD3D and insufficient support for GL 4.5 extensions. Try it on a more modern GPU

**Comment by NS-Clone** [comment]
> Couldn't decide if this should be in a new issue or not, so I'll just leave this here
> 
> Tested using Windows XP x64 w/ all post sp2 updates applies, using [OneCore API 4.0.0 preRTM hotfix 20241109](https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/tag/4.0.0-pre-rtm-hotfix-20241109-experimental) on real hardware. Hardware is an Intel Pentium E2220 (conroe) with 4gb of ram, and an ATI Firepro V4800 for graphics.
> 
> Game starts up fine, no directx errors. (you may need to install the june 2010 Redistributable however). The loading screen displays fine but once you actually get into the game, the majority of the game fails to render, besides HUD minimap and any system messages in the top left. Unsure if OCAPI is at fault or my graphics card, as it crashes shortly after, with the error report pointing to a dll from my video driver
> 
> but, the game does technically start, so that's a start atleast ![loading](https://private-user-images.githubusercontent.com/21185626/385080424-a2baa388-5914-4cc5-bd2c-8f3613bb936c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODI0NzAsIm5iZiI6MTczMTM4MjE3MCwicGF0aCI6Ii8yMTE4NTYyNi8zODUwODA0MjQtYTJiYWEzODgtNTkxNC00Y2M1LWJkMmMtOGYzNjEzYmI5MzZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDAzMjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNGI4NDdmN2QwYzU1Y2UyYmQ5MzA3OTBjMzMzZGMyN2E4ZTU4NjgxNzk3ZWRjZWQwYTc3MjBjNDZjZmM1MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iksFyKhSwEVksB8ZP1XyuzPo3IC2MXe0v2nrxF0EfEY) ![ingame](https://private-user-images.githubusercontent.com/21185626/385080433-57bc1551-d5d6-43dc-b45a-3c5622c7b91a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODI0NzAsIm5iZiI6MTczMTM4MjE3MCwicGF0aCI6Ii8yMTE4NTYyNi8zODUwODA0MzMtNTdiYzE1NTEtZDVkNi00M2RjLWI0NWEtM2M1NjIyYzdiOTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDAzMjkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NWI2OGM3NGUzN2VjODMxODk5MGNhNmVmYjEwODk4MDk1Y2M0YzA0MzQxNjUyNTkyZjJlYjFmYzQ5YTA2MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UWkjtOuHMzJrqofwnpLqQkdJJZ6f1xF2WuBE4hwxENA)

is it minimal graphics settings?

**Comment by EzioisAwesome56** [comment]
> You're most likely running into issues with WineD3D and insufficient support for GL 4.5 extensions. Try it on a more modern GPU

yeah i ended up throwing a gtx 660 at it and it was fine, so probably the card's fault

**Comment by Stepman123** [comment]
> > You're most likely running into issues with WineD3D and insufficient support for GL 4.5 extensions. Try it on a more modern GPU
> 
> yeah i ended up throwing a gtx 660 at it and it was fine, so probably the card's fault

GeForce GTX 660
 Feature Support:
GPU Boost, PhysX, TXAA, NVIDIA G-SYNC-readyImportant Technologies
3D Vision, CUDA, Adaptive VSync, FXAA, 3D Vision Surround, SLIOther Supported Technologies 2
4.3OpenGL
12 APIMicrosoft DirectX
PCI Express 3.0 Bus Support 1
YesCertified for Windows 7
Yes3D Vision Ready
