### ISSUE TITLE
Certain .exe installers don't work

### ISSUE THREAD

**Issue by RUvlad1** [Skulltrail192/One-Core-API-Binaries#184]
Installers that I've noticed are affected are:
Telegram 1.8.15
Double Commander 1.0.11
PeaZip 9.4.0

The Telegram 1.8.15 installer is supposed to work on Windows XP without issues, even without OCA, the PeaZip 9.4.0 installer used to work on OCA as well and the Double Commander 1.0.11 .msi installer worked perfectly fine

![explorer_t6cM4lk59t](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/60317461/d6eda05f-981b-4d65-9776-21008b7d7682)

I'm running Windows XP 64 bit SP2 on VMware

**Comment by Skulltrail192** [comment]
Telegram: installer and app working
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/142ae3aa-0622-4ebd-ab80-0a92f839e134)
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/500f3c04-e41f-40f6-9eb2-08dbfff82992)
Double Commander: installer and appworking
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/25ea9890-bb0e-4b3d-b74f-5bed2139275c)
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/f4c03ead-c6c7-42d7-9d5d-34c034fcaab9)
PeaZip: installer and app working:
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/ab5c0b04-4c2b-496a-8424-161530202c50)
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/eb750642-a008-4ae2-a7b4-978aef89ac4c)

**Comment by Skulltrail192** [comment]
Telegram: installer and app working
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/142ae3aa-0622-4ebd-ab80-0a92f839e134)
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/500f3c04-e41f-40f6-9eb2-08dbfff82992)
Double Commander: installer and appworking
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/25ea9890-bb0e-4b3d-b74f-5bed2139275c)
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/f4c03ead-c6c7-42d7-9d5d-34c034fcaab9)
PeaZip: installer and app working:
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/ab5c0b04-4c2b-496a-8424-161530202c50)
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/eb750642-a008-4ae2-a7b4-978aef89ac4c)

**Comment by Skulltrail192** [comment]
Telegram
