### ISSUE TITLE
Windows XP 64Bit noMeiryoUI3.2.1.1 problem

### ISSUE THREAD

**Issue by jonm58** [Skulltrail192/One-Core-API-Binaries#186]
**One-Core-API version**: 3.0.2
**What works**:
- Windows XP 32Bit working
- Windows XP 32Bit OCAPI working
![Windows XP x64 Edition-2023-10-12-16-36-19](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/73036321/3998942f-5e4c-4dc0-a56e-3364fd2fc260)

**Comment by Skulltrail192** [comment]
Is 32 bits or 64 bits application?

**Comment by jonm58** [comment]
> Is 32 bits or 64 bits application?

32 bit application

**Comment by Skulltrail192** [comment]
Working...Litle ugly, but working.
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/44b00a64-ace6-4d66-88c9-b83e4a347056)
