### ISSUE TITLE
Use only one .dll - possible?

### ISSUE THREAD

**Issue by Gelip** [Skulltrail192/One-Core-API-Binaries#190]
Can only be replaced with one or a few .dll files or need use all? I want to test an application that requires an InitializeCriticalSectionEx function in the kernel32.dll file on WinXP SP2 64-bit
I tried copied the kernelbase.dll or XP64SP2\kernel32.dll file to C:\WINDOWS\system32 but it doesn't work.

**Comment by jonm58** [comment]
Copy kernel32.dll and kernelbase.dll for your application

**Comment by Gelip** [comment]
Thank you very much - I will know for the future.
Meanwhile, I just installed only **one-core-api-base.exe** and works :-)

**Comment by Skulltrail192** [comment]
kernel32 and kernelbase are inter-dependents. Copy both
