### ISSUE TITLE
Windows XP does not allow me to install OneCore A.P.I with an update.exe error!

### ISSUE THREAD

**Issue by Saswat2005** [Skulltrail192/One-Core-API-Binaries#191]
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/122409692/e41d3b91-33e8-4784-b977-5ff739d6d542)

Can you explain why this happened by this stupid error? Please explain me, how to install OneCore A.P.I without update.exe error! Please resolve the problems of update.exe error on OneCore A.P.I binaries version 3.0.2!

**Comment by jonm58** [comment]
your Windows XP is 32 bit...
not 64 bit

**Comment by Saswat2005** [comment]
Sorry.

**Comment by Skulltrail192** [comment]
This issue will be closed.
