### ISSUE TITLE
Installation order x64 - need to install the base package twice?

### ISSUE THREAD

**Issue by Gelip** [Skulltrail192/One-Core-API-Binaries#193]
- **Modern Setup:**

  - **x86:** Branding -> Modern Setup -> Base-> API-SET -> D3d -> Driver Update -> App Compat-> Additional Dlls;
  - **x64:** _Base_ -> Branding -> Modern Setup -> _Base_-> API-SET -> D3d -> Driver Update -> App Compat-> Additional Dlls;

**Comment by jonm58** [comment]
lmao

**Comment by Saswat2005** [comment]
No, in 64 bit, only x64, not x86 but in 32 bit, only x86.

**Comment by Gelip** [comment]
> No, in 64 bit, only x64, not x86 but in 32 bit, only x86.
Do you have me an idiot ???

The point is that there is a **Base** twice with x64 - Base > Branding > Modern Setup and one more time Base ???

**Comment by jonm58** [comment]
> > No, in 64 bit, only x64, not x86 but in 32 bit, only x86.
> 
> Do you have me an idiot ???
> 
> The point is that there is a **Base** twice with x64 - Base > Branding > Modern Setup and one more time Base ???

I made a pull request,wait

**Comment by Skulltrail192** [comment]
See installation order instructions.
