### ISSUE TITLE
The instructions for the order of packet installation is not understood - please correct

### ISSUE THREAD

**Issue by Gelip** [Skulltrail192/One-Core-API-Binaries#195]
I read the installation instructions carefully but I don't understand. How is the Modern Setup difference from Modern Setup Only? - completely different order of the installation.

Does the order really matter?

This is badly written or I don't understand something.

**Comment by Skulltrail192** [comment]
See https://github.com/Skulltrail192/One-Core-API-Binaries#readme at section **Installation order of packages:**.
