### ISSUE TITLE
sysprep.exe 6.0.4066.0 from OCA in WinXP SP2 64-bit

### ISSUE THREAD

**Issue by Gelip** [Skulltrail192/One-Core-API-Binaries#196]
Will sysprep.exe 6.0.4066.0 from OCA 3.0.2 seal correctly WinXP SP2 64-bit without installing any a OCA component?
I would like to use this version of sysprep in my guide:
[https://msfn.org/board/topic/185865-sysprep-winxp-sp2-64-bit-on-pure-uefi-v3/](url)

**Comment by Skulltrail192** [comment]
No. Sysprep will add this path to C:\Windows\System32\oobe\setup.exe to registry, at key: HKEY_LOCAL_MACHINE\System\Setup\CmdLine, what will run setup.exe on next startup of Windows. 
So, if you doesn't have the oobe from Longhorn 4074, what i copy with OCA Modern Setup, it will not do anything.

**Comment by Gelip** [comment]
OK, thx for info.
BTW, sysprep.exe from WinXP SP2 64-bit works OK :-)
[https://www.betaarchive.com/forum/viewtopic.php?t=45015](url)

**Comment by Skulltrail192** [comment]
Fine! Well, since the question is solved, this issue will be closed.
