### ISSUE TITLE
sysdm.cpl - can I use back the original WinXP SP2 64-bit version?

### ISSUE THREAD

**Issue by Gelip** [Skulltrail192/One-Core-API-Binaries#197]
I tested the sysprep with OCA 3.0.2 in WinXP SP2 64-bit and works well but I don't like the system properties window in which the click to Activate and Change product key does not work anyway.

Can I replace the sysdm.cpl file with the original WinXP SP2 64-bit after installing one-core-api-modern-setup.exe?

**Comment by jonm58** [comment]
> 我在 WinXP SP2 64 位中使用 OCA 3.0.2 测试了 sysprep，运行良好，但我不喜欢系统属性窗口，在该窗口中单击激活和更改产品密钥无论如何都不起作用。 安装 one-core-api-modern-setup.exe 后可以用原来的 WinXP SP2 64 位替换 sysdm.cpl 文件吗？

YES

**Comment by Gelip** [comment]
OK, thx.

**Comment by sal-ammoniac** [comment]
unlicensed? did you use volume version though?

**Comment by Skulltrail192** [comment]
I used Sysdm.cpl from Vista 5231, only for view boot options from BCD. Just ignore Activation information on this. Don't install Modern Setup if you don't want capture a Windows Image. Uninstall Modern Setup, get sysdm.cpl from cd or from dllcache. This issue will be closed.
