### ISSUE TITLE
Modified Telegram 4.8.3 for Windows XP doesn't work

### ISSUE THREAD

**Issue by Snaky1a** [Skulltrail192/One-Core-API-Binaries#199]
Modified Telegram 4.8.3 doesn't work on Windows XP Professional Service Pack 3 x86 with One-Core-API (no errors shown), but works without it

![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/131266173/835d4fa0-1eaa-4b5c-a2f3-3387bd4929f9)

UPDATE: Got this error
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/131266173/497d778e-9766-4b42-a214-6e2e8d715ccb)

Download link: https://pixeldrain.com/u/jmgH6fk6

**Comment by TowerProductions** [comment]
OneCore API breaks many things, it breaks RemoteDesktop, and makes the system VERY unstable. I hope that they will fix this issuse and the RDP server issuse too.

**Comment by Skulltrail192** [comment]
No, don't make the system very stable.. I use in real computer. If you have a issue, create and i will review!

**Comment by Snaky1a** [comment]
Since **One-Core-API version 3.0.3** modified telegram **works** on Windows XP x64 and Windows XP x86 (maybe, need test)

I think it works because Telegram uses native dwrite.dll from Windows Vista.

<img src="https://github.com/Skulltrail192/One-Core-API-Binaries/assets/131266173/413a6558-752c-41bb-a402-65a93e496060">
