### ISSUE TITLE
XP compatible programs which don't work anymore

### ISSUE THREAD

**Issue by avaxx** [Skulltrail192/One-Core-API-Binaries#2]
A strange problem occurs when I use newer XP compatible Firefox versions. They work but the window doesn't get refreshed after an input (for example after typing a text in the address bar or trying to open a new tab) before I click on the menu or somewhere else. I didn't noticed such a problem with any other application (beside Pale Moon which is very similar). Sandboxie doesn't work, also I can't install Microsoft C++ Runtimes 2013 and 2015 (there's no setup window, nothing happens). I use XP Pro SP2 32bit without any newer updates. Keep up the good work! :)

**Comment by Skulltrail192** [comment]
Next releases will fix Visual C++ errors, is a know bug. Other applications, i will test
