### ISSUE TITLE
Merging all installers into one?

### ISSUE THREAD

**Issue by ghost** [Skulltrail192/One-Core-API-Binaries#20]
Currently, to install One-Core-API, you have to install about 8 installers. The fact that you need to install the  One-Core-API Base first is not obvious, and there's no clear order to install the rest of them in. Furthermore, if you reboot after installing One-Core-API Base, it tends to mess your system up. There's no reason to install any one installer alone, so why not move them all into one big installer (except for x86/x64 separation)?

**Comment by SSJ9899TDylan** [comment]
That's a great idea, but we should even make a true addon for it too.

**Comment by SSJ9899TDylan** [comment]
r3muxd, you are right because of the Windows File Protection promps that I got during my last 2 tests on Windows Server 2003

**Comment by Skulltrail192** [comment]
For now, it not my goal. I use several installer because it is better to discovery a problem, with independent functionalities. While One-Core-APi keep not stable, it will not changed. If want change it, please, fork and edit by yourself
