### ISSUE TITLE
BSOD IRQL_NOT_LESS_OR_EQUAL

### ISSUE THREAD

**Issue by mattodinaturas** [Skulltrail192/One-Core-API-Binaries#200]
Hi! I installed the latest One core api on my Lenovo T60 (w/ Intel t7400 cpu) running Windows xp sp3 x86. 
Yesterday after the installation process everything was fine, but today I noticed that when I plug or unplug the power cable, the system throws a bsod saying "IRQL_NOT_LESS_OR_EQUAL". Now even on battery mode or on AC power, without plugging and unplugging the cable, the system throws the same bsod shortly after login and is completely unusable. In safe mode the system works without issues and apps that require one core apis (example BBLogger ver. 1.1.3.7, which is based on dotnet 4.8) also work fine.

This is the install order: app compat -> base -> driver update -> API -set -> branding -> d3d -> additional ddls

Here are attached the minidumps. Thank you very much!

[Mini102223-01.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079272/Mini102223-01.dmp)
[Mini102223-02.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079273/Mini102223-02.dmp)
[Mini102223-03.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079274/Mini102223-03.dmp)
[Mini102323-01.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079275/Mini102323-01.dmp)
[Mini102323-02.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079276/Mini102323-02.dmp)
[Mini102323-03.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079277/Mini102323-03.dmp)
[Mini102323-04.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079278/Mini102323-04.dmp)
[Mini102323-05.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079279/Mini102323-05.dmp)
[Mini102323-06.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079280/Mini102323-06.dmp)
[Mini102323-07.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079281/Mini102323-07.dmp)
[Mini102323-08.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079282/Mini102323-08.dmp)
[Mini102323-09.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079283/Mini102323-09.dmp)
[Mini102323-10.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079284/Mini102323-10.dmp)
[Mini102323-11.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079285/Mini102323-11.dmp)
[Mini102323-12.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079286/Mini102323-12.dmp)
[Mini102323-13.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079287/Mini102323-13.dmp)
[Mini102323-14.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079288/Mini102323-14.dmp)
[Mini102323-15.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079289/Mini102323-15.dmp)
[Mini102323-16.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079290/Mini102323-16.dmp)
[Mini102323-17.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079291/Mini102323-17.dmp)
[Mini102323-18.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079292/Mini102323-18.dmp)
[Mini102323-19.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079293/Mini102323-19.dmp)
[Mini102323-20.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079294/Mini102323-20.dmp)
[Mini102323-21.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079295/Mini102323-21.dmp)
[Mini102323-22.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079296/Mini102323-22.dmp)
[Mini102323-23.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079297/Mini102323-23.dmp)
[Mini102323-24.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079298/Mini102323-24.dmp)
[Mini102323-25.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079299/Mini102323-25.dmp)
[Mini102323-26.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079300/Mini102323-26.dmp)
[Mini102323-27.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079301/Mini102323-27.dmp)
[Mini102323-28.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079302/Mini102323-28.dmp)
[Mini102323-29.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079303/Mini102323-29.dmp)
[Mini102323-30.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079304/Mini102323-30.dmp)
[Mini102323-31.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079305/Mini102323-31.dmp)
[Mini102323-32.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13079306/Mini102323-32.dmp)

**Comment by TowerProductions** [comment]
It also BSODs when I try to connect to it via RDP. OneCore API should update the files.

**Comment by mattodinaturas** [comment]
> It also BSODs when I try to connect to it via RDP. OneCore API should update the files.

Well, now is this installation of windows screwed royally or is there a way to uninstall opencoreapi, without a backup image of the disk?

**Comment by Skulltrail192** [comment]
Is this Windows XP SP3 "vanilla" or some edited, like "Integral Edition"?

**Comment by mattodinaturas** [comment]
> Is this Windows XP SP3 "vanilla" or some edited, like "Integral Edition"?

It's a completely stock retail version + legacy update (w/ posready). I think the issue is caused by Lenovo power management driver, if I uninstall it I don't get anymore bsods upon startup, but I still get them when I plug and unplug the power cord. In device manager now "Lenovo PM" is shown with a yellow "!"
The bsod and instability doesn't happen without installing oca. I think it's messing with the PM driver for some reason

**Comment by Skulltrail192** [comment]
Well, if possible, test without Posready 2009 updates.

**Comment by mattodinaturas** [comment]
> Well, if possible, test without Posready 2009 updates.

It's a bit involved but if I have time I'll give it a try

**Comment by windisklessfree** [comment]
https://github.com/windisklessfree/IRQ_NOT_LESS_OR_QUAL

**Comment by Skulltrail192** [comment]
Please test with version 3.0.4

**Comment by Skulltrail192** [comment]
As there was no response regarding a new test, the topic will be closed. If the author has any feedback, please reopen the topic and share new information.
