### ISSUE TITLE
Server 2003 x64 R2 throws activation error after installing base package.

### ISSUE THREAD

**Issue by Win7Devs** [Skulltrail192/One-Core-API-Binaries#202]
After installing the first (base) package, I cannot login, windows throws a Windows Product Activation error 
Similar to (Exact same as) [this on Reddit](https://www.reddit.com/r/windowsxp/comments/waxu5j/onecoreapi_issue_xp_x64_activation/?rdt=58644).
I tried this with x86 Windows, and the problem does not seem to exist. Will I have to move to x86, or is there a solution?

VM details:
VMware Player 17 (latest updated)
Windows Server 2003 R2 Standard x64 (with SP2)
4GB RAM
ISO from [Archive.org](https://archive.org/details/Windows_Server_2003_R2_Standard_x64)

**Comment by Skulltrail192** [comment]
Same #217

**Comment by Skulltrail192** [comment]
Test again with 3.0.4

**Comment by Skulltrail192** [comment]
As there has been no response since the possible fix was made available, this topic will be closed and the fix will be considered done.
