### ISSUE TITLE
Windows Server 2003 throws activation error after installing base package.

### ISSUE THREAD

**Issue by ss06009180** [Skulltrail192/One-Core-API-Binaries#206]
After installing the first (base) package,  Windows Logon throws a Windows Product Activation error  0x8004050a with the OEM or Retail license, the volume license does not have this problem.

![Windows XP Professional 测试-2023-11-01-19-24-40](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/23609607/15f75a1f-cee2-4f1f-b7b5-89b2e8b0375e)

OS: Windows XP Professional With SP2 x86 ，build 5.2.3790.6912

![Windows XP Professional 测试-2023-11-01-19-07-19](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/23609607/93a1b5bb-bfd4-4b96-a814-ccbf9c078e7e)

**Comment by jonm58** [comment]
> Windows XP Professional With SP2

Windows XP Professional SP2? 5.2.3790?

**Comment by sal-ammoniac** [comment]
> > Windows XP Professional With SP2
> 
> Windows XP Professional SP2? 5.2.3790?

he might be using some homebrew image or just converted using tweaknt. (应该是魔改的)

**Comment by ss06009180** [comment]
> > Windows XP Professional With SP2
> 
> Windows XP Professional SP2? 5.2.3790?

Modify the ISO image of Windows Server 2003 Standard Edition based on the leaked source code

![Windows XP Professional v2003-2023-11-08-15-20-48](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/23609607/2fb7c755-8f1e-4366-961c-f75457b5e9d8)

The Volume license With OneCoreAPI 3.0.3:
![Windows XP Professional v2003-2023-11-08-16-34-04](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/23609607/604a91c5-7359-4061-a0b4-8d9825960ca5)

**Comment by Skulltrail192** [comment]
Correct information: **Windows Server 2003** ...

**Comment by Skulltrail192** [comment]
I think it was solved at version 3.0.4. So, the topic will close.
