### ISSUE TITLE
Line by LY Corporation from Japan with ERROR: Cannot find Qt5Svg.dll

### ISSUE THREAD

**Issue by peter8777555** [Skulltrail192/One-Core-API-Binaries#208]
OS : Windows XP SP3
One-Core-API-Binaries : V3.0.3

I try two softwares.

1.
Internet Explorer V11 can NOT run Setup.exe

2.
A software for Windows 7,
Show error message "Cannot find Qt5Svg.dll"
(PS: There is no issue in Windows 7)

See sample for testing.
https://www.mediafire.com/file/eh6afxssdu2ezsc/Test_Setup_For_Win7.rar/file

**Comment by jonm58** [comment]
I put Qt5Svg.dll to system32,app can find,I get this
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/73036321/cc898c9a-1239-4deb-ba21-2c2ec28d26c9)

**Comment by peter8777555** [comment]
To jonm58 :

I try
copy qt5*.dll c:\windows\system32

Error message again ?

**Comment by jonm58** [comment]
> To jonm58 :
> 
> I try copy qt5*.dll c:\windows\system32
> 
> Error message again ? Do you use One-Core-API-Binaries : V3.0.3 ? No "API-SET" and "Modern Setup" packages in V3.0.3 ,is this issue ?

Then put Qt5Svg.dll in the folder with LineLauncher.exe

**Comment by peter8777555** [comment]
To jonm58 :

I put Qt5Svg.dll in the folder with LineLauncher.exe

Error message again ?

PS:
C:\Documents and Settings\Administrator\Local Settings\Application Data\Line\bin\6.7.4.2508
This are ALL files and run app OK in Windows 7.

**Comment by Skulltrail192** [comment]
I don't understond: what is the software?

**Comment by peter8777555** [comment]
To Skulltrail192:

Line by LY Corporation from Japan.

**Comment by jonm58** [comment]
have new ver line?
OCA 4.0.0RC1 seem fix cannot find QT5Svg.dll,but line update don't work

**Comment by Stepman123** [comment]
Installs and runs without any tricks. Server 3003 32-bit
![line](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/8846337/d8ce1f00-69ea-4cc5-8288-657e496edb95)

**Comment by peter8777555** [comment]
> have new ver line? OCA 4.0.0RC1 seem fix cannot find QT5Svg.dll,but line update don't work

Line the latest version:
V8.6.0.3277
https://desktop.line-scdn.net/win/new/LineInst.exe

Now OCA V3.0.5
How to get OCA 4.0.0RC1 ?

**Comment by peter8777555** [comment]
> > Internet Explorer V11
> 
> It's a joke?

Why is a joke ?
One-Core-API run some new softwares on Windows XP.
Internet Explorer V11 works on Windows 7.

**Comment by peter8777555** [comment]
> Installs and runs without any tricks. Server 3003 32-bit

I installs and runs on Windows XP ONLY.

Show error message "Cannot find Qt5Svg.dll"
(PS: There is no issue in Windows 7)

**Comment by Skulltrail192** [comment]
Just downloaded and installed:
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/d5736ea6-36a2-44e2-927e-9880c9b5a002)
So, i think this issue can be closed

**Comment by peter8777555** [comment]
> Just downloaded and installed: ![image](https://private-user-images.githubusercontent.com/5159776/306102808-d5736ea6-36a2-44e2-927e-9880c9b5a002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzOTE2MzcsIm5iZiI6MTcwODM5MTMzNywicGF0aCI6Ii81MTU5Nzc2LzMwNjEwMjgwOC1kNTczNmVhNi0zNmEyLTQ0ZTItOTI3ZS05ODgwYzliNWEwMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjBUMDEwODU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmUyN2NiNDI3YzBlNGY5MmU4OGJkZTg4ZTJjMjc5ZTkwZjU5M2NjYjgyODg2OGE0YzE5MTVlMDNkZjRlMmNiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UD4bkKqDyBUkH2Y1tKqeJ2E8NFg_Go4nP2r18teUtVQ) So, i think this issue can be closed

OCA V3.0.5 ?

**Comment by jonm58** [comment]
> > 有新版本线吗？  OCA 4.0.0RC1 似乎修复找不到 QT5Svg.dll，但行更新不起作用
> 
> 网站： [https://line.me/en/ ](https://line.me/en/) 下载最新版本： V8.6.0.3277 [https://desktop.line-scdn.net/win/new/LineInst.exe ](https://desktop.line-scdn.net/win/new/LineInst.exe)
> 
> 现在OCA V3.0.5 如何获取OCA 4.0.0RC1？

https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/

**Comment by peter8777555** [comment]
> > > 有新版本线吗？  OCA 4.0.0RC1 似乎修复找不到 QT5Svg.dll，但行更新不起作用
> > 
> > 
> > 网站： [https://line.me/en/ ](https://line.me/en/) 下载最新版本： V8.6.0.3277 [https://desktop.line-scdn.net/win/new/LineInst.exe ](https://desktop.line-scdn.net/win/new/LineInst.exe)
> > 现在OCA V3.0.5 如何获取OCA 4.0.0RC1？
> 
> https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/

Thank you very much.
I will test.
