### ISSUE TITLE
No "API-SET" and "Modern Setup" packages in V3.0.3

### ISSUE THREAD

**Issue by peter8777555** [Skulltrail192/One-Core-API-Binaries#209]
Does the "API-SET" package is important ?

**Comment by jonm58** [comment]
"API-Set was merged into Base Installer to support Windows 7 dlls, like sspicli.dll, what was repleaced (from wine to native Windows 7). It's fix Microsoft Essentials Security;"

**Comment by peter8777555** [comment]
Thank jonm58 for reply.
