### ISSUE TITLE
Breaking the Activation in XP x64 after installing

### ISSUE THREAD

**Issue by aroko-kun** [Skulltrail192/One-Core-API-Binaries#217]
Hello there, I found this issue with your patches in Windows XP X64 Edition.
I'm running XP Professional x64 Edition SP2, all updates installed by me, under VMware.

After installing these updates and doing a restart, the activation system got broken like hell. I tried activating it with a activation_patch but it still gives this error when logging in. I hope you might find a solution to this problem.

This XP x64 systems has not been modified with any TweakNT or running a beta build. This is the official XP x64 with SP2 installed by me.

![Windows XP Professional x64 Edition DDLC Modding-2023-11-22-20-52-12](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/88131513/752a91e7-d714-445a-9513-34f495fdff33)

**Comment by jonm58** [comment]
Check, Windows file protection, how do you deal with it?

**Comment by aroko-kun** [comment]
> Check, Windows file protection, how do you deal with it?

Normally when I should install these patches, Windows File Protection should come up, but it didn't for me. When I installed these patches, my XP x64 ISO File was not mounted. Maybe it's a XP x64 bug? I will try to experiment with it and maybe I will come with an update, but I will have to do a full reinstall of XP X64, since I can't even Log In to my user even via any mode of Safe Mode(normal, networking or CMD).

**Comment by jonm58** [comment]
> > Check, Windows file protection, how do you deal with it?
> 
> Normally when I should install these patches, Windows File Protection should come up, but it didn't for me. When I installed these patches, my XP x64 ISO File was not mounted. Maybe it's a XP x64 bug? I will try to experiment with it and maybe I will come with an update, but I will have to do a full reinstall of XP X64, since I can't even Log In to my user even via any mode of Safe Mode(normal, networking or CMD).

It is best that your Windows XP 64 bit has the latest patches
[I'm using Windows XP 64 bit](https://archive.org/details/xpx64_slip)

**Comment by Skulltrail192** [comment]
Same #202

**Comment by Skulltrail192** [comment]
Test again with 3.0.4

**Comment by mkgrn** [comment]
The same issue on x86 Home Edition SP3 after installing OCA 4.0.0 

![Image](https://github.com/user-attachments/assets/48035c58-7384-49cf-951a-ee873ef202a9)

**Comment by nixxoq** [comment]
@Skulltrail192
