### ISSUE TITLE
Blue screen after rebooting after installation of base package 

### ISSUE THREAD

**Issue by Nickelexp** [Skulltrail192/One-Core-API-Binaries#218]
OS: Windows XP Professional x64 Edition with all updates(by legacy update)

Problem: Downloaded One Core Api 3.0.3,installed base package(during installation there was windows file protector window, which was saying about recovery of original windows files by SP2 disk, but I cancelled them all). After installation, setup showed, that I need to reboot. I rebooted and now I can't go to system, because a blue screen "STOP c000021a" (I'll send the photo)

What I need to do? 
![IMG_20231201_000111](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/152532305/e7c5941f-d12e-46e0-86c5-7345b37cf54b)

**Comment by Skulltrail192** [comment]
Do you have Wifi adapter?

**Comment by Skulltrail192** [comment]
Try this version: https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/tag/3.0.4-20231130-experimental
For boot, unplug wifi adapter, uninstall older and install new and plug in again.

**Comment by Nickelexp** [comment]
> Try this version: https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/tag/3.0.4-20231130-experimental For boot, unplug wifi adapter, uninstall older and install new and plug in again.

Thanks, but I need to re-install my Windows XP. I've tried to install One Core Api before and every time I needed to re-install my windows, but again, thanks I'll try and reply later

**Comment by Skulltrail192** [comment]
Please test again with 3.0.4

**Comment by Skulltrail192** [comment]
Since don't return with new test, the topic be close. If the error keep occouring, open again.
