### ISSUE TITLE
dxdiag (Directx diagnostic Tool) and some question dialog is still english

### ISSUE THREAD

**Issue by TK50P** [Skulltrail192/One-Core-API-Binaries#225]
![Screenshot 2023-12-08 221325](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/127497974/a30f5f45-a397-4b81-95ae-bd0228e8880e)
![Screenshot 2023-12-08 221533](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/127497974/dda55726-3f98-4b04-9813-b9c85cb27e9b)
I installed it on Korean, dxdiag and some dialog Yes/No/Cancel button is still english.
Can you fix it on next release?
Version: OCAPI 3.0.4
OS: Windows XP MCE 2005 with SP3

**Comment by Skulltrail192** [comment]
Done in version 3.0.5
