### ISSUE TITLE
add amdppm.sys into OCA

### ISSUE THREAD

**Issue by sal-ammoniac** [Skulltrail192/One-Core-API-Binaries#226]
while Windows XP does have intelppm.sys for Intel Processor, it lacks amdppm.sys originally.
Microsoft gives amdppm.sys update in 2007/08/09 for XP and 2003.

https://catalog.s.download.windowsupdate.com/msdownload/update/driver/drvs/2008/02/20075410_007bedf9f3ae30f0211b56b662d2e1ffa3e6cfeb.cab

**Comment by Skulltrail192** [comment]
Added at version 3.0.5
