### ISSUE TITLE
NotepadEx Save windows problem

### ISSUE THREAD

**Issue by jonm58** [Skulltrail192/One-Core-API-Binaries#229]
[NotepadEx](https://github.com/vxiiduu/NotepadEx)
![NotepadEx](https://cdn.discordapp.com/attachments/1030009770385625108/1183548911021981706/image.png)
[user.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13629588/user.dmp)

**Comment by Stepman123** [comment]
[user.dmp](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13630847/user.dmp)

**Comment by Skulltrail192** [comment]
This app maybe use open/save implementation only avaliable on Vista+. It is under development.

**Comment by vxiiduu** [comment]
try this one and see what happens, it runs unmodified on NT4.0 and up.
[notepad.zip](https://github.com/Skulltrail192/One-Core-API-Binaries/files/13694358/notepad.zip)

**Comment by jonm58** [comment]
Thanks
![图片](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/73036321/dffad7ac-370f-4590-b174-cdbb5588983d)

**Comment by Skulltrail192** [comment]
See the latest canary verion, 3,0,5 preview. Solved this issue.

**Comment by jonm58** [comment]
problem solved
