### ISSUE TITLE
is there a extened kenrenal for win7 

### ISSUE THREAD

**Issue by bradycodemaster** [Skulltrail192/One-Core-API-Binaries#231]
windows vista and xp have one so why not 7

**Comment by Snaky1a** [comment]
In the future, One-Core-API will support of Windows 7 and much more.

For now, the “Windows 7 Extended kernel” exists: it is [VxKex](https://github.com/vxiiduu/VxKex)

**Comment by Skulltrail192** [comment]
One-Core-API will be compatible with Windows Vista-8.1 on 2024. For now, no. The topic will be closed.
