### ISSUE TITLE
i found another extened kenreal for xp

### ISSUE THREAD

**Issue by bradycodemaster** [Skulltrail192/One-Core-API-Binaries#232]
maybe we can use it to have more apps working
https://www.betaarchive.com/forum/viewtopic.php?t=36763

**Comment by jonm58** [comment]
> maybe we can use it to have more apps working [betaarchive.com/forum/viewtopic.php?t=36763](https://www.betaarchive.com/forum/viewtopic.php?t=36763)

[ExtendedXP](https://github.com/DibyaTheXPFan/ExtendedXP-Core-Api-implementation)
last update is 6 years ago,lol.

**Comment by bradycodemaster** [comment]
https://www.mediafire.com/file/4k48mb5tt73jmvy/BuildEnviroment.7z/file

**Comment by sal-ammoniac** [comment]
It is not actively developed anymore
just wait for Opensource Api Wrapper coming

**Comment by Skulltrail192** [comment]
It is from a my friend, and not work really. So, i think better option close this topic
