### ISSUE TITLE
NET 4.8 is not recognized by the new version

### ISSUE THREAD

**Issue by Kevin0928000** [Skulltrail192/One-Core-API-Binaries#234]
This is the old version 2.10.0
![02](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/72051291/5a45bb6e-4c05-41a9-b3d2-23c657f7d213)

This is the new version 3.0.4
![01](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/72051291/25bfb423-88ca-4428-bd95-564aa51db285)

Supplement: System Windows XP SP3 x86 4GB
NET4.8 installed

**Comment by Skulltrail192** [comment]
Are you installed BEFORE .net 2.0-3.5 and 4.0?

**Comment by Kevin0928000** [comment]
No, because the minimum version supported by this application is NET4.8

This is the result of not installing all NET components, API version 3.0.4
![03](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/72051291/0dc7cc15-eae4-4a70-a714-cb1d9d35dab2)

This is the result of installing NET2.0 and 3.5, API version 3.0.4
![04](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/72051291/63b16a46-553a-45b6-80b7-249c41f943ea)

**Comment by jonm58** [comment]
![图片](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/73036321/4b9bbfc2-0467-44ae-976b-8f12a8aceb93)
![图片](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/73036321/b465210a-9f55-41b4-ad0e-d108563458ee)
![图片](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/73036321/46c74230-0a3f-41e2-8127-1162b34017a0)

working good for me

**Comment by Kevin0928000** [comment]
this is my status
![05](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/72051291/9c0489fa-3de3-4e95-8347-1ded16a037c9)
![06](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/72051291/b2a9e5ad-c783-447d-a443-7d246bd503e5)

**Comment by jonm58** [comment]
> 这是我的状态 ![05](https://private-user-images.githubusercontent.com/72051291/291024045-9c0489fa-3de3-4e95-8347-1ded16a037c9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3ODAyMzksIm5iZiI6MTcwMjc3OTkzOSwicGF0aCI6Ii83MjA1MTI5MS8yOTEwMjQwNDUtOWMwNDg5ZmEtM2RlMy00ZTk1LTgzNDctMWRlZDE2YTAzN2M5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDAyMjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ODVlZjMwMGYxMDFiOGM4NDc4ZGNiMzhlZGZjZWNhNjFmNGI5OWJjZjVlMmEyMjE4OGMyNWEwMjAyZWYxOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5FgS2O__Fi2KYa6Xfcnai0_U_rCRB_xzOpUZmtMHlbU) ![06](https://private-user-images.githubusercontent.com/72051291/291024046-b2a9e5ad-c783-447d-a443-7d246bd503e5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3ODAyMzksIm5iZiI6MTcwMjc3OTkzOSwicGF0aCI6Ii83MjA1MTI5MS8yOTEwMjQwNDYtYjJhOWU1YWQtYzc4My00NDdkLWE0NDMtN2QyNDZiZDUwM2U1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDAyMjUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3OTIzNzE4MGE4ZDNmZDA0MmRmZjE2MzJiYTk1ZTczOGRhYjI4NjJjZGJkMDJlYzE4NTRlOWZhNjM2MDZiN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yBywTX80MukCVdcjTMI7sGbxSm2iz6zgb6RBKOM1dy0)

Did you install .net 4.0 and then .net 4.8?

**Comment by Kevin0928000** [comment]
No
Only NET4.8

**Comment by jonm58** [comment]
> No Only NET4.8

That's what you're wrong about

please from dotnet 4.0 to update dotnet 4.8

**Comment by Kevin0928000** [comment]
result
![07](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/72051291/5503135d-d959-4c15-a213-90ee2181e48d)

**Comment by Kevin0928000** [comment]
I think the problem is not NET4.8 but API 3.0.4
Because in the old version 2.10.0, you only need to install NET4.8

**Comment by jonm58** [comment]
> 我认为问题不是NET4.8而是API 3.0.4 因为在旧版本2.10.0中，只需要安装NET4.8

Strange, can you give me this file?

**Comment by Kevin0928000** [comment]
https://drive.google.com/drive/folders/1hMTjCSpPEarY-p_yjMjNi3fGiDAe44tk?usp=drive_link

**Comment by jonm58** [comment]
![图片](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/73036321/6119aa6c-1d79-4b27-a3a1-df67cd37d121)

Use this to package in winxp [dotNetFx4xW7](https://github.com/abbodi1406/dotNetFx4xW7) then update .net4.0 to 4.8

**Comment by Kevin0928000** [comment]
doesn't seem to work
![08](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/72051291/6139ab8e-f2c8-4f1c-848f-50922a6247e5)

I have uploaded my XP system to google drive

**Comment by Kevin0928000** [comment]
It is definitely a problem with API 3.0.4. The following is a comparison
![01](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/72051291/5097d7c6-c135-4888-a212-3bd1040b0355)
![02](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/72051291/7b0ccd88-38ad-43de-8907-08e8ef38a464)

**Comment by Kevin0928000** [comment]
> Are you installed BEFORE .net 2.0-3.5 and 4.0?


https://github.com/Skulltrail192/One-Core-API-Binaries/assets/72051291/131ab872-77ce-4021-b3ac-0af487ca0bca
