### ISSUE TITLE
Failed To Load steamui.dll

### ISSUE THREAD

**Issue by UangGaming** [Skulltrail192/One-Core-API-Binaries#236]
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/85173746/8b60e5ba-5cdf-4913-85b8-0efc6c8b31d7)
i have error steamui.dll problem it's steam client version January 26th, 2023

**Comment by Skulltrail192** [comment]
It's seem solved for next 3.0.5 version. However, for now, can't log in for now.

![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/e804dd30-ac4e-421b-bf2e-513693c71a5b)

**Comment by Skulltrail192** [comment]
Fixed at version 3.0.5
