### ISSUE TITLE
Is planned One Core API for Windows 95/98/ME and Windows NT 3.1/3.5/3.51/4.0 in 2024?

### ISSUE THREAD

**Issue by EgorKuzevanov** [Skulltrail192/One-Core-API-Binaries#239]
**Skulltrail192**, do you plan to develop One Core API for Windows operating systems from 1990s (Windows 95/98/ME and Windows NT 3.1/3.5/3.51/4.0) in 2024?
- Firstly, the KernelEx for Windows 98/ME available on the [MSFN forum](https://msfn.org/board) does not currently support running Firefox-like browsers [Serpent 52](http://o.rthost.win/basilisk/), [New Moon 28](http://o.rthost.win/palemoon/) and [K-Meleon 76](http://o.rthost.win/kmeleon/) for Windows XP/2003/Vista, as well as universal command-line utility [TCIMG](https://wincmd.ru/plugring/tcimg.html) compiled with [AutoIt v3.3.16.1](https://www.autoitscript.com/autoit3/files/archive/autoit/autoit-v3.3.16.1.zip) (requiring a minimum of Windows XP SP2).
- And secondly, at the moment there are no extended kernels for Windows 95 and Windows NT 3.1/3.5/3.51/4.0.

**Comment by p1glynlol** [comment]
I think it would be extremely impossible to port OCAPI to Windows NT 3.1-4.0 (especially DOS-based). 2000 (NT 5.0) seems promising.

For Windows 98-ME however, there is KernelEx and the files from OCAPI can be useful for stubbing.

**Comment by EgorKuzevanov** [comment]
> I think it would be extremely impossible to port OCAPI to Windows NT 3.1-4.0 (especially DOS-based). 2000 (NT 5.0) seems promising.
> For Windows 98-ME however, there is KernelEx and the files from OCAPI can be useful for stubbing.
On Windows 2000 SP4 with Extended Kernel by blackwingcat, universal command-line utility [TCIMG](https://wincmd.ru/plugring/tcimg.html) compiled with [AutoIt v3.3.16.1](https://www.autoitscript.com/autoit3/files/archive/autoit/autoit-v3.3.16.1.zip) (requiring a minimum of Windows XP SP2) runs properly if you use the NNN4NT5.exe utility to replace the Windows kernel version to Windows NT 5.1.2600 SP3 (i.e. Windows XP SP3). Why doesn't the TCIMG utility run on Windows 98 SE with KernelEx?:
![IMG_1105](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/78859951/7e59996d-a007-4635-b544-a181abed26ca)
![IMG_1106](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/78859951/b9e5b35b-586b-4212-bafb-054598c740b7)
![IMG_1107](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/78859951/03f47bc5-213c-4dd4-b7a0-d537fd5645e7)

**Comment by p1glynlol** [comment]
> Can you tell me instructions on how to install KernelEx v4.5.2 with unofficial updates on Windows 98 SE without rebooting into MS-DOS mode? Because using the MS-DOS command line to copy and move Windows 98 system files (including overwriting) is very inconvenient.

I don't have a Windows 98/ME machine. But this installer can be useful: https://retrosystemsrevival.blogspot.com/2021/04/kernelex-45201924-installer.html

**Comment by EgorKuzevanov** [comment]
> https://retrosystemsrevival.blogspot.com/2021/04/kernelex-45201924-installer.html

Your link contains an old KernelEx installer for Windows 98 from 2021, which does not support running the latest builds of the Serpent 52 browser from 2023.

**Comment by EgorKuzevanov** [comment]
> I think it would be extremely impossible to port OCAPI to Windows NT 3.1-4.0 (especially DOS-based). 2000 (NT 5.0) seems promising.

If the Windows NT 4.0 SP6 kernel cannot be modified to reach the Windows 7 or Windows 10 level, then it may be possible to reach at least the Windows XP SP3 level (enough to run Firefox-like browsers by **roytam1** and **Feodor2** )?

**Comment by Snaky1a** [comment]
> I think it would be extremely impossible to port OCAPI to Windows NT 3.1-4.0 (especially DOS-based). 2000 (NT 5.0) seems promising.

Yeah, Windows 9x systems and early versions of Windows NT may not be compatible with the One-Core-API

But someone had tried creating an extended kernel for Windows NT 4.0: 

https://msfn.org/board/topic/182201-windows-nt4-extended-kernel/ (for now, it's a dead project)

https://msfn.org/board/topic/183418-i-am-trying-to-create-an-extended-kernel-for-nt4/page/2/ (last update 25 August, 2023)

**Comment by Skulltrail192** [comment]
No, no planned version of OCA to support bellow Windows 2000.

**Comment by Aspire89** [comment]
Skulltrail192 thanks you

**Comment by Skulltrail192** [comment]
As I am only a man and not God, it is impossible to maintain so many systems...Not even Microsoft does that. Then this topic will be closed.
