### ISSUE TITLE
Windows 2000 support

### ISSUE THREAD

**Issue by Aspire89** [Skulltrail192/One-Core-API-Binaries#240]
Will One Core Api support Windows 2000 SP4

**Comment by jonm58** [comment]
win2k have that, name is "KernelEx for Win2000"

**Comment by Aspire89** [comment]
> win2k have that, name is "KernelEx for Win2000"

There is also an extended kernel for Windows Vista, but nevertheless, One Core Api will support this system, and besides, KernelEx is quite outdated

**Comment by jonm58** [comment]
https://github.com/Skulltrail192/One-Core-API-Binaries/issues/239#issuecomment-1868565612

**Comment by Skulltrail192** [comment]
As I am only a man and not God, it is impossible to maintain so many systems...Not even Microsoft does that. Then this topic will be closed. if OCA get support for Windows 2000, i will annunce for all.
