### ISSUE TITLE
Using Blackwingcat's works in future One Core API for Windows 2000

### ISSUE THREAD

**Issue by EgorKuzevanov** [Skulltrail192/One-Core-API-Binaries#242]
**Skulltrail192**, if you start developing One Core API for Windows 2000 SP4 in 2024, will you use works by **blackwingcat** (author of Windows 2000 Extended Kernel)? Or will it be a separate project, not related to **blackwingcat** and Windows 2000 Extended Kernel?

I believe that at the initial stage of development of the One Core API for Windows 2000 SP4, most of the works from Windows 2000 Extended Kernel by **blackwingcat** should be transferred there. Namely, all WinAPI functions from Windows XP, Windows Server 2003, Windows Vista and Windows 7 and support for latest DirectX versions using WineD3D project.

In addition, unlike Windows 2000 Extended Kernel by **blackwingcat**, future One Core API for Windows 2000 SP4 should provide support for original English and Russian versions of Windows 2000 SP4 with Internet Explorer 5.0 and without installed updates (Update Rollup 1, Internet Explorer 6.0 SP1 with Cumulative Security Update, DNS Update, etc).

**Comment by EgorKuzevanov** [comment]
Second question:
Are **Skulltrail192** and **blackwingcat** planning to collaborate and share their experiences with modern software on Windows 2000 SP4? By analogy with CodeWeavers (developer of a CrossOver is a paid Wine for Mac OS X) and the Wine development team.

**Comment by jonm58** [comment]
please STOP ask Win2k
https://github.com/Skulltrail192/One-Core-API-Binaries/issues/239#issuecomment-1868565612

**Comment by Skulltrail192** [comment]
As I am only a man and not God, it is impossible to maintain so many systems...Not even Microsoft does that. Then this topic will be closed.
