### ISSUE TITLE
Video and audio is glitchy when playing youtube videos on Chrome 102

### ISSUE THREAD

**Issue by ChrisSpartan** [Skulltrail192/One-Core-API-Binaries#243]
the title explains itself, trying to play youtube videos is just glitchy while the audio is just choppy, i'm using windows xp x86 with chrome 102 cuz i can't get chrome 120 to work but that's not the point, i do have VmAudioFixTray and VMAudioBack since i use vmware but that barely does anything, it only affects to chrome, the system sounds work fine, the glitchy and the choppiness gets worse when my cursor moves around in the window, i know is a stupid issue but i need a fix, not like asap but you get my point

**Comment by Skulltrail192** [comment]
Report on official main thread: #178

**Comment by Stepman123** [comment]
This is a known issue with windows XP +360EE (chrome86) and other builds. There is no solution.

**Comment by ChrisSpartan** [comment]
> This is a known issue with windows XP +360EE (chrome86) and other builds. There is no solution.

Oh, well that sucks

**Comment by ChrisSpartan** [comment]
btw in windows server 2003 sp2, aside from the freezing and bsod issues the video and audio less glitchy and choppy then on windows xp, there is some glitchy and choppiness but it's really minor that it doesn't matter
