### ISSUE TITLE
Restoration of Windows 9x computers

### ISSUE THREAD

**Issue by Saswat2005** [Skulltrail192/One-Core-API-Binaries#244]
Plan No 1. Install Windows XP on Windows 95 or Windows 98 computer with or without upgrading the hardware.
Plan No 2. Customize Windows XP into Windows 95, Windows 98, Windows M.E. or Windows 2000.
Plan No 3. Internet must be lightweighted, transformed into 1998, 2000 or whatever. Or let it be 2024.
Plan No 4. Program developing or App Store with restricted apps unlocked with extended kernel like One Core A.P.I.
Plan No 5. Updates need to work on browsers, as well as everything that was buggy, need to be fixed.
Plan No 6. Sell the old computers to the store and everything will be okay.

@Skulltrail192 and @Snaky1a, these are the 6 plans I have to do it to restore the computers. If the plan is okay, let's go on and on in 2024 or beyond. Think that it's 1985, 1985 is a good year, so let 2024 be like 1985. 1985 life needs to work in 2024.

**Comment by jonm58** [comment]
Stop, One Core API does not intend to support Windows 9X and Windows 2000 OS

Unless Jesus becomes a member of the project.

**Comment by Snaky1a** [comment]
What? OCA won't support Windows 9x and 2000, because it's a very-very hard work.

As @jonm58 said:
> Unless Jesus becomes a member of the project.

It's a true opinion.

**Comment by Saswat2005** [comment]
> Stop, One Core API does not intend to support Windows 9X and Windows 2000 OS
> 
> Unless Jesus becomes a member of the project.

I know that One Core A.P.I does NOT support the operating systems earlier than Windows XP. But I'm customizing Windows XP into Windows 9x. I'll install Windows XP on Windows 9x computer first.

**Comment by Saswat2005** [comment]
Resource customization: - https://youtu.be/nIL0MRmXaZU?si=IbWkvmRbe7uM4vN4
