### ISSUE TITLE
Microsoft Edge 109 often crashes

### ISSUE THREAD

**Issue by TK50P** [Skulltrail192/One-Core-API-Binaries#247]
![crash](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/127497974/8243649f-73ff-47e1-8fae-5445b85e3ab7)
On Windows Server 2003 x64.......

**Comment by Skulltrail192** [comment]
Test this:
https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/tag/3.0.5-20231227-experimental

**Comment by TK50P** [comment]
I don't know, windows xp x64 doesn't work microsoft edge after installed experimental version of One-Core-API. it shows Entey Point Not found
![Screenshot 2024-01-11 004716](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/127497974/b51fae87-012e-4c7f-8d02-1bfd9379cdc8)

**Comment by Skulltrail192** [comment]
Fixed at version 3.0.5
