### ISSUE TITLE
Windows Server 2003 Crashing after installing the base

### ISSUE THREAD

**Issue by ChrisSpartan** [Skulltrail192/One-Core-API-Binaries#249]
Yea so after installing the base it just crashes randomly with the same error page_fault_in_nonpaged_area 0x00000050, sometimes it crashes on the login screen, other times it crashes when trying to login to the OS, trying to open Chrome 102 and it even crashes when I’m doing nothing, very few times tho, if that’s not enough info I will go to event viewer and translate it since the OS is in Spanish

**Comment by Skulltrail192** [comment]
- Windows version, including updates:
- Iso used;
- Is Virtual Machine or Real Machine?
- If VM, what is used?
- If Real, What is the hardware configuration?
- Enable dump generation and upload to some driver;

**Comment by ChrisSpartan** [comment]
> * Windows version, including updates:
> * Iso used;
> * Is Virtual Machine or Real Machine?
> * If VM, what is used?
> * If Real, What is the hardware configuration?
> * Enable dump generation and upload to some driver;

Is a virtual machine, not using much

**Comment by Skulltrail192** [comment]
-If VM, what is used?
- Iso used;
- Configuration of VM;

**Comment by ChrisSpartan** [comment]
> -If VM, what is used?
> 
> * Iso used;
> * Configuration of VM;

If your referring to if use the dvd drive, no I don’t and the configuration of the vm is

Memory is 4 GB
Processors 2
Hard Drive 40 GB
Network Adapter at NAT
USB Controller Compatibility at 2.0
Sound Card Auto Detected and Display Auto Detected 

not sure what I need to change, I did notice the 3d graphics is on but I’m not sure if turning them off will do anything

**Comment by Skulltrail192** [comment]
-Iso used;

**Comment by ChrisSpartan** [comment]
> * Iso used;
> * What is the VM used? Vmware, virtual box or what?

In VMware and i only use a iso for installing the OS but I’m confused on what are you referring to so sorry

**Comment by ChrisSpartan** [comment]
Miss click sorry

**Comment by Skulltrail192** [comment]
I need a link to the iso used to download, because in none of the necessary tests, this error occurs. I also need to know the vmware version.

**Comment by ChrisSpartan** [comment]
> I need a link to the iso used to download, because in none of the necessary tests, this error occurs. I also need to know the vmware version.

Ok so it wasn’t a iso file I install server 2003 from, it was a burn copy or something of server 2003 enterprise edition in Spanish, I turn on the vm back after I turn off 3d graphics and seems like the issue is gone, weird and if your talking about the VMware I’m using is 17.5.0

**Comment by ChrisSpartan** [comment]
It seems like the 3D Graphics was the issue, but I need to make sure it was the issue so I’m gonna turn it on and see for myself if the issue is back so I’ll update

**Comment by ChrisSpartan** [comment]
Update it still crash even with 3d graphics off

**Comment by ChrisSpartan** [comment]
@Skulltrail192 ok so i got the burn dvd copy of server 2003 into a iso file from my old laptop since it has a dvd drive, i pass it over to the laptop i use now, since i can't upload iso files in github i uploaded in google drive here: https://drive.google.com/drive/folders/1FZVjtNJh1aKs1j7LdPhTRrQH7Nc38dfG?usp=sharing if there's any issues with the link, tell me

**Comment by Skulltrail192** [comment]
And correct place to report BSOD is #233

**Comment by ChrisSpartan** [comment]
> And correct place to report BSOD is #233

ok

**Comment by ChrisSpartan** [comment]
> > @Skulltrail192 ok so i got the burn dvd copy of server 2003 into a iso file from my old laptop since it has a dvd drive, i pass it over to the laptop i use now, since i can't upload iso files in github i uploaded in google drive here: https://drive.google.com/drive/folders/1FZVjtNJh1aKs1j7LdPhTRrQH7Nc38dfG?usp=sharing if there's any issues with the link, tell me
> 
> Don't work. I can't see and download the iso

i realize that google thinks it's a virus or smth, so i'm gonna upload it to mediafire so i'll update

**Comment by ChrisSpartan** [comment]
@Skulltrail192 ok here's new link: https://www.mediafire.com/file/4jy3jci47ftv9h8/NRMEFPP_ES.ISO/file#

**Comment by Skulltrail192** [comment]
Thanks, downloading and will test

**Comment by sal-ammoniac** [comment]
> It seems like the 3D Graphics was the issue, but I need to make sure it was the issue so I’m gonna turn it on and see for myself if the issue is back so I’ll update

VMWare 17.5 does have issue on 3D graphics even with Windows 11 Guest. So maybe use TP23H1 instead

**Comment by Skulltrail192** [comment]
An interesting fact: you gave me an iso that contains Server 2003 SP1, which is not supported at this time. Therefore, I recommend using an Iso with SP2. So this topic will be closed

**Comment by ChrisSpartan** [comment]
> An interesting fact: you gave me an iso that contains Server 2003 SP1, which is not supported at this time. Therefore, I recommend using an Iso with SP2. So this topic will be closed

Dude my vm with server 2003 is already in sp2 because of legacy update and it still crash, in fact when I was checking if it was in sp2 or not it just crash with the same error

**Comment by Skulltrail192** [comment]
try a integrated SP2 iso.

**Comment by ChrisSpartan** [comment]
> try a integrated SP2 iso.

Yea, maybe I’ll try that but for now I’m messing around with my old PC from 2012 so I might update in a few days since it’s slow

**Comment by ChrisSpartan** [comment]
> I installed your iso, on Vmware 17 on Windows 10 and getting error related with SP1, no BSOD. So, i will try update by Legacy Update, but, more easy for me if you upload your VM and i analyze.

Um ok

**Comment by ChrisSpartan** [comment]
Update: it's been almost a year since i put my last comment but to anyone that's wondering, with the latest version of one core api, version 4.0.0, windows server 2003 finally stop crashing, or at least as i'm writing this

**Comment by nixxoq** [comment]
> Update: it's been almost a year since i put my last comment but to anyone that's wondering, with the latest version of one core api, version 4.0.0, windows server 2003 finally stop crashing, or at least as i'm writing this
> 
> Edit: nvm, still crashes, just less often

re-open issue

**Comment by ChrisSpartan** [comment]
> > Update: it's been almost a year since i put my last comment but to anyone that's wondering, with the latest version of one core api, version 4.0.0, windows server 2003 finally stop crashing, or at least as i'm writing this
> > Edit: nvm, still crashes, just less often
> 
> re-open issue

I’ll leave it closed, is not that big of a deal, especially since I can’t open it myself
