### ISSUE TITLE
kernel installer gives black screen in vbox vm?

### ISSUE THREAD

**Issue by toddfraser88** [Skulltrail192/One-Core-API-Binaries#25]
I ran kernel installer (the part with ntoskrnl.exe) it installed, however on reboot I got a black screen.
This is in a vbox vm

is this normal behavior?

**Comment by Skulltrail192** [comment]
What system? Can you are more specific?

**Comment by NEO-SPECTRUMAN** [comment]
after turn on I/O APIC in virtual box
windows normally run
