### ISSUE TITLE
One-Core-API-Binaries-3.0.5  x64 Stuck during installation 

### ISSUE THREAD

**Issue by twttafku** [Skulltrail192/One-Core-API-Binaries#253]
One-Core-API-Binaries-3.0.5 
I'm stuck in the installation interface as shown in the picture. Please help me check it out.

![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/79491553/b5ef2359-21f4-494d-905e-7965e4f3e38c)

**Comment by Skulltrail192** [comment]
Close the certupdate.exe process and download again the package. This was fixed;.

**Comment by twttafku** [comment]
thanks. it works.
