### ISSUE TITLE
Windows hangs on Windows logo after installing base (XP x64)

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [Skulltrail192/One-Core-API-Binaries#258]
After installing the base package on a Dell Latitude D630 (Intel Pentium T4500/4GB RAM/Intel GMA X3100) running XP x64, when attempting to boot Windows, it hangs on the Windows XP logo with no HDD activity and the loading bar stops moving. Safe mode works fine.

Using version 3.0.5

**Comment by Skulltrail192** [comment]
If you reinstalled OCA (uninstalling previous and install new), i recommend do a fresh install (by strach)

**Comment by Lost-Entrepreneur439** [comment]
This was a clean install of OCA.

**Comment by Skulltrail192** [comment]
What is the Windows Service pack installed? And the drivers? What is the iso used?

**Comment by Skulltrail192** [comment]
Closing issue since reporter not returned

**Comment by TechGigant** [comment]
> I've just installed One-Core API on Windows x64 on real hardware and confirm, it doesn't boot and is stuck on the bootscreen. I tried it with only IE8 and WM11 installed and also with all updates installed and it doesn't work.
> 
> Before installing One-Core i installed all my drivers (whick work without issues) and came preinstalled with SP2.

I am having these exact same issues.

**Comment by Skulltrail192** [comment]
What ISO used and both cases?

**Comment by TechGigant** [comment]
> What ISO used and both cases?

I used https://archive.org/details/xpx64_slip
I also had the drivers for my motherboard and GPU installed, ASUS P8P67 LE and a GT 710 2GB.
