### ISSUE TITLE
ReactOS 0.4.11 build number for OCA support?

### ISSUE THREAD

**Issue by mtsxslnk** [Skulltrail192/One-Core-API-Binaries#26]
I'm trying to install OCA on ReactOS 0.4.11-dev (Build 20181126-0.4.11-dev-850-g57d48a7.GNU_4.7.2).
Some notes:
1. I have to change "Uniprocessor Checked" to "Uniprocessor Free" to start installation.
2. If I do that, I can get halfway through OCA base installation, but then I get this error:
"ERROR_PROCESS_ABORTED - The process terminated unexpectedly."
Is there anything else I should be doing?
Or is there only one build that works with ReactOS?

**Comment by Skulltrail192** [comment]
It will works a litte different from windows. Need a installer of 3rd. Reactos seem not support hotfix system of Windows
