### ISSUE TITLE
You say IFileDialog is needed for PaleMoon and other software. But this is not the case.

### ISSUE THREAD

**Issue by Anixx** [Skulltrail192/One-Core-API-Binaries#260]
There are simple Windhawk mods that allow to use the XP-style file picker in Win10 and Win11:
https://winclassic.net/post/12485/thread

All software is compatible with the old dialogs, all works well. Even custom controls work well. So, introducing IFileDialog is not needed! Just redirect things to the
XP one, keep XP spirit!

P.S. Don't you think about making WindHawk compatible with One-Core-API?

**Comment by jonm58** [comment]
> introducing IFileDialog is not needed!

lmao

**Comment by Skulltrail192** [comment]
Several new applications need a new API/Interface called IFileDialog. XP/2003 doesn't have any implementation about it. I Implemented a wrapper to "simulate" this implementation, redirecting to old impletation, supported by XP/2003. This feature is very important, try open/save anything on XP/2003 without it in Opera/firefox, chrome/notepad++/movie maker and several others. So, try don't lost my time asking nothing and opening issue for nothing!
