### ISSUE TITLE
A problem with Minecraft Bedrock Edition (Win32 build) crash when trying to open the world at the very end of the loading.

### ISSUE THREAD

**Issue by Max-RM** [Skulltrail192/One-Core-API-Binaries#262]
This game (Minecraft Bedrock Edition win32) works on Windows XP with OneCoreAPI: 

https://github.com/Skulltrail192/One-Core-API-Binaries/assets/81485476/d38616a1-6733-46a2-bb26-ed9a089216b3

but crashes when trying to open the world at the very end of the loading.

Althought it works on Windows 7 without any problems: 
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/81485476/c6667249-6c35-43cc-85b2-08c279283c2e)

Here build that from video (it was modified by OptiJuegos): https://www.mediafire.com/file/y9cq2460i7ta155/OptiCraft_1.16.12_By_OptiJuegos_OpenGL_4.1.7z/file
Original build: https://t.me/MDLC_main/632 (Need a telegram account to download file from it).

**Comment by TukangM** [comment]
bruh 😭

**Comment by Max-RM** [comment]
> bruh 😭

![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/81485476/03f341fc-c807-4ec8-92ba-80d3066e5df8)

**Comment by TukangM** [comment]
lel hahaha 
> ![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/91467886/86392c91-9217-4c2e-b3ca-6ab11de10ff0)

**Comment by Max-RM** [comment]
It was Video Card issue
