### ISSUE TITLE
Installing One-Core-API on Windows XP/2003 x64 breaks VirtualBox Guest Additions

### ISSUE THREAD

**Issue by ItsAndrewDev** [Skulltrail192/One-Core-API-Binaries#267]
After installing One-Core-API Base Package in *both* Windows XP x64 and Windows Server 2003 R2 x64 (SP2 for both), the mouse stops responding (stuck) after the reboot. Standard keyboard works as expected, but Display driver non-functional. Windows additionally asks for a Base Machine Driver.
Uninstalling VirtualBox Guest Additions seems to resolve this problem.

Edit: I tested this on VirtualBox 7.0, and I'm currently downgrading my VirtualBox to VirtualBox 6.1 and trying again.

**Comment by jonm58** [comment]
"VirtualBox 5.2.44 or 6.0.24 versions are highly and strongly recommended. Most versions of VirtualBox from 6.1.x branch onwards (including both VirtualBox 6.1.x and 7.0.x branches) are still very buggy and unstable, causes fake regressions to be found in ReactOS. Also guest 3D acceleration for NT 5.x (and ReactOS) was cut down in VirtualBox 6.1.x and newer versions"

**Comment by ItsAndrewDev** [comment]
Thx for letting me know! I'll try it immediately.
