### ISSUE TITLE
One-Core-API not working on Windows XP x64 (AMD64)

### ISSUE THREAD

**Issue by Gravarty** [Skulltrail192/One-Core-API-Binaries#282]
I've tried to install One-Core-API on a fully updated X64 SP2 install (correct order) with all drivers correctly installed and after reboot it's stuck on the bootscreen. Then i tried to install One-Core-API on a stock install (with SP2 and only IE8 and WM11 installed) and it's still stuck on the bootscreen. While installing, it also asks to restore original system files (which i declined) and also closing system critical applications like WinLogon.exe (which obviously doesn't work). Safemode doesn't work as well. Version used: VL

I also replied to this thread, but it was closed because OP didn't reply
https://github.com/Skulltrail192/One-Core-API-Binaries/issues/258

![Screenshot_1](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/16298668/ac9d133c-619e-4e9b-94cf-d65f89e2be4a)

**Comment by Gravarty** [comment]
I've now tried the non VL version and nope, same issue. 

Specs, in case you need it:

ASUS P8H61
GTX 770
8 GB DDR3 RAM
1TB HDD

Installed using Intel's official SATA driver integrated.

**Comment by nixxoq** [comment]
Which version of OCA? Are you tried using 4.0.0 rc1 or rc2? (from One-Core-API-Canary repository)

**Comment by Gravarty** [comment]
The latest official version 3.0.5. I didn't know about the canary build, i will give this a try. Thanks!

**Comment by Gravarty** [comment]
Thanks, but unfortunately that doesn't work either. I also tried installing Windows XP in IDE mode because I suspected it might be the Intel AHCI driver that caused trouble but still bootlooping.

**Comment by jonm58** [comment]
> Thanks, but unfortunately that doesn't work as well. I also tried installing Windows XP in IDE mode because I suspected it might be the Intel AHCI driver that caused trouble but it's still stuck on the bootscreen.

1.use this windows 2003 iso
https://archive.org/download/windows-xp-2003-updated/Windows%20Server%202003%20x86%20Enterprise%20Updated%20Beta%202%2024-02-04.iso

and try:Base-> Additional Dlls -> Branding -> D3d -> App Compat

**Comment by Gravarty** [comment]
Okay, thanks! So you want me to try Server 2003 32-Bit first? My plan was to use the 64-Bit version of XP (Server 2003 NT 5.2)

**Comment by jonm58** [comment]
> Okay, thanks! So you want me to try Server 2003 32-Bit first? My plan was to use the 64-Bit version of XP (Server 2003 NT 5.2)

Oops,use this iso
https://archive.org/download/windows-xp-2003-updated/Windows%20XP%20x64%20Updated%20Beta%202%2024-02-04.iso

**Comment by Gravarty** [comment]
Okay, now it's finally working! Thanks for your help!

**Comment by jonm58** [comment]
![VMware](https://cdn.discordapp.com/attachments/1030000423282675714/1236818048825163827/unknown.png?ex=666199d1&is=66604851&hm=db96f59e35db5497c32f9603d5c165716d76b70abdf6de03f99d27d6f687eb15&)

this [2003 x64](https://archive.org/download/windows-xp-2003-updated/Windows%20XP%20x64%20Updated%20Beta%202%2024-02-04.iso) with VMware usb3.1

**Comment by Skulltrail192** [comment]
> Okay, now it's finally working! Thanks for your help!
> 
> EDIT: Okay, i think i found the issue, the bootloop is caused by the VIA USB3 drivers. The drivers work fine without OCA, but installing the USB3 drivers before or after OCA is installed, the system is then stuck on the bootscreen.

 VIA USB3 drivers are official for your motherboard or patched for XP? Because if not official, i can grant if is compatible with OCA. and OCA has driver update package what you get USB 3 support

**Comment by jonm58** [comment]
> > Okay, now it's finally working! Thanks for your help!
> > EDIT: Okay, i think i found the issue, the bootloop is caused by the VIA USB3 drivers. The drivers work fine without OCA, but installing the USB3 drivers before or after OCA is installed, the system is then stuck on the bootscreen.
> 
> VIA USB3 drivers are official for your motherboard or patched for XP? Because if not official, i can grant if is compatible with OCA. and OCA has driver update package what you get USB 3 support

VIA have official usb3 for xp

**Comment by Skulltrail192** [comment]
> > > Okay, now it's finally working! Thanks for your help!
> > > EDIT: Okay, i think i found the issue, the bootloop is caused by the VIA USB3 drivers. The drivers work fine without OCA, but installing the USB3 drivers before or after OCA is installed, the system is then stuck on the bootscreen.
> > 
> > 
> > VIA USB3 drivers are official for your motherboard or patched for XP? Because if not official, i can grant if is compatible with OCA. and OCA has driver update package what you get USB 3 support
> 
> VIA have official usb3 WHQL Driver for xp

For that motherboard or is "forced"?

**Comment by jonm58** [comment]
> Okay, now it's finally working! Thanks for your help!
> 
> EDIT: Okay, i think i found the issue, the bootloop is caused by the VIA USB3 drivers. The drivers work fine without OCA, but installing the USB3 drivers before or after OCA is installed, the system is then stuck on the bootscreen.

your PC is what name?

**Comment by jonm58** [comment]
> > > > Okay, now it's finally working! Thanks for your help!
> > > > EDIT: Okay, i think i found the issue, the bootloop is caused by the VIA USB3 drivers. The drivers work fine without OCA, but installing the USB3 drivers before or after OCA is installed, the system is then stuck on the bootscreen.
> > > 
> > > 
> > > VIA USB3 drivers are official for your motherboard or patched for XP? Because if not official, i can grant if is compatible with OCA. and OCA has driver update package what you get USB 3 support
> > 
> > 
> > VIA have official usb3 WHQL Driver for xp
> 
> For that motherboard or is "forced"?

I don't know

**Comment by Gravarty** [comment]
It's ASUS P8H61 Motherboard.

**Comment by Skulltrail192** [comment]
> I've tried to install One-Core-API on a fully updated X64 SP2 install (correct order) with all drivers correctly installed and after reboot it's stuck on the bootscreen. Then i tried to install One-Core-API on a stock install (with SP2 and only IE8 and WM11 installed) and it's still stuck on the bootscreen. While installing, it also asks to restore original system files (which i declined) and also closing system critical applications like WinLogon.exe (which obviously doesn't work). Safemode doesn't work as well. Version used: VL
> 
> I also replied to this thread, but it was closed because OP didn't reply #258
> 
> ![Screenshot_1](https://private-user-images.githubusercontent.com/16298668/336533011-ac9d133c-619e-4e9b-94cf-d65f89e2be4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTM3MTcsIm5iZiI6MTcxNzYxMzQxNywicGF0aCI6Ii8xNjI5ODY2OC8zMzY1MzMwMTEtYWM5ZDEzM2MtNjE5ZS00ZTliLTk0Y2YtZDY1Zjg5ZTJiZTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE4NTAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExM2QxMzExNTVhNDk2OTRiNDEyZWNiNTk1Mjk5YTg0ZDZmYjdiZDAzNmZjYjNkMWVmMDdiZTAwNzg5MDMzOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.05B8Dodcc-qBOElFi_QKuyGypdgzXwviBo1S-BTa2wU)

And you can try the ORIGINAL driver for your motherboard:
https://www.asus.com/me-en/supportonly/p8h61-usb3/helpdesk_download/

**Comment by Gravarty** [comment]
I always had the original drivers installed, i didn't use the drivers part of OCA, sorry for the confusion. So far everything works fine without the USB3 drivers installed.

**Comment by Skulltrail192** [comment]
So, if is working without USB3 drivers installed, it will be closed
