### ISSUE TITLE
kernelbase.dll BSoD bootloop

### ISSUE THREAD

**Issue by Inqurity** [Skulltrail192/One-Core-API-Binaries#286]
My anti-virus said something about removing some file, I believe it was C:\Windows\System32\kernelbase.dll. I didn't pay that much thought and continued using the PC, until rebooting. On the startup screen (the one with the blue bar) it flashes the blue screen for a moment and then reboots. Is there any way to restore the system by downloading the file and putting it in the right place manually? Is the file even related to the bootloop?

**Comment by Skulltrail192** [comment]
Use another antivirus.

**Comment by Inqurity** [comment]
I have turned off reboot on failure and the BSoD says this:
STOP: c0000139 {Entry Point Not Found}
The procedure entry point kernelbase.FlsSetValue could not be located in the dynamic link library Kernel32.dll
So yeah, I'll try restoring the file now. And thanks for advice. I don't even think this PC needs an AV, as it's not connected to the internet. It's an old NOD32 which the previous owner definitely didn't buy

**Comment by Inqurity** [comment]
I was also told that this machine supported booting from USB, but it.. uh... didn't. The flash drive simply didn't appear in the boot menu. Maybe you're supposed to use the mobo's ports, but those are dead. So I also had to burn a WinPE CD.

**Comment by Inqurity** [comment]
But, indeed, putting the file back into System32 fixed the issue.
![PXL_20240625_124018181](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/65112064/d50c7933-cbb2-4bc4-8fc4-7e2696fa6bce)

**Comment by Skulltrail192** [comment]
> My anti-virus said something about removing some file, I believe it was C:\Windows\System32\kernelbase.dll. I didn't pay that much thought and continued using the PC, until rebooting. On the startup screen (the one with the blue bar) it flashes the blue screen for a moment and then reboots. Is there any way to restore the system by downloading the file and putting it in the right place manually? Is the file even related to the bootloop?

What was the antivirus what you tried use?

**Comment by Inqurity** [comment]
ESET NOD32, the one in the screenshot from my last message
