### ISSUE TITLE
winsrv not found

### ISSUE THREAD

**Issue by Sheepsnoop** [Skulltrail192/One-Core-API-Binaries#29]
When using the latest X64 build I restart the pc and get bsod saying winsrv not found
I tried doing everything including replacing the dll and it doesn't change. I have done this on multiple installs including windows pro x64 and windows server x64.

**Comment by Raindirk** [comment]
Same here with both x86 and x64, not only with the latest builds. This BSOD appears after installing kernel update. Without installing kernel update it works more or less.

**Comment by Skulltrail192** [comment]
For what OS?

**Comment by Sheepsnoop** [comment]
Windows xp professional x64 and windows server 2003 x64 for me.
I have tried virtual machine and physical hardware, I have tried both OS's with full updates and no updates. It first happened to me i think about november. 

Sadly i've done research about this error and there is only a few forum posts from 2008 regarding this happening with service pack 2 or 3. Of course that's no help for this sadly haha.

**Comment by Raindirk** [comment]
Win XP SP2 and SP3 x32 in my case. Hardware installation. Funny that winsrv file is present in the system, but OS just cannot see it somewhy.

**Comment by Sheepsnoop** [comment]
"This BSOD appears after installing kernel update. Without installing kernel update it works more or less."
I've tried x64 again recently and installed service pack 2 only, then installed one core api again without the kernel update and still got this error.

Would installing the older kernel update help?

**Comment by Raindirk** [comment]
Not sure. Some time ago I tested all possible configurations of packages from last year versions up to current one - always the same result, BSOD after installing kernel update. Without kernel update installing no BSODs. And one more thing, absolutely NO system restarts between packages installation.

**Comment by Sheepsnoop** [comment]
strange... windows pro x64 with service pack 2 didn't work. But testing again just now with 03 enterprise x64 R2 in VM without updates worked for first time for me without kernel. upon restarting, everything worked so I decide to test the kernel and it works now too.

Perhaps it's the service packs or something.

**Comment by Skulltrail192** [comment]
Fixed
