### ISSUE TITLE
Base Install Not Working

### ISSUE THREAD

**Issue by PoimeYT** [Skulltrail192/One-Core-API-Binaries#293]
Hi

I am on x64 and Base Install is stuck on Installing file 1.0.6002.24064.POLICY

What do I do?
Thanks!
Poime

**Comment by Skulltrail192** [comment]
This is a know issue. Kill schtasks,exe on task manager

**Comment by PoimeYT** [comment]
There is no schtasks.exe in the task manager.

**Comment by jonm58** [comment]
> There is no schtasks.exe in the task manager.

Do you see an exe with "certupdate.exe" on tasksmgr?
Kill certupdate.exe on task manager
