### ISSUE TITLE
Installation of NVIDIA driver after installing One Core API gives a BSOD

### ISSUE THREAD

**Issue by Nickelexp** [Skulltrail192/One-Core-API-Binaries#296]
PC: real
Configuration: 
![win64_about](https://github.com/user-attachments/assets/f61d5f8f-0c39-408b-9f57-3375a31bd5a7)
also NVIDIA GeForce GTX 970
Programs installed with One Core API:
![win64_programs](https://github.com/user-attachments/assets/d25e48c1-4508-4090-ae95-ab2f63a3705c)
Version of NVIDIA Driver: 368.81(It is little modified to recognize GTX 970, but the same issue goes also with GTX 650 which is officially supported by that version of driver)
BSOD text:

STOP: c000021a {Fatal System Error}

The Session Manager Initialization system process terminated unexpectedly with a
  status of 0xc0000005 (0x00000000 0x00000000)

The system has been shut down.

Beginning dump of  physical memory

Physical memory dump complete.

Contact your system administrator or techical support group for futher assistance.

How to do the BSOD: before/after installation of "Common Order" of One Core API install NVIDIA Driver and reboot the system. If after installation of NVIDIA Driver but before the reboot restore the system to the state before NVIDIA Driver but with One Core API, there won't be a BSOD

**Comment by Skulltrail192** [comment]
This is a know issue and was fixed on 4.0.0 RC3 hotfix. See: https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/tag/4.0.0-rc3-hotfix-20240706-experimental

**Comment by Nickelexp** [comment]
Thanks,I'll try it and will send a feedback about it.

**Comment by Nickelexp** [comment]
I installed that fork and it worked with NVIDIA drivers.After installation some modern apps still give me "Error openig OpenAL device", VLC has begun to freeze the videos I'm playing, despite my attempts to fix the issue, but everything else worked fine. Thanks.
