### ISSUE TITLE
Reporting bugs

### ISSUE THREAD

**Issue by Nojus2001** [Skulltrail192/One-Core-API-Binaries#30]
Hello,

Here the bugs i have found in ONE CORE API as of now

1.The appearance tab in display propeties sample theme like luna is in spanish or espanol i dont know what language it is
2.The Security center ballon popup is missing the red shield
3.The compatibility tab is messed up
Well this my current bug reports.I hope after April 9th these bugs will be fixed.I might find new bugs too @Skulltrail192

**Comment by NEO-SPECTRUMAN** [comment]
there is some files missing in sv2003 base shell update installer
![2022-02-16_193005](https://user-images.githubusercontent.com/88002487/154321077-a3783b0f-23ed-4ced-b0a7-0e73c0c730d9.png)
they are exist in deprecated versison
![2022-02-16_193156](https://user-images.githubusercontent.com/88002487/154321488-f66b6782-45a1-46d4-9584-35fd348c8c71.png)

maybe i broke sv2003 instelled it
![2022-02-16_193420](https://user-images.githubusercontent.com/88002487/154321610-a5e0628c-d294-43c3-9fe5-92a1644d5cff.png)

**Comment by NEO-SPECTRUMAN** [comment]
im reinstall ncore (sv2003)
and tryed update OCAPI
in order
Packages\x86\Base Installer\update\update.exe
Packages\x86\App Compat Installer\update\update.exe
Packages\x86\New Dlls Installer\update\update.exe
Packages\x86\D3D Installer\update\update.exe
Packages\x86\API-SET Installer\update\update.exe

and another one sv2003 was bricked
![2022-02-17_002916](https://user-images.githubusercontent.com/88002487/154367200-d8ac5618-fe6c-43a9-b7c4-a2a5c818d444.png)

**Comment by NEO-SPECTRUMAN** [comment]
xp
![2022-02-19_001938_](https://user-images.githubusercontent.com/88002487/154776761-febea608-848b-4581-95c7-59fbece92608.png)

**Comment by NEO-SPECTRUMAN** [comment]
nope
2.2.1 doesn't works too (on ncore)
safe mode also not works
![Uploading 2022-02-21_220738.png…]()

**Comment by Skulltrail192** [comment]
What is ncore? I installed all packages on Server 2003 with updates and works fine, including Safe Mode. Base Shell Installer is experimental and incomplete, not install for now.

**Comment by NEO-SPECTRUMAN** [comment]
https://disk.yandex.com/d/T9EFk045tHHYTg
https://vk.com/lwgame_ncore

**Comment by Skulltrail192** [comment]
I downloaded the iso and installed. I installed Base and it's works fine. On Vmware, version 12. Do you installed on Virtual machine or real computer?

**Comment by NEO-SPECTRUMAN** [comment]
i tryed 2.5.0 or 2.4.0
and there is no BSOD
but it works worse than on xp sp3
(black squares on buttons etc)

**Comment by Skulltrail192** [comment]
What is black squares on buttons?

**Comment by NEO-SPECTRUMAN** [comment]
i don't screenshot it
i tryed it on Virtualbox
and now i delete it already

i will make some screenshots if i check it again

**Comment by Skulltrail192** [comment]
Well, since the issue not showed, will be closed.
