### ISSUE TITLE
Video signal broken on XP SP2 X64 running on QEMU KVM using libvirt.

### ISSUE THREAD

**Issue by lukes07xd** [Skulltrail192/One-Core-API-Binaries#306]
After installing base package. The display is completely glitched. On startup, the loading screen still shows, but when it should show the welcome message, it glitches out.
![image](https://github.com/user-attachments/assets/9a104bd6-ed5e-4b46-9e15-732072dc88e2)

**Comment by lukes07xd** [comment]
+ also just now tested the latest canary build V4.0.0 and it's the same

**Comment by lukes07xd** [comment]
If it helps, the VM has these specs:
8 vCPUs i5-9300H
4GB RAM
40GB IDE storage (saved in qcow2 format)
Video output VirtIO, i tried VGA too, but still nothing.
Sound AC97, still works.

**Comment by ernierasta** [comment]
I have the same setup and WinXP 64-bit version and I can confirm, that I have the same problem. 
No problem with WinXP Pro sp3 32-bit.

**Comment by ernierasta** [comment]
Hi just ping back. I had been able to workaround problem.

I am not sure if updating system was necessary, but I updated everything using legacyupdate.net.

Then installed spice tools from:
https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.132-1/
qlx and guest-agent (this probably doesn't matter).

Most important part is: enable xml editing in virt-manager and than change video section to:
```
<video>
  <model type="cirrus" vram="65536" heads="1" primary="yes"/>
  <alias name="video0"/>
  <address type="pci" domain="0x0000" bus="0x00" slot="0x02" function="0x0"/>
</video>
```
Maybe, that changing video to cirrus is the only thing you need to do. Cirrus is quite limiting and I wonder if we can change it to something else later, but it works - that is most important.

Idea to change it to cirrus is not mine, I found tip for qemu on discord.

**Comment by lukes07xd** [comment]
@ernierasta Thanks, this works without a problem! :D
