### ISSUE TITLE
MCCToolChestPE doesnt work

### ISSUE THREAD

**Issue by Max-RM** [Skulltrail192/One-Core-API-Binaries#311]
This program doesnt work in Windows XP with OneCoreAPI and in any version of wine too.

[MCC Tool Chest PE.zip](https://github.com/user-attachments/files/17347154/MCC.Tool.Chest.PE.zip)

**Comment by Max-RM** [comment]
> What exactly is the error here. This? ![image](https://private-user-images.githubusercontent.com/36737188/375948961-68234da9-0706-410e-93db-31839874abd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MzU1ODgsIm5iZiI6MTcyODczNTI4OCwicGF0aCI6Ii8zNjczNzE4OC8zNzU5NDg5NjEtNjgyMzRkYTktMDcwNi00MTBlLTkzZGItMzE4Mzk4NzRhYmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDEyMTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwM2ZiNjM5OGNmNTdiM2JlYzVmYjE2MzUyNmIxYmU2MTUwNjE0MDI2NTU0MWRkYjMyMjZjNjVkMTBlMDA0ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WG17vhlctJKvr_a7jTGWVj7MRw-rvQt2r2z0HlV8A1Y)

Why it worked for you?

**Comment by jonm58** [comment]
MCCToolChestPE using VS 2015 C++ Runtime,so your vs2015 Runtime is what version？

**Comment by Max-RM** [comment]
> MCCToolChestPE using VS 2015 C++ Runtime,so your vs2015 Runtime is what version？

Yea I know about this problem that this app requred this version of VCedist but didnt ask to install in while first launch.
It was installed in my VM.

Idk maybe after 4 montch OCAPI was updated and now MCCToolChestPE start working.

**Comment by Max-RM** [comment]
> Try to update the VS2015 runtime to the latest VS 2022 runtime and see if that helps. That helped with atleast one application [Dolphin] before.
> 
> You can enable debugging info for this application by changing byte 0xDC from 02 to 03, then running the application in cmd.exe. It should log any .NET exceptions that can be used to solve this problem.

I will try later.

**Comment by Max-RM** [comment]
> Try to update the VS2015 runtime to the latest VS 2022 runtime and see if that helps. That helped with atleast one application [Dolphin] before.
> 
> You can enable debugging info for this application by changing byte 0xDC from 02 to 03, then running the application in cmd.exe. It should log any .NET exceptions that can be used to solve this problem.

![image](https://github.com/user-attachments/assets/bacadf13-3972-41ed-9edc-2138c45bde1a)
Even with enabling console on background doesnt shows anything.

**Comment by Max-RM** [comment]
> 0xC0000135 indicates a missing DLL. This application is powered by .NET Framework. Is the .NET Framework installed correctly in your VM?
Sorry
I forgot this time.

I think need to install 4.8

**Comment by Max-RM** [comment]
> 0xC0000135 indicates a missing DLL. This application is powered by .NET Framework. Is the .NET Framework installed correctly in your VM?

I cant install NET framework. No error windows, just doest start at all

**Comment by Max-RM** [comment]
> 4.5

![image](https://github.com/user-attachments/assets/03ac3fc2-a6fd-4fa7-9bff-d22e2d451372)


And what then?
I cant install NET 4.5 on it

**Comment by Max-RM** [comment]
> Set compatibility mode to Windows 7 and it should let you through.

Already tried it. Still same error.

**Comment by Max-RM** [comment]
> ".NET Framework 4.5 is not supported by this operating system." The next option is to use an unofficial installer to install .NET 4.8 instead. You should follow [this](https://github.com/Abdelrhman-AK/WinPaletter/wiki/Build-.NET-Framework-4.8-for-legacy-operation-systems-(Windows-XP,-Vista)) guide to create the unofficial installer.
> 
> This should install .NET Framework 4.8 and strip out all the system requirement checks.

What installer was used in your OS?
This unofficial installer?

**Comment by Max-RM** [comment]
> I used that installer to install .NET 4.8, there is a issue in the official installers where it simply crashes seconds after clicking Install. You should try the guide linked above and report back.

Can you just send your precompilled installer here?

**Comment by Max-RM** [comment]
> I used that installer to install .NET 4.8, there is a issue in the official installers where it simply crashes seconds after clicking Install. You should try the guide linked above and report back.

Thx now it worked. I hope will work in Wine too.
