### ISSUE TITLE
The 4.0.0 pre-RTM causes Windows XP crash on VirtualBox 7.1.2

### ISSUE THREAD

**Issue by sal-ammoniac** [Skulltrail192/One-Core-API-Binaries#315]
Issue: After installed, start screen crashes and explorer will not be able to start.
[WinXP-screen0.webm](https://github.com/user-attachments/assets/0a1daf6f-e036-4643-b861-50c2bc6e75f1)
Also, SFC occurs during installation.
![屏幕截图 2024-11-08 120932](https://github.com/user-attachments/assets/fae005d6-33e3-40b3-849b-26404af24e1e)

VM configuration: 4096MB RAM,4 cores PIIX3 chipset and 128MB VRAM for VBoxVGA

Windows XP SP3 Chinese edition was used for testing

**Comment by Skulltrail192** [comment]
What iso used?

**Comment by sal-ammoniac** [comment]
> What is the iso used? Please give the download link

just plain Windows XP SP3 Pro VL：
zh-hans_windows_xp_professional_with_service_pack_3_x86_cd_vl_x14-74070.iso

**Comment by jonm58** [comment]
https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/tag/4.0.0-pre-rtm-hotfix-20241109-experimental

**Comment by sal-ammoniac** [comment]
> https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/tag/4.0.0-pre-rtm-hotfix-20241109-experimental

OK,fixed. Thanks
