### ISSUE TITLE
No Network

### ISSUE THREAD

**Issue by rxwerx1** [Skulltrail192/One-Core-API-Binaries#316]
After Installing One-Core-Api 4.0.0 Pre-RTM or something like that it broke internet i can ping 8.8.8.8 but cant google.com and cant visit any webpages.No matter the browsers or any other things. I installed this on VMware Workstation Pro 17.6.0.And now i don't know what do to to fix the internet
https://github.com/user-attachments/assets/0d52f529-ba02-4bb1-8e1e-acfe085a9316
Here's the screenshot.I hope it would be fixed before OCAPI 4.0.0 realeases or give any sort of way to fix this

**Comment by Skulltrail192** [comment]
What ISO used?

**Comment by rxwerx1** [comment]
> What is the ISO used?

I used the Poland version of Windows XP Service Pack 3 without any updates internet worked but after installing OCAPI it broke
I will try the 4.0.0 pre-rtm patch and if this would not work I will inform you

**Comment by jonm58** [comment]
![1](https://cdn.discordapp.com/attachments/1304562971233489016/1304562971451719732/image.png?ex=67332432&is=6731d2b2&hm=cb05ad5a86c996fcfce7ae699c746431c266c2fa1616b4c1fe4aeb675c107df8&)

**Comment by rxwerx1** [comment]
> Try the hotfix release [4.0.0-pre-rtm-hotfix-20241109-experimental](https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/tag/4.0.0-pre-rtm-hotfix-20241109-experimental) which should have a fix for no internet connection.
> 
> If this still isn't fixed, post a link to the ISO you used to install XP in your VM - issues do happen on one ISO but not another

It worked thanks

**Comment by Skulltrail192** [comment]
Since fixed the issue, that will be closed
