### ISSUE TITLE
Missing vtdll.dll functions.

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [Skulltrail192/One-Core-API-Binaries#34]
Installing the newer base from 2018 on Shorthorn 5219 results in a broken Windows install (vtdll.dll is different enough that it breaks winlogon.exe). In order to update WineD3D to fix the card games, the newer base needs to be installed.

**Comment by Skulltrail192** [comment]
Hello friend. Well, interfaces packs use a different patch requiring decrepated dlls. I will update all interfaces to be compatbile with One-Core-API. Be patient.
