### ISSUE TITLE
Slipstreaming this with nLite?

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [Skulltrail192/One-Core-API-Binaries#36]
I'm wanting to make a slipstreamed image with the API installed, but the problem is that nLite refuses to do this.

is SFXCAB EXE binaries the problem here? Thanks!

**Comment by Skulltrail192** [comment]
Maybe. I not use microsoft version of sfxcab, i use a custom version called "SFXCAB Substitute (version 9,1)"

**Comment by Skulltrail192** [comment]
However, i will test. And, i have plans to use Official Microsoft version.

**Comment by Skulltrail192** [comment]
Since One-core-API not uses common SFX from Microsoft, this issue will be close.
