### ISSUE TITLE
Issues on Windows XP SP2 x64

### ISSUE THREAD

**Issue by evilpro** [Skulltrail192/One-Core-API-Binaries#4]
I just tried the release from 12/28/17 on a clean install of Windows XP SP2 64 Bit.

- Running update\update.exe for the Kernel Installer throws "KB293802 installation did not complete"
- The other packages installed, however, after a reboot the system throws a BSOD

`[KB2393802.log]`
`0.172: ==============================================================`
`0.172: 2018/01/02 03:34:55.739 (local)`
`0.172: C:\Documents and Settings\Administrator\Desktop\One-Core-API-Binaries`
`master\Packages\x64\kernel Installer\update\update.exe (version 6.3.15.0)`
`0.172: Hotfix started with following command line: `
`0.172: GetKernelType: GetInternalFilename failed`
`0.172: In Function GetReleaseSet, line 1193, RegQueryValueEx failed with error 0x2`
`0.250:   1274 CheckSystem: Failed to get product build type.`
`0.250: DoInstallation: CheckSystem Failed: 0xf117 `
`0.281: KB2393802 installation did not complete.`
`2.828: Message displayed to the user: KB2393802 installation did not complete.`
`2.828: User Input: OK`
`2.828: Update.exe extended error code = 0xf117`
`2.828: Update.exe return code was masked to 0x643 for MSI custom action compliance.`

**Comment by Skulltrail192** [comment]
Please retest

**Comment by SSJ9899TDylan** [comment]
This is why you should fully update your system to its end of life before testing those packages

**Comment by ManoaNosea** [comment]
I wanne say thank you, this project allow me to run windows 7 games on XPx64 such as Project CARS :) and the performance is not bad at all: I measured no change in framerate between windows 7 and XP x64 using WineD3D 3.14 but noticed a big improvement in response times.

I have one littel problem: killing floor 2 gets stuck when loading and it's using 100% cpu, from the thread list inside process explorer in the stack list it looks like it's stuck inside ntdll.dll
