### ISSUE TITLE
Chrome doesn't seem to work

### ISSUE THREAD

**Issue by v3core** [Skulltrail192/One-Core-API-Binaries#40]
hi, chrome doesn't seem to work on neither x64 xp or x86 (both versions of chrome tried too), I tried chrome 55, 56, 57, 58, 59, 60 x64 and x86 and none of them work, chrome 55 tries to launch but closes without any error, and rest error 0xc0000005 (x86) and The procedury entry Wow64GetThreadContext...
is there any way to get chrome 56 or newer working?

**Comment by Skulltrail192** [comment]
Hey, how you discovered what the problem is on Wow64GetThreadContext? I will review this function, i already noticed that this problem occurred

**Comment by v3core** [comment]
hi, i actually have a very limited knowledge of how windows stuff work, but the error it throws on xp64 mentions Wow64GetThreadContext specifically

**Comment by Skulltrail192** [comment]
Test again, please

**Comment by Skulltrail192** [comment]
Well, i tested chrome 32 bits until version 57-60 and works on XP x64. Chrome x64 also works on XP x64 at latest version. So, this issue will be closed.
