### ISSUE TITLE
0xDEADBEEF bsod

### ISSUE THREAD

**Issue by cesar300** [Skulltrail192/One-Core-API-Binaries#42]
I have installed this on a Windows XP virtual machine with vmware and after install the base package and reboot I got those bsod.
I used an iso with the patches of integral edition with and without kernel patch. I need these mods for future testing on real hardware.

**Comment by Skulltrail192** [comment]
Hey, can you send to Shorthorn Project e-mail the iso used on this installation? E-mail: shorthornproject@outlook.com

**Comment by cesar300** [comment]
File is too large (660 MB) to send via attachment. Instead I'll send a google drive download link.
Thanks

**Comment by cesar300** [comment]
The new version 2.2 is still throwing this BSOD.

**Comment by Skulltrail192** [comment]
This issue was fixed?

**Comment by cesar300** [comment]
Unfortunately not yet.

**Comment by Skulltrail192** [comment]
So, please, send here the link of google drive to download

**Comment by Skulltrail192** [comment]
And tell me about environment:
- Vmware specs used;
- Windows XP version used: has updates installed? Is vanilla?

**Comment by cesar300** [comment]
https://drive.google.com/file/d/14hByqsxhvxUkkJseLBXDMdZMhPscs88q/view?usp=sharing
VMware 16.2.3
Windows XP Pro SP3 Spanish with the following fixes from integral edition:
- Generic SATA AHCI driver
- USB 3.x xhci generic driver
- ACPI patch
- PAE 4GB ram patch
- Kernel mode driver framework 1.11
- Live USB setup

**Comment by cesar300** [comment]
> Are you installed with USB 3.0 and AHCI options on Vmware?

Don't mind in Vmware but in real hardware I need those fixes

**Comment by posreadyxp** [comment]
Same this BSoD. I tried to install XP (on modern hardware with NVMe (Samsung drivers), SATA drivers, USB 3.x support, ACPI, PAE 128 GB, Kernel Mode driver framework 1.11) and got error now

**Comment by Skulltrail192** [comment]
Well, the issue is produced by ntoskrnl_emu. It uses a tecnhique to find a address of some functions using hex address. The problem is: the kernel of One-Core-API is a custom kernel, so, the address are differents. I think ntoskrnl_emu is completly imcompatible with one-core-api. And, all functions implemented on ntoskrnl_emu is implemented on One-Core-API kernel. the way is replace references of ntoskrn_emu on driver with ntoskrnl original.

**Comment by JakoDel** [comment]
> Well, the issue is produced by ntoskrnl_emu. It uses a tecnhique to find a address of some functions using hex address. The problem is: the kernel of One-Core-API is a custom kernel, so, the address are differents. I think ntoskrnl_emu is completly imcompatible with one-core-api. And, all functions implemented on ntoskrnl_emu is implemented on One-Core-API kernel. the way is replace references of ntoskrn_emu on driver with ntoskrnl original.

will you ever work on a fix (if there is one) for this issue? I got XP fully working on my new coffee lake system but it's quite useless without your amazing piece of software :/

**Comment by Skulltrail192** [comment]
Yes, i'm working a workaround to fix it. I will release a custom version of ntoskrnl_emu.

**Comment by Skulltrail192** [comment]
Hello, i made a special version of Ntoskrnl_emu and it's working on XP/Server 2003 and XP x64. On end-of-month i will release new version.

**Comment by posreadyxp** [comment]
> Hello, i made a special version of Ntoskrnl_emu and it's working on XP/Server 2003 and XP x64. On end-of-month i will release new version.

That's cool, i'm wait Your release =)

**Comment by JakoDel** [comment]
> Hello, i made a special version of Ntoskrnl_emu and it's working on XP/Server 2003 and XP x64. On end-of-month i will release new version.

thanks a lot!

**Comment by Skulltrail192** [comment]
Fixed on version 2.9. Close this issue.
