### ISSUE TITLE
Issue On Winrar And CFF Explorer After Install One Core API Binaries V2.1 Without Install one-core-api-app-kernel-alone

### ISSUE THREAD

**Issue by MWF2** [Skulltrail192/One-Core-API-Binaries#43]
Hey, i'm new here but anyways, there issue on winrar and cff explorer after install one core api binaries v2.1 except one-core-api-app-kernel-alone, due ik that will be appear bsod after install everything, it appear error on winrar after that, even cff explorer too like gdi32.dll idk what is talking about, what did i install wrong or there way to fix the issue?, even i using virtual machine and os is Windows XP Professional SP3 x86 - Integral Edition 2021.5.15 ![error winrar](https://user-images.githubusercontent.com/74994144/140992876-de708ee5-4f0e-4f6b-9a27-1f41b2cf9190.PNG)

**Comment by mina354** [comment]
In which order did you install the binaries?

**Comment by r3muxd** [comment]
i also have this problem

**Comment by Skulltrail192** [comment]
Thank you, i will see and fixe it. I see what Windows XP doesn't have this function, need be implement on gdi32.dll
