### ISSUE TITLE
rust 1.50, cargo.exe can't run, kernel32.dll error

### ISSUE THREAD

**Issue by jelly2512** [Skulltrail192/One-Core-API-Binaries#44]
install all of one-core-API-Binaries, rustc and rustdoc can run ,but cargo.exe can't run
![cargo](https://user-images.githubusercontent.com/96339691/146641580-baca377b-1e86-4157-ad5c-651e80625fa9.png)

**Comment by Skulltrail192** [comment]
I will this function.
