### ISSUE TITLE
Base installer breaks internet options

### ISSUE THREAD

**Issue by K4sum1** [Skulltrail192/One-Core-API-Binaries#45]
This is on XP x86, NT 5.1
![broken-internet-options](https://user-images.githubusercontent.com/77039240/149232776-613ed7d7-e34e-4cc0-9dbe-d28884686195.png)

**Comment by Skulltrail192** [comment]
What IE version?

**Comment by NEO-SPECTRUMAN** [comment]
one of previous versions breaks it on not original xp/sv2k3 builds
last 2.3.0 not breaking  it on original en XP

**Comment by Skulltrail192** [comment]
Well, i see it break on XP, on Server 2003 keep working fine. I will see on Xp

**Comment by K4sum1** [comment]
> What IE version?

8, I had to access the settings to change TLS settings since I installed the TLS 1.2 update. Ended up uninstalling OCA and then reinstalling it at the time.

**Comment by jonm58** [comment]
Open Internet Options from Security Center

**Comment by Skulltrail192** [comment]
Now, i discovered the reason what it's happens. Fix on next release, on friday (1 jully).

**Comment by Skulltrail192** [comment]
Fixed on version 2.6.0, so, close this issue.
