### ISSUE TITLE
Black screen after installing One Core API Base on Windows XP Professional SP3 (x86)

### ISSUE THREAD

**Issue by EgorKuzevanov** [Skulltrail192/One-Core-API-Binaries#47]
After installing One Core API Base on Windows XP Professional SP3 (x86), the system stopped starting even in safe mode. A black screen appears without a mouse cursor. Before the appearance of the boot screen with the Windows XP logo and Microsoft copyright, it does not come. The problem occurs on both Russian and English versions of Windows XP SP3. Systems installed from original MSDN ISO images.

Tested on the following virtual machines: Microsoft Virtual PC 2007 SP1, VirtualBox 6.0.24, VMware Workstation 15.5.6. My host system is Windows 7 Ultimate SP1 (x64).

Dear One Core API developers, are you going to fix this bug that prevents Windows XP from starting even in safe mode?

**Comment by NEO-SPECTRUMAN** [comment]
нужно заводить список сборок на которые можно безопаасно установить ocapi
