### ISSUE TITLE
DLL missing entry points/procedures list

### ISSUE THREAD

**Issue by NEO-SPECTRUMAN** [Skulltrail192/One-Core-API-Binaries#48]
OCAPI 2.2.1
![2022-02-19_002250](https://user-images.githubusercontent.com/88002487/154776892-0c3dccb1-87cd-4041-8be3-619c234b429a.png)
![2022-02-19_002434](https://user-images.githubusercontent.com/88002487/154776896-34ce360e-a015-41dc-ae8d-ad798d37efa4.png)

**Comment by Skulltrail192** [comment]
For Palemoon, you just need delete api-ms-win-core-memory-l1-1-0.dll from Palemmon folder and install api-set package.

**Comment by Skulltrail192** [comment]
The way to solve Palemon will be described on readme and the isue with oleacc.dll was fixed. So, this issue will be closed.

**Comment by NEO-SPECTRUMAN** [comment]
> Well, i tested the application and open and close instatlly. It seem Directx Problem (dx11).

not it shows
![2022-07-06_005501](https://user-images.githubusercontent.com/88002487/177423263-91dcd16f-0ed6-45f4-9454-401413968a30.png)

**Comment by Skulltrail192** [comment]
Are you installed on VirtualBox? If yes, virtual box with virtualbox tools with 3d options install a custom wined3d dll. Check if wined3d.dll is same present on One-core-API d3d runtime.

**Comment by NEO-SPECTRUMAN** [comment]
oh
i install virtualbox wined3d after 2.6.0

**Comment by NEO-SPECTRUMAN** [comment]
ok
now it crashes as always
