### ISSUE TITLE
Issue with Windows XP SP3 (x86) on VirtualBox 6.0.24 without enabling I/O APIC

### ISSUE THREAD

**Issue by EgorKuzevanov** [Skulltrail192/One-Core-API-Binaries#49]
After installing One Core API 2.2.1, Windows XP SP3 (x86) stopped starting even in safe mode. After restarting the virtual machine, a black screen appears without a mouse cursor.
But if you enable the "Enable I/O APIC" option in the settings of the VirtualBox virtual machine with Windows XP installed, then Windows returns its booting.
Dear One Core API developer, are you going to fix the bug with killing Windows XP SP3 in a VirtualBox virtual machine without enabling I/O APIC?

**Comment by NEO-SPECTRUMAN** [comment]
did you RTFM?
![2022-02-22_185944](https://user-images.githubusercontent.com/88002487/155179357-f51fd569-454f-4874-8dcb-9a909eaec9e2.png)

**Comment by NEO-SPECTRUMAN** [comment]
i have not XP that would work without i/o apic in virtualbox

**Comment by EgorKuzevanov** [comment]
Why hasn't Skulltrail192 fixed this bug for the third month?

**Comment by NEO-SPECTRUMAN** [comment]
why Skulltrail192 must do something for virtualbox?

**Comment by mina354** [comment]
I'm facing same issue, except that my main OS is Windows 11, VirtualBox version 6.1.32.

**Comment by Skulltrail192** [comment]
The question is: Windows XP without One-Core-API run fine without that option enabled?

**Comment by mina354** [comment]
@Skulltrail192 Yes, of course it runs fine.
> The question is: Windows XP without One-Core-API run fine without that option enabled?

**Comment by Skulltrail192** [comment]
This is a known limitation of Base Update, because i only found a way for now to copy uni/multiprocessor hal, i chose ACPI APIC version. I'm searching a way to copy each hal for certain architecture.

**Comment by TBRHS** [comment]
> After installing One Core API 2.2.1, Windows XP SP3 (x86) stopped starting even in safe mode. After restarting the virtual machine, a black screen appears without a mouse cursor. But if you enable the "Enable I/O APIC" option in the settings of the VirtualBox virtual machine with Windows XP installed, then Windows returns its booting. Dear One Core API developer, are you going to fix the bug with killing Windows XP SP3 in a VirtualBox virtual machine without enabling I/O APIC?

Couldn't move my mouse pointer

**Comment by Skulltrail192** [comment]
Are you enabled APIC mode?

**Comment by Skulltrail192** [comment]
> Are you enabled APIC mode?
Enable APIC mode before Install Windows. When you change Hal, all hardware are reinstalled. Mouse PS2 is not recognized correctly.

**Comment by Skulltrail192** [comment]
The issue what Windows XP not boot up on Virtual box are solved and will be avaliable on next release. However, as commented, Mouse pointer not working with virtual box tools installed. It is by investigation.

**Comment by TBRHS** [comment]
> The issue what Windows XP not boot up on Virtual box are solved and will be avaliable on next release. However, as commented, Mouse pointer not working with virtual box tools installed. It is by investigation.

SO THAT MEANS I HAVE TO TAKE OFF THE VIRTUALBOX GUEST ADDITIONS AND RESTART

**Comment by TBRHS** [comment]
> The issue what Windows XP not boot up on Virtual box are solved and will be avaliable on next release. However, as commented, Mouse pointer not working with virtual box tools installed. It is by investigation.

HOW AM I SUPPOSED TO GET MYPAL

**Comment by Smu1zel** [comment]
> > The issue what Windows XP not boot up on Virtual box are solved and will be avaliable on next release. However, as commented, Mouse pointer not working with virtual box tools installed. It is by investigation.
> 
> SO THAT MEANS I HAVE TO TAKE OFF THE VIRTUALBOX GUEST ADDITIONS AND RESTART

Try safe mode and uninstall the Guest Additions, if that doesn't work, delete the guest additions mouse driver or try switching to a emulated PS/2 mouse in VBox settings (believe that's an option).

Also, why all caps? This is software based on a OS (ReactOS) that is notorious for being unstable. You can't really perfect something like this with a base that isn't perfect at all. You are warned in the installer before the installation starts. Not saying you're ungrateful or anything, just don't expect stability from something that doesn't even have a good starting point to begin with.

**Comment by Skulltrail192** [comment]
The issue related with mouse not working with virtual box guest additions is solved and will be avaliable on end-of-month release.

**Comment by TBRHS** [comment]
> > > The issue what Windows XP not boot up on Virtual box are solved and will be avaliable on next release. However, as commented, Mouse pointer not working with virtual box tools installed. It is by investigation.
> > 
> > 
> > SO THAT MEANS I HAVE TO TAKE OFF THE VIRTUALBOX GUEST ADDITIONS AND RESTART
> 
> Try safe mode and uninstall the Guest Additions, if that doesn't work, delete the guest additions mouse driver or try switching to a emulated PS/2 mouse in VBox settings (believe that's an option).
> 
> Also, why all caps? This is software based on a OS (ReactOS) that is notorious for being unstable. You can't really perfect something like this with a base that isn't perfect at all. You are warned in the installer before the installation starts. Not saying you're ungrateful or anything, just don't expect stability from something that doesn't even have a good starting point to begin with.

HAVE NO IDEA HOW TO SELECT THE ITEMS IN THE HARDDRIVE

**Comment by Skulltrail192** [comment]
You can navigate using keyboard

**Comment by Skulltrail192** [comment]
Now solved on version 2.10.0.
