### ISSUE TITLE
Issues with Kernel Installer on XP x86

### ISSUE THREAD

**Issue by SSJ9899TDylan** [Skulltrail192/One-Core-API-Binaries#5]
When I use the Kernel Installer, it actually corrupts the logon screen. Also, when I had the logon box, it instantly shut down Windows XP. Can you please fix this?
P.S ALL of the other installers work for me & I was able to install:
Firefox 57.0.4
After that, when I tried to use it, it encountered an error. Also, when are you going to release the One Core API?
Note that it has better performance after you update Windows XP/Server 2003 to it's end of life.

**Comment by SSJ9899TDylan** [comment]
Could you please add the Windows Modules Installer Service to the One Core API? That's required for .NET Framework 4.5.

**Comment by SSJ9899TDylan** [comment]
Will I be able to use 100% of the applications that Windows 7 can run if it works?

**Comment by SSJ9899TDylan** [comment]
Now the Base Installer has crashed on me.

**Comment by Skulltrail192** [comment]
I think it is solved
