### ISSUE TITLE
Chromium with DirectWrite?

### ISSUE THREAD

**Issue by v3core** [Skulltrail192/One-Core-API-Binaries#51]
Hi, some time ago you have shown chromium and electron-based program (vscode) running on your win xp vm with ocapi, but trying the latest release with chrome or chromium 53 or newer does not seem to work, is there a specific version of chrome that has to be used? This is the screenshots im talking about https://www.betaarchive.com/imageupload/2018-05/1525922817.or.46143.png

**Comment by Skulltrail192** [comment]
Hey, to get Chromium 51+ on XP-2003 (working version until 57), you need add parameter "--no-sandbox" on shortcut and set compatibility of execuable to Windows Vista SP2 or Windows 7 SP1 (installing App Compat)

**Comment by mina354** [comment]
So I guess the list which says Chrome can be run up to version 60 is wrong, or it's not?

**Comment by Skulltrail192** [comment]
With version 2.2.1, no. I will create a new version what we can use Chrome 60+, until 100.

**Comment by mina354** [comment]
> With version 2.2.1, no. I will create a new version what we can use _Chrome 60+, until 100._
That's gonna rock! Can't wait to see this!

**Comment by Skulltrail192** [comment]
> Hey, to get Chromium 51+ on XP-2003 (working version until 57), you need add parameter "--no-sandbox" on shortcut and set compatibility of execuable to Windows Vista SP2 or Windows 7 SP1 (installing App Compat)

And now, you don't need set compatibility no more, only need add "--no-sandbox". Maybe on nexts releases we will don't must include this parameter

**Comment by Skulltrail192** [comment]
Chromium work WineD3D DirectWrite, so, i will close this issue.
