### ISSUE TITLE
Standalone release (not as update, but already patched dll's)

### ISSUE THREAD

**Issue by Himmler** [Skulltrail192/One-Core-API-Binaries#52]
Please, make a standalone package release.
I mean pack with ready-to-use dll's, not windows update deltapatches.

**Comment by NEO-SPECTRUMAN** [comment]
for patching software without ocapi installing?

**Comment by Himmler** [comment]
Yes, it's for replacing dlls in software directory, not in system directory.
For example, there is no bcrypt.dll in Windows XP at all, so i can just place it from OCAPI release near my software executable. Also, if it needs some NT6+ API in kernel32.dll (for example), i can just use OCAPI renamed kernel32.dll and patch executable for importing kernel3x.dll (OCAPI renamed kernel32.dll). And i don't need to patch all system dll's.

**Comment by NEO-SPECTRUMAN** [comment]
i think you can download all "binaries" repo
with all dll-s without installer
https://github.com/Skulltrail192/One-Core-API-Binaries/tree/master/Packages/x86/D3D Installer

**Comment by Himmler** [comment]
Looks like this repo doesn't updated so well as main repo. Some dlls was builded years ago, but last main release was 2 month ago.

**Comment by mina354** [comment]
Why'd you want to do this anyway? It's gonna be hard as you will have to configure EVERY incompatible software to work with windows xp. The package is also made in a Windows Update Deltapatch to prevent Windows's SFC from replacing them with original files.

**Comment by Himmler** [comment]
Patching incompatible software binary is pretty easy - it's just a script for replacing every "kernel32.dll" string to "kernel33.dll" (which is renamed OCAPI dll) for example.
So, if you try to run any incompatible software and it can't find some function in default system dlls - just run corresponding script for it (kernel32_patch.script, user32_patch.script ets.).
Most  incompatible software needs just 2-3 dlls to be replaced. Not all system dlls.

**Comment by Skulltrail192** [comment]
Due already exists folders with unpacked hotfix/installer, this issue will be close.
