### ISSUE TITLE
Fix dxdiag.exe

### ISSUE THREAD

**Issue by jonm58** [Skulltrail192/One-Core-API-Binaries#56]
![Windows XP Professional-2022-05-20-22-23-57](https://user-images.githubusercontent.com/73036321/169548881-8702466f-7909-480c-bcdc-2d59e4853449.png)
![Windows XP Professional-2022-05-20-22-21-02](https://user-images.githubusercontent.com/73036321/169548972-01b75bd0-c783-4eaa-8d17-0d9aaf1ad363.png)
Windows XP SP3 X86
Base Installer -> New Installer (Additional Dlls) -> D3d Installer -> API-SET installer -> App Compat

**Comment by NEO-SPECTRUMAN** [comment]
i have run it in virtualbox
![2022-05-20_182718](https://user-images.githubusercontent.com/88002487/169561418-24d607b5-e978-4de3-bd4a-0c80fcd0a1d1.png)

**Comment by jonm58** [comment]
@NEO-SPECTRUMAN With VMware, the hardware compatibility is 6.5-7.x, and the inability to use dxdiag looks like a unique bug for VMware？
