### ISSUE TITLE
Chrome 101 Windows XP 32 Bit

### ISSUE THREAD

**Issue by ghost** [Skulltrail192/One-Core-API-Binaries#57]
Hey. I installed the latest One Core Api on Windows XP Professional SP3 x86 - Integral Edition 2021.12.19 (Vanilla).iso and trying to fire up Chroma but I have this problem.
![untitled](https://user-images.githubusercontent.com/100865716/169572871-4df47f0d-6542-4922-9494-ce25aff948cc.PNG)

**Comment by NEO-SPECTRUMAN** [comment]
how you do this?
i tried it
but online\offline installers skip installation with error

**Comment by mina354** [comment]
Chrome 100 doesn't work for me. If I run it without setting executable to Vista SP2 compatibility mode and no --no-sandbox parameter set on the shortcut, it gives this error.
![image](https://user-images.githubusercontent.com/87821255/169578545-4f71d582-f127-4922-bc9d-ac5a0d27adae.png)
But, if I do both, Chrome 100 crashes.
![image](https://user-images.githubusercontent.com/87821255/169579128-df6d271d-3f8c-4013-8075-32f4acf5940b.png)
@Skulltrail192 could you take a look at this issue?

**Comment by mina354** [comment]
> how you do this? 
i tried it 
but online\offline\ fckn installers skip installation with error

I know of a way to install latest Chrome on XP. If there's demand, I can tell instructions on how to install newer Chrome versions on XP.

**Comment by rounk-ctrl** [comment]
> > how you do this?
> > i tried it
> > but online\offline\ fckn installers skip installation with error
> 
> I know of a way to install latest Chrome on XP. If there's demand, I can tell instructions on how to install newer Chrome versions on XP.

please tell

**Comment by mina354** [comment]
Ok, so people are asking for instructions. Here it is.
Let's give an example and say that you want to install Chrome 70 on XP. Here's how:
1- If you own a system/VM that has an OS that still supports Chrome (Win7 and later), install Chrome 70 there.
32-bit: https://www.filepuma.com/download/google_chrome_32bit_70.0.3538.110-20750/
64-bit: https://www.filepuma.com/download/google_chrome_64bit_70.0.3538.110-20751/
2- After installation is done, go to Chrome's installation folder by right-clicking on Chrome's desktop shortcut and selecting "Open file location".
3- Inside Chrome's installation folder, you will see a folder that represents the version of Chrome you have installed. Open that folder, and inside that, you will see another folder named Installer. Go to that folder.
4- Now, follow this:
If the OS that still supports Chrome (Win7 and later) is in a real hardware, get an external storage, copy chrome.7z from the Installer folder, and paste it there. Then, connect the external storage to your XP real hardware, and put it on the desktop.
If the OS that still supports Chrome (Win7 and later) is in a VM, drag chrome.7z from the Installer folder, and drop it to your main system. Then, drop it to your XP VM on the desktop.
5- Install Chrome 49 on XP.
6- After Chrome 49 installation is done, right click on Chrome's desktop shortcut and select "Open file location" to go to Chrome's installation folder, then open the folder named 49.0.2623.112, and open the folder called Installer. Replace the chrome.7z file with the file you've had from the desktop recently.
7- Open setup.exe. Chrome 70 will install if all the steps are followed correctly.
8- Delete the folder "49.0.2623.112".
9- Congratulations! You successfully installed a new version of Chrome on XP.

**Comment by K-BOX2022** [comment]
Not Working

**Comment by ruupoo488** [comment]
> Ok, so people are asking me for my instructions. Here it is. Let's give an example and say that you want to install Chrome 70 on XP. Here's how: 1- If you own a system/VM that has an OS that still supports Chrome (Win7 and later), install Chrome 70 there. 32-bit: https://www.filepuma.com/download/google_chrome_32bit_70.0.3538.110-20750/ 64-bit: https://www.filepuma.com/download/google_chrome_64bit_70.0.3538.110-20751/ 2- After installation is done, go to Chrome's installation folder by right-clicking on Chrome's desktop shortcut and selecting "Open file location". 3- Inside Chrome's installation folder, you will see a folder that represents the version of Chrome you have installed. Open that folder, and inside that, you will see another folder named Installer. Go to that folder. 4- Now, follow this: If the OS that still supports Chrome (Win7 and later) is in a real hardware, get an external storage, copy chrome.7z from the Installer folder, and paste it there. Then, connect the external storage to your XP real hardware, and put it on the desktop. If the OS that still supports Chrome (Win7 and later) is in a VM, drag chrome.7z from the Installer folder, and drop it to your main system. Then, drop it to your XP VM on the desktop. 5- Install Chrome 49 on XP. 6- After Chrome 49 installation is done, right click on Chrome's desktop shortcut and select "Open file location" to go to Chrome's installation folder, then open the folder named 49.0.2623.112, and open the folder called Installer. Replace the chrome.7z file with the file you've had from the desktop recently. 7- Open setup.exe. Chrome 70 will install if all the steps are followed correctly. 8- Delete the folder "49.0.2623.112". 9- Congratulations! You successfully installed a new version of Chrome on XP.

You really can skip all of this by just getting

A: portable chrome
B: just downloading chromium files in zip format instead of installer

also up to Chromium 75 works on XP x64 (NT 5.2)
And up to Chromium 85 (maybe later too) works on XP x86 (NT 5.1)
Chromium 101 starts on 5.1 but doesnt load anything
do note you need to start chrome with --no-sandbox

**Comment by NEO-SPECTRUMAN** [comment]
> B: just downloading chromium files in zip format instead of installer

where is we can download portable/official zip package?

**Comment by ruupoo488** [comment]
> > B: just downloading chromium files in zip format instead of installer
> 
> where is we can download portable/official zip package?

Ungoogled Chromium (what i use): https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/windows/32bit/

Standard Chromium: https://chromium.cypress.io/win/

**Comment by mina354** [comment]
> You really can skip all of this by just getting
> 
> A: portable chrome B: just downloading chromium files in zip format instead of installer
> 
> also up to Chromium 75 works on XP x64 (NT 5.2) And up to Chromium 85 (maybe later too) works on XP x86 (NT 5.1) Chromium 101 starts on 5.1 but doesnt load anything do note you need to start chrome with --no-sandbox
> 
> EDIT: I should note some sites just dont work like youtube. This isn't a stable way to use modern chromium EDIT 2: i also forgot to mention i used vista's oleacc.dll to fix that missing function

Well, I don't prefer Chrome in portable, but in an installation, so I discovered that way instead. Of course I am aware of the fact that --no-sandbox is required.

**Comment by ruupoo488** [comment]
> > You really can skip all of this by just getting
> > A: portable chrome B: just downloading chromium files in zip format instead of installer
> > also up to Chromium 75 works on XP x64 (NT 5.2) And up to Chromium 85 (maybe later too) works on XP x86 (NT 5.1) Chromium 101 starts on 5.1 but doesnt load anything do note you need to start chrome with --no-sandbox
> > EDIT: I should note some sites just dont work like youtube. This isn't a stable way to use modern chromium EDIT 2: i also forgot to mention i used vista's oleacc.dll to fix that missing function
> 
> Well, I don't prefer Chrome in portable, but in an installation, so I discovered that way instead. Of course I am aware of the fact that --no-sandbox is required.

you can always just move the chromium portable/files you downloaded to a folder in your C: drive (or really anywhere) and make a shortcut on the desktop

**Comment by mina354** [comment]
> > > You really can skip all of this by just getting
> > > A: portable chrome B: just downloading chromium files in zip format instead of installer
> > > also up to Chromium 75 works on XP x64 (NT 5.2) And up to Chromium 85 (maybe later too) works on XP x86 (NT 5.1) Chromium 101 starts on 5.1 but doesnt load anything do note you need to start chrome with --no-sandbox
> > > EDIT: I should note some sites just dont work like youtube. This isn't a stable way to use modern chromium EDIT 2: i also forgot to mention i used vista's oleacc.dll to fix that missing function
> > 
> > 
> > Well, I don't prefer Chrome in portable, but in an installation, so I discovered that way instead. Of course I am aware of the fact that --no-sandbox is required.
> 
> you can always just move the chromium portable/files you downloaded to a folder in your C: drive (or really anywhere) and make a shortcut on the desktop

Yes, I know, but I prefer an installation over a portable/zip file.

**Comment by Skulltrail192** [comment]
> Chrome 100 doesn't work for me. If I run it without setting executable to Vista SP2 compatibility mode and no --no-sandbox parameter set on the shortcut, it gives this error. ![image](https://user-images.githubusercontent.com/87821255/169578545-4f71d582-f127-4922-bc9d-ac5a0d27adae.png) But, if I do both, Chrome 100 crashes. ![image](https://user-images.githubusercontent.com/87821255/169579128-df6d271d-3f8c-4013-8075-32f4acf5940b.png) @Skulltrail192 could you take a look at this issue?

Hey, i see on my Windows XP installation and oleacc.dll has this function. The version of file is 7.0.2600.6153. Maybe on your installation has a previous before these version. I will add oleacc.dll from my installation to prevent this error.

**Comment by K-BOX2022** [comment]
> > Chrome 100 doesn't work for me. If I run it without setting executable to Vista SP2 compatibility mode and no --no-sandbox parameter set on the shortcut, it gives this error. ![image](https://user-images.githubusercontent.com/87821255/169578545-4f71d582-f127-4922-bc9d-ac5a0d27adae.png) But, if I do both, Chrome 100 crashes. ![image](https://user-images.githubusercontent.com/87821255/169579128-df6d271d-3f8c-4013-8075-32f4acf5940b.png) @Skulltrail192 could you take a look at this issue?
> 
> Hey, i see on my Windows XP installation and oleacc.dll has this function. The version of file is 7.0.2600.6153. Maybe on your installation has a previous before these version. I will add oleacc.dll from my installation to prevent this error.

![169572871-4df47f0d-6542-4922-9494-ce25aff948cc](https://user-images.githubusercontent.com/100865716/171192141-86a5c436-4ab3-4be7-9034-ed75ba7471ee.PNG)

Hot to fix it?

**Comment by ruupoo488** [comment]
In my testing on latest updates i could only get Chromium 85 working on NT 5.1 and it was unstable.
It was on latest update level (updated via WSUS and has all patches) and was still missing a function in oleacc.dll. I used Vista x86 oleacc to fix this but its strange that it needed it at all.. since that implies that testing was done with an oleacc that had the function.
Perhaps we are doing something wrong? But chromium 101 DID start but refused to render any pages.

**Comment by mina354** [comment]
> > Chrome 100 doesn't work for me. If I run it without setting executable to Vista SP2 compatibility mode and no --no-sandbox parameter set on the shortcut, it gives this error. ![image](https://user-images.githubusercontent.com/87821255/169578545-4f71d582-f127-4922-bc9d-ac5a0d27adae.png) But, if I do both, Chrome 100 crashes. ![image](https://user-images.githubusercontent.com/87821255/169579128-df6d271d-3f8c-4013-8075-32f4acf5940b.png) @Skulltrail192 could you take a look at this issue?
> 
> Hey, i see on my Windows XP installation and oleacc.dll has this function. The version of file is 7.0.2600.6153. Maybe on your installation has a previous before these version. I will add oleacc.dll from my installation to prevent this error.

My installation is a clean one with no updates. This is also the latest OCAPI, no previous ones installed or anything. Thanks.

**Comment by mina354** [comment]
@Skulltrail192 Ok, so I tried it with OCAPI version 2.4.0, and the issue of oleacc.dll is still happening. I even tried to replace it manually, but it still stays with version 4.2.5406.0. This was tested with Chrome 102.

oleacc.dll file version before OCAPI installation:
![image](https://user-images.githubusercontent.com/87821255/171664586-7804d1c6-78fa-46af-ac80-b4a81315c849.png)

oleacc.dll file version after OCAPI installation:
![image](https://user-images.githubusercontent.com/87821255/171665651-545f1440-8740-4b9c-ab0e-b588a5ed489c.png)

**Comment by jonm58** [comment]
@mina354
![Windows XP Professional-2022-06-04-01-11-40](https://user-images.githubusercontent.com/73036321/171913341-eb2e1bb7-9aa2-48c0-9100-60666b8177f3.png)
 Advanced Chrome 94.0.4590.0
But can't open webside

**Comment by mina354** [comment]
How sad.

**Comment by jonm58** [comment]
@mina354 But new Advanced Chrome only 94.0.4590.0
(94-99 working 100+ no work){No Test 100 and earlier versions}

**Comment by mina354** [comment]
Ya know what. I am recreating my XP VM later on. Indeed something must've went wrong that doesn't make Chrome 100+ run on my VM.

**Comment by Skulltrail192** [comment]
For version 51~69, you must set compatibility to Windows Vista SP2, add parameter to shortcut "--no-sandbox". And all version above, you only need add the paremeter "--no-sandbox". The problem with oleacc is solved on version 2.5.0

**Comment by mina354** [comment]
Thank you, it works!
![image](https://user-images.githubusercontent.com/87821255/174679392-6f35fdb2-8c44-45a9-905f-497cd327a4f7.png)

**Comment by mina354** [comment]
@Skulltrail192 But there's a problem, downloading files using newest Chrome version, gives a "Failed - Download error" error. I can't also install extensions.
![image](https://user-images.githubusercontent.com/87821255/174683885-9eb58ed0-4582-4c72-bad5-552b7c3ea7be.png)
Other than these issues, newest Chrome version works fine otherwise.

**Comment by K-BOX2022** [comment]
@Skulltrail192 In my browser there is no sound at all. On chrome, chromium and brave there is no sound at all, I tried with --wave-audio and then without it and no difference. How to fix it?

**Comment by Skulltrail192** [comment]
> @Skulltrail192 In my browser there is no sound at all. On chrome, chromium and brave there is no sound at all, I tried with --wave-audio and then without it and no difference. How to fix it?

Well, need a little fix: the correct parameter is: "--force-wave-audio"

**Comment by Skulltrail192** [comment]
Chrome still has instability and crash randomless, it need some investigation. On Server 2003 and XP x64 now has some compatbility, run chrome at last version (tested 105 version)

**Comment by K-BOX2022** [comment]
@Skulltrail192 Also not working audio in chrome

**Comment by mina354** [comment]
@Skulltrail192 Just updated to Chrome 103 (released today), and Chrome immediately closes upon launching it.

**Comment by Skulltrail192** [comment]
> @Skulltrail192 Just updated to Chrome 103 (released today), and Chrome immediately closes upon launching it.

How i said on release notes, Chrome has instability both XP/Server 2003, need investigaton.

**Comment by Skulltrail192** [comment]
> > @Skulltrail192 But there's a problem, downloading files using newest Chrome version, gives a "Failed - Download error" error. I can't also install extensions. ![image](https://user-images.githubusercontent.com/87821255/174683885-9eb58ed0-4582-4c72-bad5-552b7c3ea7be.png) Other than these issues, newest Chrome version works fine otherwise.
> 
> What about these? My network connection is working fine, so the download error appears even if my network connection is fine.

What version used?

**Comment by mina354** [comment]
> > @Skulltrail192 Just updated to Chrome 103 (released today), and Chrome immediately closes upon launching it.
> 
> How i said on release notes, Chrome has instability both XP/Server 2003, need investigaton.

Got it.


> > > @Skulltrail192 But there's a problem, downloading files using newest Chrome version, gives a "Failed - Download error" error. I can't also install extensions. ![image](https://user-images.githubusercontent.com/87821255/174683885-9eb58ed0-4582-4c72-bad5-552b7c3ea7be.png) Other than these issues, newest Chrome version works fine otherwise.
> > 
> > 
> > What about these? My network connection is working fine, so the download error appears even if my network connection is fine.
> 
> What version used?

102, the last version that lets me download files is 74. Extensions don't install on any newer Chrome version though.

**Comment by Skulltrail192** [comment]
> > > @Skulltrail192 Just updated to Chrome 103 (released today), and Chrome immediately closes upon launching it.
> > 
> > 
> > How i said on release notes, Chrome has instability both XP/Server 2003, need investigaton.
> 
> Got it.
> 
> > > > @Skulltrail192 But there's a problem, downloading files using newest Chrome version, gives a "Failed - Download error" error. I can't also install extensions. ![image](https://user-images.githubusercontent.com/87821255/174683885-9eb58ed0-4582-4c72-bad5-552b7c3ea7be.png) Other than these issues, newest Chrome version works fine otherwise.
> > > 
> > > 
> > > What about these? My network connection is working fine, so the download error appears even if my network connection is fine.
> > 
> > 
> > What version used?
> 
> 102, the last version that lets me download files is 74. Extensions don't install on any newer Chrome version though.

Thanks man, i will analyze differences between these 74 and 75 versions.

**Comment by Skulltrail192** [comment]
Hello, i made a mistake. The correct parameter to get audio working on Chrome is: --enable-exclusive-audio

**Comment by mina354** [comment]
Oops. 
Anyway, have you found differences between versions 74 and 75?

**Comment by jonm58** [comment]
Chrome 94 can't Download

**Comment by Skulltrail192** [comment]
> Oops. Anyway, have you found differences between versions 74 and 75?

For now, no.

**Comment by mina354** [comment]
Alright.

**Comment by win32ss** [comment]
If you want Chromium to work perfectly on Windows XP (i.e. install extensions, be able to access its own cookies, etc), one of the things you will have to do is enhance FindFirstFileExW so it accepts the new flags and enums that Windows 7 added for it. You can find an example in my API repository.

**Comment by Skulltrail192** [comment]
> This seems to be an issue where Chromium cannot get write access to the temp folders, according to Chromium source.
> 
> If you want Chromium to work perfectly on Windows XP (i.e. install extensions, be able to access its own cookies, etc), one of the things you will have to do is enhance FindFirstFileExW so it accepts the new flags and enums that Windows 7 added for it. You can find an example in my API repository.

Hey friend, i will test. We can talk by email, skype or other way?

**Comment by win32ss** [comment]
Yes, try e-mailing me at win32alt@inbox.lv (it is a terrible provider anyway, that inbox is clogged up with lots of local spam anyway so I don't care if harvesters get at that one).

**Comment by avaxx** [comment]
First of all, congratulations and a big thank to Skulltrail192 for the progress in making newer Chrome versions work in XP!

I use XP SP2 and I tried to start Chrome v102 and v90 without installing One-Core-Api. Here's what i did...
I updated App Compat files manually.
Just in case I put all other OCA DLLs in Chrome's folder (where Chrome.exe and other essential Chrome files are) together with a proper file Chrome.exe.manifest which contains a line for each OCA DLL to enable DLL redirection (to be sure that Chrome will use system DLLs from OCA instead of those ones from Windows\System32).
As base DLLs for OCA wrappers I copied DLLs from SP3.
I renamed import module name "Kernel32.dll" in Kernelbase.dll to "Kernelex.dll" (using CFF Explorer) and put my system's Kernel32.dll (btw I use Dibya's extended kernel) renamed to "Kernelex.dll" in the same folder.
I also renamed import module name "Ntext.dll" in Xpspkernel32.dll (needs Kernelbase.dll for forwarded exports) to "Ntdll.dll" and renamed this file to Kernel32.dll placing it in the same folder (there's the redirection line for it in my Chrome.exe.manifest as well).
 
To my pleasant surprise, with proper command line options and the proper compatibility setting, I started Chrome successfully. But there's just one "little" problem - Chrome cannot load any web page! I get the following error message: "This site can’t be reached ... ERR_NAME_NOT_RESOLVED" I tried everything that came to my mind but nothing helped. Does anybody have any idea...?
(I think I had a similar problem with chinese 360 Extreme Browser (360Chrome) v13 but I solved it by using 360bdoctor.exe, I'm not sure what this proggy does but it worked.)
Btw installing extensions doesn't work either.

**Comment by Skulltrail192** [comment]
Are you updated Root Certifcates? To navigate with Chrome, you must use the tool on this repository to update Root Certificates.

**Comment by avaxx** [comment]
Thanks, certificates were updated, anyway I finally solved the problem. (Although I have some issue with security it can be avoided by using option "--ignore-certificate-errors".)

I was inspecting Chrome's Internet and networking API calls with API Monitor (rohitab.com) and found out that function getaddrinfo from Ws2_32.dll returns error code WSANOTINITIALISED, and that WSASocketW returns INVALID_SOCKET while trying to load a website, most likely because Ws2_32.dll is not properly initiated by Chrome. With Ollydbg I found a call to WSAStartup in Chrome.dll which looks related to this and I managed to read out the function's return value, it was 10107 what means WSASYSCALLFAILURE, an untypical error which didn't mean much to me.

Fortunately, the solution was very simple. Instead of a redirection to another Ws2_32.dll this DLL should be loaded with the system. I had to remove lines for redirection to Ws2_32.dll and Ws2_base.dll in Chrome's folder from my Chrome.exe.manifest, and to move these DLLs to Windows\System32. Just to mention for those ones who are interested, to make wrapper Ws2_32.dll work you should also put unmodified Kernelbase.dll, Ntext.dll and Normaliz.dll from O-C-A in Windows\System32.
(Btw Dibya's Ws2_32.dll from Extended XP works well too, in case anyone needs it here's the link: https://app.box.com/s/olwh7j6q9cag4justfgsif2jek5lbbmb)

Interestingly, with App Compat files from the newest O-C-A v2.9.0 I have to set compatibility mode for Chrome.exe to XP SP2 instead of Vista SP2.

Chrome 102 is still not usable for me, webpages crash constantly, they cannot be saved, no download is possible, but it looks like the things move in the right direction :)

**Comment by Skulltrail192** [comment]
Well, maybe ws2_32 is related with steam and discord problem?

**Comment by RetroSoftwareRepository** [comment]
On 32 bit XP, latest version of Chromium fails to even launch...let alone install.

**Comment by TK50P** [comment]
> > > > @Skulltrail192 Just updated to Chrome 103 (released today), and Chrome immediately closes upon launching it.
> > > 
> > > 
> > > How i said on release notes, Chrome has instability both XP/Server 2003, need investigaton.
> > 
> > 
> > Got it.
> > > > > @Skulltrail192 But there's a problem, downloading files using newest Chrome version, gives a "Failed - Download error" error. I can't also install extensions. ![image](https://user-images.githubusercontent.com/87821255/174683885-9eb58ed0-4582-4c72-bad5-552b7c3ea7be.png) Other than these issues, newest Chrome version works fine otherwise.
> > > > 
> > > > 
> > > > What about these? My network connection is working fine, so the download error appears even if my network connection is fine.
> > > 
> > > 
> > > What version used?
> > 
> > 
> > 102, the last version that lets me download files is 74. Extensions don't install on any newer Chrome version though.
> 
> Thanks man, i will analyze differences between these 74 and 75 versions.

I have same problem.
![chrome_extenstions_problem](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/127497974/15323396-5558-44a5-a118-3a2d5999c7a2)

**Comment by Skulltrail192** [comment]
Fixed main issue and chrome 103-109 is working on XP. See chrome main thread: #178
