### ISSUE TITLE
Once One-Core-API is installed, you cannot use any custom themes.

### ISSUE THREAD

**Issue by mina354** [Skulltrail192/One-Core-API-Binaries#58]
![image](https://user-images.githubusercontent.com/87821255/169616140-96e4c408-a28a-4c69-bad9-794d6a405cc2.png)
![image](https://user-images.githubusercontent.com/87821255/169616278-d515749c-4589-4bfb-96f3-76a4d18c93f7.png)
Just thought I'd point that out here. If One-Core-API isn't installed, you can use custom themes, but you will miss out on boosted app compatibility, and that's kinda sad, because I want to have One-Core-API installed, while at the same time having [a Windows 7 theme applied.](https://www.deviantart.com/ebhefgyxp/art/Aero-7-XP-v11-4-807725030)

**Comment by NEO-SPECTRUMAN** [comment]
maybe you can setep win15 theme
and install OCAPI after
im installed OCAPI on sevetal virtaulbox systems
and almost all with custom theme by default

**Comment by mina354** [comment]
If I setup custom themes, and install OCAPI after that, the custom themes no longer work, since the patched uxtheme.dll gets replaced by OCAPI's.

**Comment by mina354** [comment]
> Well, it occurs because uxtheme is wrapper on One-core-API. The real dll is uxthemebase. _I will replace this dll with already patched dll, to allow custom themes._

That's awesome to hear!
