### ISSUE TITLE
MyPal 68 problem

### ISSUE THREAD

**Issue by jonm58** [Skulltrail192/One-Core-API-Binaries#59]
https://www.youtube.com
![Windows XP Professional-2022-05-21-17-10-21](https://user-images.githubusercontent.com/73036321/169644638-7971edf3-23af-480b-bff0-bebaba187af0.png)
click Don't send mypal 68 crashed
https://www4.bing.com
![Windows XP Professional-2022-05-21-17-19-10](https://user-images.githubusercontent.com/73036321/169645010-025cf66b-3b17-492e-baf9-821357c06819.png)
![Windows XP Professional-2022-05-21-17-19-16](https://user-images.githubusercontent.com/73036321/169645012-cb9a2db1-4d0a-4d73-8237-89325de38aaa.png)
![Windows XP Professional-2022-05-21-17-19-24](https://user-images.githubusercontent.com/73036321/169645013-1ca45487-92bc-40ca-b9b9-1ba34d1550ba.png)
click Don't send mypal 68 no crashed

Windows XP SP3
Base Installer -> New Installer (Additional Dlls) -> D3d Installer -> API-SET installer -> App Compat
**mypal**:68.12.3b

**Comment by mina354** [comment]
Yeah, I noticed the same, that 2.3.0 release makes Firefox-based browsers run unstable. Didn't happen with 2.2.1 and below though. I hope this issue gets fixed as soon as possible, because it's making Firefox-based browsers unusable.

**Comment by Skulltrail192** [comment]
This is a known issue and i trying fixing it in this moment.

**Comment by Skulltrail192** [comment]
This is already fixed, on next version on end of month i will release the fix.

**Comment by GizmoTheGreen** [comment]
MyPal crashing for me on 2.10...
