### ISSUE TITLE
Windows 7/10 GPU Drivers for Windows XP?

### ISSUE THREAD

**Issue by K-BOX2022** [Skulltrail192/One-Core-API-Binaries#60]
Hey. When will it be possible to install graphics drivers from Windows 7/10 on XP?

Will you add such a feature. I need to upload Amd Radeon r2 on XP but driver is only from 7 upwards.

@Skulltrail192

**Comment by foxtrot-99** [comment]
If it is possible, it would be great, but I heard that Windows XP or earlier and Windows Vista and later's graphics system is very different.

**Comment by Skulltrail192** [comment]
For now, no. I'm working to transplant/implement WDDM on XP/2003, however, it isn't easy task. Several components need be modified.

**Comment by Skulltrail192** [comment]
Well, due it is not possible for now, i will close this issue.
