### ISSUE TITLE
Some devices stops working

### ISSUE THREAD

**Issue by cesar300** [Skulltrail192/One-Core-API-Binaries#61]
When I install the first package (base with kernel update), the laptop GPU nvidia GTX 980 disappears from the device manager. When I try to open the nvidia control panel says: "There's no nvidia gpu". What's going on?
And other problem is the USB ports. My laptop is xhci only; when I use the amdxhci modded driver, after the installation, throws code 10.
It was better that the kernel installer was independent from base installer.
Thanks.

**Comment by NEO-SPECTRUMAN** [comment]
try to overwrite kernel updates
with installing all other packagess (without kernel standalone)

**Comment by cesar300** [comment]
All packages require the base installer.

**Comment by Skulltrail192** [comment]
No, kernel update is a standalone, not need Base installer. AppCompat too, no need base installer. However, maybe when change the hal, Windows need update drivers, so, maybe this is reason of vga missing.

**Comment by Skulltrail192** [comment]
What the processor?

**Comment by cesar300** [comment]
Intel core i7 6700 3,40 GHz

**Comment by cesar300** [comment]
I used this acpi file: "acpi 6666 - 2021.8.28 - daniel_k, diderius6"

**Comment by Skulltrail192** [comment]
Repelace again with this file and test again.

**Comment by cesar300** [comment]
Which file?

**Comment by Skulltrail192** [comment]
> Which file?

I used this acpi file: "acpi 6666 - 2021.8.28 - daniel_k, diderius6"

**Comment by Skulltrail192** [comment]
Can you provide the link to download these driver?

**Comment by jonm58** [comment]
There may be problems with storport.sys, ntoskrn8.sys, storpor8.sys

**Comment by jonm58** [comment]
> There may be problems with storport.sys, ntoskrn8.sys, storpor8.sys

USB3.X xHCI Driver Use storport.sys, ntoskrn8.sys,

**Comment by jonm58** [comment]
@cesar300 I'm curious if the driver version you use is 145 or 276？

**Comment by cesar300** [comment]
Finally got it working without the kernel patch and acpi files. Simply commenting the lines with a semicolon making reference to:
acpi.sys
hal files
kernel nt files

**Comment by Skulltrail192** [comment]
kernel Nt files are required to new features, like Chromium works. Please, send to me the link to download what acpi driver used and what get BSOD.

**Comment by NEO-SPECTRUMAN** [comment]
> Are there any chance to execute it w/o installing this software?

you can try to patch PE header for all executables and dlls
rename all system dlls in import table
(kernel32 -> kernel3O)
and put dlls from ocapi to executable folder
with renaming (kernel32.dll -> kernel3O.dll)

**Comment by NEO-SPECTRUMAN** [comment]
also you need Dependency walker

**Comment by cesar300** [comment]
> you can try to patch PE header for all executables and dlls

Which program did you use in this screenshot?

**Comment by Skulltrail192** [comment]
To rename required dependency dll, you can use a hex editor. Find occorrence of dll string name and replace. However, it isn't the goal of one-core-api.

**Comment by Skulltrail192** [comment]
Hello

> When I install the first package (base with kernel update), the laptop GPU nvidia GTX 980 disappears from the device manager. When I try to open the nvidia control panel says: "There's no nvidia gpu". What's going on? And other problem is the USB ports. My laptop is xhci only; when I use the amdxhci modded driver, after the installation, throws code 10. It was better that the kernel installer was independent from base installer. Thanks.

Hello. Please, make screenshot of device manager with GPU detais and USB

**Comment by Skulltrail192** [comment]
Since the creator of issue not returned, this issue will be closed.
