### ISSUE TITLE
OCAPI 2.4.0 BSOD

### ISSUE THREAD

**Issue by jonm58** [Skulltrail192/One-Core-API-Binaries#62]
![Windows XP Professional-2022-06-02-20-09-32](https://user-images.githubusercontent.com/73036321/171626798-ee75ed7e-c54a-4b18-a523-dff01c7a30f3.png)

How to Fix it?
only Base Installer.

**Comment by Skulltrail192** [comment]
What system? What environment? Real Hardware or Virtual Machine? You need to specify details. I really don't know what happening only seeing a print screen.

**Comment by jonm58** [comment]
@Skulltrail192 
> system:Windows XP Professional SP3 x86 - Integral Edition 2021.12.19 (Vanilla)
> environment:Boot BSOD
> Virtual Machine:VMware® Workstation 16 Pro(16.2.3 build-19376536)

**Comment by Skulltrail192** [comment]
Are the issue solved?
