### ISSUE TITLE
VLC media player  problem

### ISSUE THREAD

**Issue by jonm58** [Skulltrail192/One-Core-API-Binaries#63]
The same two error pop-ups appear when the VLC opens.
![Windows XP Professional-2022-06-03-23-42-26](https://user-images.githubusercontent.com/73036321/171900229-40259bad-4db9-434a-90ab-0fe15728354b.png)
![Windows XP Professional-2022-06-03-23-48-19](https://user-images.githubusercontent.com/73036321/171900560-7fae79d4-3f86-4ef8-98bd-78f848e2cb52.png)

**Comment by mina354** [comment]
This doesn't only happen with VLC, also happens with Zoom Meetings app. https://zoom.us/download
![image](https://user-images.githubusercontent.com/87821255/171916723-6ccdbc20-0d75-4ae1-9b46-fff4d02f5c5d.png)

**Comment by Skulltrail192** [comment]
Due it was fixed on version 2.5.0, this issue will be closed
