### ISSUE TITLE
Internet messed up

### ISSUE THREAD

**Issue by Legendary-Candice-Joe** [Skulltrail192/One-Core-API-Binaries#65]
When I try to run steam, riot client, osu, they all pop up with errors about not having an internet connection. Although steam and riot client are technically not supported, osu, as far as I know, should be working just fine. What's weirder is there is an active connection. I'm literally posting this on mypal 68 on the same computer, but the apps aren't working??? Its also worth mentioning I'm running one core 2.2.1 since 2.3.0 and 2.4.0 are causing a lot of stablility issues, and other non-sense.

Another thing that isn't too big of a deal is that I can't get dotnet 4.5 to work correctly. I can install it, but it has a weird error with a memory address and saying that it has been terminated.

any help with one of these issues would be nice.

**Comment by foxtrot-99** [comment]
This happens in Node.js too.

**Comment by Skulltrail192** [comment]
This a known issue what need investigation yet.

**Comment by Legendary-Candice-Joe** [comment]
Real quick before I close this, I noticed that task manager can see a full 8gb of ram. Even tho this is a 32 bit installation. I assume this is PAE but is there any way to disable this? since a lot of programs seem to also be having issues with ram. I'm fine with just 4gb.
