### ISSUE TITLE
2.4.0 GetQueuedCompletionStatusEx exported in kernebase.dll, but kernel32.dll isn't exported it

### ISSUE THREAD

**Issue by jis133** [Skulltrail192/One-Core-API-Binaries#66]
some program need this api in kernel32.dll,can add it in kernel32.dll?

**Comment by Skulltrail192** [comment]
GetQueuedCompletionStatusEx is exported from kernel32.dll yes.

**Comment by Skulltrail192** [comment]
Due kernel32 already export this function, this issue will be closed.
