### ISSUE TITLE
OCAD3DR Setup Error: The file amd64/d3d12.dll is missing

### ISSUE THREAD

**Issue by GlitchR9506** [Skulltrail192/One-Core-API-Binaries#67]
I was attempting to install One-Core-Api on Windows 2003 x64 and when I went to run the Direct3D installer got this error on 2.4.0.
This error is not present in the x86 version which has the file nor in 2.3.0 x64 where it lacks the file but does not look for it.

**Comment by Skulltrail192** [comment]
It will be fixed on next version.

**Comment by Skulltrail192** [comment]
Due it was fixed on version 2.5.0, this issue will be closed
