### ISSUE TITLE
geph4-client and wepoll library can't run , need  NtCancelIoFileEx in ntdll.dll

### ISSUE THREAD

**Issue by jerrypack104** [Skulltrail192/One-Core-API-Binaries#69]
Can add this function in ntdll.dll? some socket library also use this function.
![api1](https://user-images.githubusercontent.com/108001904/175029447-12e0caec-054b-4421-8fc4-7186a5147589.png)

**Comment by Skulltrail192** [comment]
Where can i find this program?

**Comment by Skulltrail192** [comment]
Added function on version 2.7.0. So, this issue will be closed.
