### ISSUE TITLE
How to uninstall one-core-api-app-kernel-alone.exe?

### ISSUE THREAD

**Issue by hlizard** [Skulltrail192/One-Core-API-Binaries#72]

**Comment by jonm58** [comment]
在增加或卸载软件，卸载更新

**Comment by hlizard** [comment]
> 在增加或卸载软件，卸载更新
添加或删除程序/Add or Remove Programs里选中显示更新/Show updates后找到了.
谢谢你的提示, 之前没认真找, 还以为不可以卸载呢,:)

**Comment by NEO-SPECTRUMAN** [comment]
![2022-06-28_113803](https://user-images.githubusercontent.com/88002487/176133995-d9fa4fa3-cc7f-45bd-8149-3d8df2254537.png)

**Comment by hlizard** [comment]
When I uninstalled and installed again, I found that they no longer appeared there

**Comment by hlizard** [comment]
@Skulltrail192 @jonm58 没有这些文件夹，只有以“$NtUninstallKB”开头的文件夹。此外，我还发现了几个OCA安装和卸载日志文件。我现在不能卸载它们？！我只能等待后续更新来解决问题:
1. 迅雷崩溃(迅雷精简版1.5.3.288隔一次闪退; 迅雷X测试版10.0.3.88启动后提示"迅雷下载SDK 崩溃了 很抱歉");
2. 执行Firefox 54, Waterfox 31, ChromeSetup, VSCode等安装包报错, 似乎什么都无法安装;
3. 遨游5浏览器打开保存文件对话框导致崩溃;

补充: 我的系统是XP x64 SP2再加很多官方补丁, 实机.

en:
There are no such folders, only folders starting with "$NtUninstallKB". In addition, I found several OCA installation and uninstall log files. I can't uninstall them now?! I can only wait for subsequent updates to resolve the issue:

1. Xunlei crashes (Xunlei compact version 1.5.3.288 crashes every other time; Xunlei X beta version 10.0.3.88 prompts "sorry, Xunlei download SDK crashed" after startup);

2. execute Firefox 54, Waterfox 31, ChromeSetup, VSCode and other installation packages report errors. It seems that nothing can be installed;

3. Maxthon 5 browser crash when openning the save file dialog box;

Add: my system is XP x64 SP2 with many official patches, which is a real notebook.

**Comment by Skulltrail192** [comment]
> @Skulltrail192 @jonm58 没有这些文件夹，只有以“$NtUninstallKB”开头的文件夹。此外，我还发现了几个OCA安装和卸载日志文件。我现在不能卸载它们？！我只能等待后续更新来解决问题:
> 
>     1. 迅雷崩溃(迅雷精简版1.5.3.288隔一次闪退; 迅雷X测试版10.0.3.88启动后提示"迅雷下载SDK 崩溃了 很抱歉");
> 
>     2. 执行Firefox 54, Waterfox 31, ChromeSetup, VSCode等安装包报错, 似乎什么都无法安装;
> 
>     3. 遨游5浏览器打开保存文件对话框导致崩溃;
> 
> 
> 补充: 我的系统是XP x64 SP2再加很多官方补丁, 实机.
> 
> en: There are no such folders, only folders starting with "$NtUninstallKB". In addition, I found several OCA installation and uninstall log files. I can't uninstall them now?! I can only wait for subsequent updates to resolve the issue:
> 
>     1. Xunlei crashes (Xunlei compact version 1.5.3.288 crashes every other time; Xunlei X beta version 10.0.3.88 prompts "sorry, Xunlei download SDK crashed" after startup);
> 
>     2. execute Firefox 54, Waterfox 31, ChromeSetup, VSCode and other installation packages report errors. It seems that nothing can be installed;
> 
>     3. Maxthon 5 browser crash when openning the save file dialog box;
> 
> 
> Add: my system is XP x64 SP2 with many official patches, which is a real notebook.
> 
> OCAB.log: ![image](https://user-images.githubusercontent.com/6994037/176336205-aacfc268-2dd4-4270-b329-3be02a3ef46b.png) [OCAB.log](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9006867/OCAB.log)

- Firefox 54 32 bits not working for now on XP x64. Only 64 bits works. 
- Waterfox 31 must be set compatbility to Windows 7 to install. And it's works fine;
- Chrome Setup is not working for all, however, i never said it's works. Need be investigate
- VSCode only works until version 1.19 for now. And, must be set compatbility to Windows 7 to install and generate error when create the shortcut. However, it is installed, verify "Program and files and see Microsoft VS Code folder;
-

**Comment by hlizard** [comment]
@Skulltrail192 
- Set compatibility to Windows 7 SP1 to run VSCodeSetup-ia32-1.18.1.exe(or VSCodeSetup-x64-1.18.1.exe), alert ```Access violation at address 7DBC16BB in module 'LPK.DLL'. Read of address 00000086.``` and 
```Access violation at address 71A5AD64 in module 'comctl32.dll'. Read of address 00000000.``` when step "Select Destination Location", can not continue.
- No window display when running Code.exe from the portable version VSCode-win32-ia32-1.18.0.zip(or VSCode-win32-x64-1.18.0.zip), XP 5.1 sp3 also.
- Yes, my Firefox setup file is 64 bit, same error "The exception unknown software exception (0xc0000005) occurred in the application at location 0x7dbc16bb." when select destination location.

**Comment by hlizard** [comment]
@Skulltrail192 I found changing "Language for non-Unicode programs" from "Chinese (PRC)" to "English (United States)" can make  FF and VSCode setup program work.

**Comment by Skulltrail192** [comment]
One-Core-API only support English-US for default for now

**Comment by Skulltrail192** [comment]
> @Skulltrail192
> 
>     * Set compatibility to Windows 7 SP1 to run VSCodeSetup-ia32-1.18.1.exe(or VSCodeSetup-x64-1.18.1.exe), alert `Access violation at address 7DBC16BB in module 'LPK.DLL'. Read of address 00000086.` and
>       `Access violation at address 71A5AD64 in module 'comctl32.dll'. Read of address 00000000.` when step "Select Destination Location", can not continue.
> 
>     * Yes, my Firefox setup file is 64 bit, same error `The exception unknown software exception (0xc0000005) occurred in the application at location 0x7dbc16bb.` when select destination location.
> 
>     * No window display when running Code.exe from the portable version VSCode-win32-ia32-1.18.0.zip(or VSCode-win32-x64-1.18.0.zip), XP 5.1 sp3 also.

You need send to me the link to download the iso of windows utilized, because my installations are working.

**Comment by Skulltrail192** [comment]
Now, all packages are installable and uninstallable. And, Kernel-standalone now is discontinued.

**Comment by Skulltrail192** [comment]
Please, create separated issue for each problem found;

**Comment by Skulltrail192** [comment]
And, One-Core-API for now is designed for English-US, may several bugs in others languages;

**Comment by hlizard** [comment]
Seeing your v2.6.0 update instructions, I really want to try again, but this weekend I changed the system to win8.0, and maybe I will try again in the future. Thank you for your extraordinary work. It's amazing.
