### ISSUE TITLE
Support for modern versions of Telegram Desktop in One Core API

### ISSUE THREAD

**Issue by EgorKuzevanov** [Skulltrail192/One-Core-API-Binaries#74]
Is it planned to support the installation and launch of modern versions of the Telegram messenger (3.2.5+) with support for 64-bit identifiers in the One Core API? Official support for the Telegram messenger for Windows XP/Vista ended on version 1.8.15 (2019). But in Telegram Desktop 1.8.15 under Windows XP/Vista, all new users and channels are not visible.

**Comment by mina354** [comment]
I hope this happens, newer versions of Telegram means more fun.

**Comment by mina354** [comment]
Basically, I would also be glad if WhatsApp Desktop can also be made to run on XP with OCAPI.

**Comment by Skulltrail192** [comment]
Version 4.0.x is supported...But, you need a native dwrite from Windows Vista or 7 and it will break chrome 110+.
