### ISSUE TITLE
WindowBlinds unable to load on Windows XP

### ISSUE THREAD

**Issue by yazanoo16** [Skulltrail192/One-Core-API-Binaries#76]
Greetings!
I just wanted to report an issue regarding WindowBlinds (WB version 6.0 to be precise) being unable to launch after One Core API is installed.

The issue is persistent even after reinstalling WindowBlinds.
Seems like One Core API hates WindowBlinds due to the kernel calls and the API itself.

See screenshot below for more useful information:
![image](https://user-images.githubusercontent.com/65330730/177614767-d83f56ef-261b-452d-83bf-00007b1c7f55.png)

This window keeps appearing even after i hit 'OK'

If there's anything that can be done about this issue, that'd be amazing.
If not, then that's fair.

Cheers & Best Regards,
Yazan A.

**Comment by Skulltrail192** [comment]
WindowBlinds6 is designed to Windows XP or only WindowBlinds5?

**Comment by yazanoo16** [comment]
WindowBlinds6 was designed to be compatible with Vista but it also works with Windows XP as well.

**Comment by Skulltrail192** [comment]
Are you using WindowBlinds in compatiblity mode?

**Comment by yazanoo16** [comment]
I haven't tried it with compatibility mode yet.
I'll be going to check in a few hours and see if that will do it as a workaround.

**Comment by yazanoo16** [comment]
Just checked,
Compatibility mode does not seem to fix the issue either.

**Comment by Skulltrail192** [comment]
I found a fix. Will be avaliable on end-of-month release.

**Comment by Skulltrail192** [comment]
Fixed on version 2.10.0
