### ISSUE TITLE
Internet Explorer 11 

### ISSUE THREAD

**Issue by CE1CECL** [Skulltrail192/One-Core-API-Binaries#77]
https://www.microsoft.com/en-us/download/details.aspx?id=40907

You need Windows 7 SP1 or Server 2008 R2 SP1 to install Internet Explorer 11.

Just trying to experiment tho

**Comment by CE1CECL** [comment]
Microsoft Edge Installer just crashes too, wanted some sort of IE for XP. https://www.microsoft.com/en-us/edge

**Comment by CE1CECL** [comment]
> wrong Internet Explorer version might break the OS, I force installed IE7 on Windows 7 because of the lovely glossy blue tab the OS got corrupted so I had to reinstall it

i wonder if i should copy ie11 from windows 7 and copy it to xp, only the program files first
or should i try 10's?

**Comment by Skulltrail192** [comment]
For now, IE explorer 9 is a dream. Really is very hard port that application to Windows XP.
