### ISSUE TITLE
Some programs have completely silent audio.

### ISSUE THREAD

**Issue by Legendary-Candice-Joe** [Skulltrail192/One-Core-API-Binaries#79]
This one explains itself. Some programs I tried are just silent, this is probably due to --enable-exclusive-audio being part of create process but since I can't disable this (or even be sure that this IS the issue), some programs just have no audio. And also MiniBrowser now complains about not having an output device (I can still hear audio just cause of exclusive audio) which is quite weird.

I know this issue is probably already known. And I've been creating a lot of issues lately (sorry for that). But this actually already happened with one core 2.6.0, I was just hoping it would be fixed in 2.7.0.

(incoming dumb request)
I know this is dumb, but since getCompletionStatusEx was removed a few programs have failed. I was wondering if it was some how possible to add it back but renamed (E.G getCompletionStatusEv or smth like that) with the idea being that I can hex edit programs that would need this function. This is dumb. This probably not even worth doing, but I was wondering if it would be possible. I would probably try to compile one core api myself however I am way to dumb to figure it out. And besides this is really just so I can run java 17 and 18.

**Comment by Skulltrail192** [comment]
Hello, what programs has this problem? Can list to me?

**Comment by Legendary-Candice-Joe** [comment]
basically just osu (and fnf and other rythm games). Whats weirder is how osu runs on legacy audio and even an output device but is silent?

As I said this didn't happen in 2.5.0, and 2.6.0 had the --enable-exlusive-audio flag on create process. I can't disable that so I can't tell for sure.

(also I'm still having internet issues)

**Comment by Skulltrail192** [comment]
These games run on browser? Or from steam? This parameter "--enable-exlusive-audio" only was added for:
- chrome.exe
- opera.exe
- msedge.exe

All other exe not run with this parameter

**Comment by Legendary-Candice-Joe** [comment]
really. So I guess it must be some other audio thing then. As I said, this happened with 2.6.0. But I noticed with 2.6.0 that audacity 3.1.3 (the only one I bothered trying) worked just fine? So I don't really know whats happening behind the scenes.

Anyway. They are not browser games (or steam), Nor would that really make sense because I can hear audio just fine in chrome (tho chrome cannot see output devices), and Steam games are their own EXE.

Though it is worth mentioning I can't get steam to run. If I try the installer it says "checking for updates" then errors out saying "steam needs to be online to update". I tried using a pre-install however I got the same result. With internet I don't have a wifi card, so I have a laptop that I hooked up ethernet with. This works just fine for chrome and web browsers so yeah.

But back to audio, its weird. Audacity and Osu can see output devices, but Teams on MiniChrome says it can't find a speaker? And lastly, these games do use the legacy audio architecture. So them using Vista audio is not the issue here.

**Comment by Legendary-Candice-Joe** [comment]
Sorry I forgot to include this but this would help a lot.

When I launched fnf from the terminal it traced an error, something along the lines of "Could Not Open AL device".
I can easily screenshot the error if needed.

Thats basically it.

**Comment by Skulltrail192** [comment]
I really don't know where i can found these programs what you mean

**Comment by Legendary-Candice-Joe** [comment]
idk either. But both Minecraft and Fnf print "Failed to open openAl device" to the terminal.

**Comment by Skulltrail192** [comment]
Are you installed OpenAl? 
Please see: https://www.openal.org/downloads/

**Comment by Legendary-Candice-Joe** [comment]
This didn't seem to help, not even after a restart. As I said, these games worked fine before one core 2.6.0.

**Comment by Legendary-Candice-Joe** [comment]
ok it fixed. I close now
