### ISSUE TITLE
Support for Intel HD Audio drivers in One Core API

### ISSUE THREAD

**Issue by creeper451** [Skulltrail192/One-Core-API-Binaries#80]
Hi, The other day i found my old laptop and decided to turn it into a retro machine so i installed Windows XP on it and managed to get all the drivers working expect for the "High Definition Audio" which is only supported on Windows Vista and higher so i was wondering could you support it on XP.
P.S Thanks for this amazing work 👍.

**Comment by Skulltrail192** [comment]
HD Audio drivers were introduced in Windows Server 2003 SP1 and Windows XP Sp2 (as hotfix). However, on Windows Vista these drivers were improveded. On ShorthornProject.com you can find a section with drivers ported from some Vista builds to get more compatbility. In some cases, you can use only HD drivers as generic drivers and audio works.

**Comment by creeper451** [comment]
Sorry for my late reply,
Yes i found the drivers but which one should i pick and is there a specific way of installing it and if its necessary to have onecore api installed.

**Comment by creeper451** [comment]
I tried the first one and it works, thank you so much for the help.
