### ISSUE TITLE
Chinese browser 360 Extreme Explorer 13.0.2310.0 (Chromium 86) won't open websites after installing One Core API 2.7.0

### ISSUE THREAD

**Issue by EgorKuzevanov** [Skulltrail192/One-Core-API-Binaries#82]
![Безымянный](https://user-images.githubusercontent.com/78859951/181476742-8ebbab77-4d01-4215-956a-73bc2e8bc488.png)
Link to problem browser: https://www103.zippyshare.com/v/CK7A0aJc/file.html

**Comment by Skulltrail192** [comment]
Well, 360 Extreme Explorer use a Loader what adde some parameters to chrome executable and broken with Base installer. If you run main executable, it's run fine. I'm investigating the issue

**Comment by Skulltrail192** [comment]
In true, the issue was started on version 2.6.0, what was introduced the option "--no-sandbox" builtin on CreateProcessInternal function. It will be solved on next version 2.9.

**Comment by Skulltrail192** [comment]
Fixed on version 2.9. Close this issue
