### ISSUE TITLE
Windows XP Professional x64 Edition Activation system breaks after installing base package

### ISSUE THREAD

**Issue by CameronSM36YT** [Skulltrail192/One-Core-API-Binaries#84]
Yeah i decided to try one core on my thinkpad. so i grabbed a blank hard drive and installed XP x64. after i was done i installed the one core base package. i did make a restore point just in case something went wrong(which it obviously did). i had activated windows on my 2nd attempt before making a new system restore point. but same results. this all happened after installing the base package and rebooting. i have to do the activation workaround just to use system restore. is this a known issue or is it something i did

**Comment by minediamonds304** [comment]
I have the same issue

**Comment by lyoneofficial** [comment]
I have the same

**Comment by Skulltrail192** [comment]
Issue solved and will solution will be avaliable on version 2.9. Same as #89

**Comment by lyoneofficial** [comment]
Ok

**Comment by Skulltrail192** [comment]
Fixed on version 2.9.
