### ISSUE TITLE
Issues running World of Tanks on Windows XP SP3

### ISSUE THREAD

**Issue by SigmaTel71** [Skulltrail192/One-Core-API-Binaries#85]
World of Tanks 1.17.1 and One-Core-API 2.7.0 can't work together in Windows 7 compatibility mode.
![image](https://user-images.githubusercontent.com/17989678/181937813-d7dc158e-3f20-46c3-8b36-08ee2b1addb3.png)
The application crashes after saying this error twice with quite unusual log error entry about invalid Coherent Gameface license key.
![image](https://user-images.githubusercontent.com/17989678/181937828-9578894f-5a44-4405-acf1-6a3ba33da1de.png)
Any additional info to provide?

**Comment by NEO-SPECTRUMAN** [comment]
WOT IS FCKN SHIT!
try to play WarThunder %)

**Comment by SigmaTel71** [comment]
> its has MOAR realistic physics/mechanics

I know, right? I have the 'open beta' participant badge, but I absolutely don't care about that.
Being realistic won't help One-Core-API to deal with errors.

**Comment by NEO-SPECTRUMAN** [comment]
in same time this is very strange
why they doesn't droped 32bit systems like other b*ches?

**Comment by jonm58** [comment]
I play World of Tanks and War Thunder.
Is this bad?
:)

**Comment by NEO-SPECTRUMAN** [comment]
> I play **World of Tanks** and War Thunder. Is this bad? :)

Definitely :)

**Comment by SigmaTel71** [comment]
@Skulltrail192, running into heavy offtopic/holywar here.

**Comment by jonm58** [comment]
> > I play **World of Tanks** and War Thunder. Is this bad? :)
> 
> Definitely :)

To stop the hate rhetoric, it is better to watch Pelosi go to Taiwan and become the fuse of World War III

**Comment by Skulltrail192** [comment]
This function will be added on next released.

**Comment by SigmaTel71** [comment]
> This function will be added on next released.

Well, it's still not there at version 2.8.0. Is it going to be in the next release *after* 2.8.0?

**Comment by Skulltrail192** [comment]
> Well, it's still not there at version 2.8.0. Is it going to be in the next release _after_ 2.8.0?

Yes, on version 2.9. I will release version 2.8.1 today, however, it's only hotfix.

**Comment by SigmaTel71** [comment]
@Skulltrail192, any updates?

**Comment by Skulltrail192** [comment]
Well, i can update binaries, before release new version. You must install using update.exe from packages folders (in case, base installers)

**Comment by SigmaTel71** [comment]
> Well, i can update binaries, before release new version.

I'd be really glad to test before the release, as I might find more missing functions before the 'stable' release comes out. Wouldn't that speed up the workflow?

**Comment by Skulltrail192** [comment]
Hey, commited kernel32 and ntdll to Base installer.

**Comment by SigmaTel71** [comment]
> Hey, commited kernel32 and ntdll to Base installer.

The error is gone, but the game still does not start. When executed through WorldOfTanks.exe located in the game's root folder, it blinks a black window and closes itself silently.
If I start it through win32\WorldOfTanks.exe, it will keep black window for longer time and pop up Dr.Watson crash report window. I can't locate the crash dump itself, but I can attach game log file which is very bland even in 'converted' from RU to DEV release and AppCompat data which was intended to be included to the crash report.
[python.log](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9418108/python.log)

[474_appcompat.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9418107/474_appcompat.txt)

**Comment by Skulltrail192** [comment]
It's seem Directx problem. Are you running on virtual machine or real hardware?

**Comment by SigmaTel71** [comment]
> real hardware

Yep, on real hardware.

**Comment by Skulltrail192** [comment]
AMD VGA or NVidia?

**Comment by SigmaTel71** [comment]
> NVidia

NVIDIA GeForce GTS 250. Its control panel icon is clearly visible in the system tray.

**Comment by SigmaTel71** [comment]
I doubt it's a DirectX-related issue as the game would throw 'appropriate graphics accelerator was not found' error (I don't remember exact text). It must have something either with locales or cryptography, or both.

**Comment by Skulltrail192** [comment]
Are you installed others packages?

**Comment by SigmaTel71** [comment]
> Are you installed others packages?

I have all six packages installed — the base, AppCompat, D3D, API-Set, Drivers Update and Additional DLLs.

**Comment by Skulltrail192** [comment]
This is a steam's game, correct? Are you installed steam working version? Are is "alternate version"?

**Comment by SigmaTel71** [comment]
There are two editions — the true original one from Wargaming.net Game Center and the weird piece of account incompatibility from Steam. Use the one from WGC.

**Comment by SigmaTel71** [comment]
I guess I'll change the target OS for this issue soon, as Wargaming [deprecates](https://worldoftanks.eu/en/content/docs/release_notes/release-notes-1-18/) 32-bit operating systems and [will support](https://worldoftanks.eu/en/news/general-news/wot-moves-to-64-os/) only the 64-bit ones.
![image](https://user-images.githubusercontent.com/17989678/187660815-3eb22f75-73c1-4f63-b377-d260f89e2fd2.png)

**Comment by Skulltrail192** [comment]
The error keep occurring? Do you want try again?

**Comment by SigmaTel71** [comment]
> The error keep occurring? 

Were there any code updates regarding AddVectoredContinueHandler function in the latest One-Core-API libraries? I haven't seen any.

> Do you want try again?

I'll retest the application when it's possible for me or if there was an actual update to the missing function mentioned above.

**Comment by Skulltrail192** [comment]
Well, this function will be added and avaliable on next release.

**Comment by SigmaTel71** [comment]
> Please see latest One-Core-API version.

Could you please tell the installation order as the amount of installation packages was changed in 3.0.0 since 2.7.0?

**Comment by SigmaTel71** [comment]
No, you haven't implemented this function in your kernel32.dll, at least in version 3.0.0. I cannot confirm that you fixed this.
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/17989678/d0c3e0ea-35c3-4e3f-af0b-696f4b43be38)
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/17989678/3163c93b-4b0f-47c3-aaaa-9429363da37d)

**Comment by Skulltrail192** [comment]
No, this is other issue, not related with missing function of this issue.

> AddVectoredContinueHandler

![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/d8463394-2746-4d8d-b426-a5a1f049a2fa)
The function is added on XP's kernel32

**Comment by Skulltrail192** [comment]
> No, you haven't implemented this function in your kernel32.dll, at least in version 3.0.0. I cannot confirm that you fixed this. ![image](https://user-images.githubusercontent.com/17989678/265128000-d0c3e0ea-35c3-4e3f-af0b-696f4b43be38.png) ![image](https://user-images.githubusercontent.com/17989678/265128172-3163c93b-4b0f-47c3-aaaa-9429363da37d.png)
> 
> Dependency Walker profiler output is below, if that matters. [WorldOfTanks.exe-win32-dw22-oca-3.0.0.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/12501577/WorldOfTanks.exe-win32-dw22-oca-3.0.0.txt)

This is other issue.

**Comment by SigmaTel71** [comment]
> This is other issue.

monitor_client_impl.dll is what calls this function. It is called from kernel32.dll. It's not the 'other issue' as if I remove or rename this library, the game **will not** crash to Dr.Watson prompt as Wargaming Error Monitor was not loaded, but will close itself because something prevents Coherent Gameface from starting up.
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/17989678/4e6f092a-8f0c-4416-9899-2da4c83201ee)

**Comment by Skulltrail192** [comment]
When I said that this is another problem, I was referring to the fact that the function had already been added to kernel32, and now, in your screenshot, another problem appears, managed by Dr Watson. The original problem, which is the absence of the function in kernel32, has been solved.

**Comment by SigmaTel71** [comment]
> When I said that this is another problem, I was referring to the fact that the function had already been added to kernel32, and now, in your screenshot, another problem appears, managed by Dr Watson.

Okay, do you need the Dr.Watson logs to investigate?

**Comment by Skulltrail192** [comment]
And .dmp generated.

**Comment by SigmaTel71** [comment]
> And .dmp generated.

[9836_appcompat.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/12563289/9836_appcompat.txt)
[4A043.zip](https://github.com/Skulltrail192/One-Core-API-Binaries/files/12563290/4A043.zip)

**Comment by SigmaTel71** [comment]
Any updates?

**Comment by Skulltrail192** [comment]
Try run again with latest OCA version

**Comment by SigmaTel71** [comment]
> Try run again with latest OCA version

Nope, still fails.
![image](https://github.com/Skulltrail192/One-Core-API-Bina
[WorldOfTanks_hdmp_mdmp.zip](https://github.com/Skulltrail192/One-Core-API-Binaries/files/14323241/WorldOfTanks_hdmp_mdmp.zip)
ries/assets/17989678/d295e035-9e81-434b-994b-1b175694f23f)

**Comment by jonm58** [comment]
> > Try run again with latest OCA version
> 
> Nope, still fails. ![image](https://private-user-images.githubusercontent.com/17989678/305727678-

try this
https://github.com/shorthorn-project/One-Core-API-Binaries-Canary/releases/tag/4.0.0-20240210-experimental

**Comment by SigmaTel71** [comment]
> do you try 4.0.0 rc1?

No dice, still errors on start.
[WorldOfTanks_mdmp_hdmp_canary.zip](https://github.com/Skulltrail192/One-Core-API-Binaries/files/14325020/WorldOfTanks_mdmp_hdmp_canary.zip)

**Comment by jonm58** [comment]
![屏幕截图 2024-02-19 103844](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/73036321/7f3b8d13-efe1-46fa-8d75-4c97592fb95c)

**Comment by SigmaTel71** [comment]
Just a side note: there is another another warning on 32-bit client in update 1.24.1 release notes. Despite that 32-bit client is still present in the game files and functional on compatible systems, I will close this issue as "wontfix" on my own if one will be finally removed.
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/17989678/9a6c11ca-8cb7-4315-a150-aab69d3554cb)

**Comment by SigmaTel71** [comment]
Closing the issue as 'wontfix'. In update 1.25 the game will continue exclusively as 64-bit one.
![image](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/17989678/d880d40d-e33d-40ab-b715-4c515641a1b3)
