### ISSUE TITLE
Windows Help and Support fails to open after installing the Additional DLLs package.

### ISSUE THREAD

**Issue by Smu1zel** [Skulltrail192/One-Core-API-Binaries#86]
After installing the above package, Help and Support may open once, or even twice, and will never work again. If it does happen to open, clicking anything results in the program freezing, and closing it renders it nonfunctional. I have attached footage of the program being unable to open. This has happened for quite a few releases (can't remember which one, at least 2.5.0), so it's not something 2.7.0 broke I believe.

https://user-images.githubusercontent.com/96768305/182025829-66c68c9c-970b-4e8b-9c86-0eca8d3f8ff7.mp4

Profiling "helpctr.exe" with Dependency Walker gives this output. Don't know if this'll be useful.
[log.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9228823/log.txt)

Edit: It's been a while but I'll also add just uninstalling the additional DLLs package doesn't fix the issue. You have to do a clean install just to fix it.

**Comment by mina354** [comment]
Same's happening to me too. Kinda annoying and sad, since I like browsing around Help and Support Center much.

**Comment by Smu1zel** [comment]
Yeah I just opened the Support center a bunch of times after each package to find the culprit, and it worked until this one. That's why I'm pointing at that specific package. I'll also note any programs that depend on Help and Support also break, like Remote Assistance and the Compatibility Troubleshooter.

**Comment by mina354** [comment]
> Yeah I just opened the Support center a bunch of times after each package to find the culprit, and it worked until this one. That's why I'm pointing at that specific package. I'll also note any programs that depend on Help and Support also break, like Remote Assistance and the Compatibility Troubleshooter.

I understand you, I was actually telling an opinion.

**Comment by Smu1zel** [comment]
> > Yeah I just opened the Support center a bunch of times after each package to find the culprit, and it worked until this one. That's why I'm pointing at that specific package. I'll also note any programs that depend on Help and Support also break, like Remote Assistance and the Compatibility Troubleshooter.
> 
> I understand you, I was actually telling an opinion.

I noticed my reply wasn't very good, sorry about that. I was trying to give more info at the same time. I'll just edit my posts next time.

**Comment by mina354** [comment]
> After installing the above package, Help and Support may open once, or even twice, and will never work again. If it does happen to open, clicking anything results in the program freezing, and closing it renders it nonfunctional. I have attached footage of the program being unable to open. This has happened for quite a few releases (can't remember which one, at least 2.5.0), so it's not something 2.7.0 broke I believe.
> 
>  helpandsupportbug.mp4 
> Profiling "helpctr.exe" with Dependency Walker gives this output. Don't know if this'll be useful. [log.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9228823/log.txt)
> 
> Edit: It's been a while but I'll also add just uninstalling the additional DLLs package doesn't fix the issue. You have to do a clean install just to fix it.

@Skulltrail192 Any progress on this? This bug is kinda annoying me.

**Comment by Smu1zel** [comment]
> > After installing the above package, Help and Support may open once, or even twice, and will never work again. If it does happen to open, clicking anything results in the program freezing, and closing it renders it nonfunctional. I have attached footage of the program being unable to open. This has happened for quite a few releases (can't remember which one, at least 2.5.0), so it's not something 2.7.0 broke I believe.
> > helpandsupportbug.mp4
> > Profiling "helpctr.exe" with Dependency Walker gives this output. Don't know if this'll be useful. [log.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9228823/log.txt)
> > Edit: It's been a while but I'll also add just uninstalling the additional DLLs package doesn't fix the issue. You have to do a clean install just to fix it.
> 
> @Skulltrail192 Any progress on this? This bug is kinda annoying me.

The nature of it (clean install every single attempt) probably makes this tedious to debug. Also, it's probably just not a very high priority right now.

**Comment by mina354** [comment]
> > > After installing the above package, Help and Support may open once, or even twice, and will never work again. If it does happen to open, clicking anything results in the program freezing, and closing it renders it nonfunctional. I have attached footage of the program being unable to open. This has happened for quite a few releases (can't remember which one, at least 2.5.0), so it's not something 2.7.0 broke I believe.
> > > helpandsupportbug.mp4
> > > Profiling "helpctr.exe" with Dependency Walker gives this output. Don't know if this'll be useful. [log.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9228823/log.txt)
> > > Edit: It's been a while but I'll also add just uninstalling the additional DLLs package doesn't fix the issue. You have to do a clean install just to fix it.
> > 
> > 
> > @Skulltrail192 Any progress on this? This bug is kinda annoying me.
> 
> The nature of it (clean install every single attempt) probably makes this tedious to debug. Also, it's probably just not a very high priority right now.

Alright then.

**Comment by Skulltrail192** [comment]
> > After installing the above package, Help and Support may open once, or even twice, and will never work again. If it does happen to open, clicking anything results in the program freezing, and closing it renders it nonfunctional. I have attached footage of the program being unable to open. This has happened for quite a few releases (can't remember which one, at least 2.5.0), so it's not something 2.7.0 broke I believe.
> > helpandsupportbug.mp4
> > Profiling "helpctr.exe" with Dependency Walker gives this output. Don't know if this'll be useful. [log.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9228823/log.txt)
> > Edit: It's been a while but I'll also add just uninstalling the additional DLLs package doesn't fix the issue. You have to do a clean install just to fix it.
> 
> @Skulltrail192 Any progress on this? This bug is kinda annoying me.

For now, no. I'm investeganting.

**Comment by mina354** [comment]
> > > After installing the above package, Help and Support may open once, or even twice, and will never work again. If it does happen to open, clicking anything results in the program freezing, and closing it renders it nonfunctional. I have attached footage of the program being unable to open. This has happened for quite a few releases (can't remember which one, at least 2.5.0), so it's not something 2.7.0 broke I believe.
> > > helpandsupportbug.mp4
> > > Profiling "helpctr.exe" with Dependency Walker gives this output. Don't know if this'll be useful. [log.txt](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9228823/log.txt)
> > > Edit: It's been a while but I'll also add just uninstalling the additional DLLs package doesn't fix the issue. You have to do a clean install just to fix it.
> > 
> > 
> > @Skulltrail192 Any progress on this? This bug is kinda annoying me.
> 
> For now, no. I'm investeganting.

Alright.

**Comment by Skulltrail192** [comment]
Will be fixed on version 2.10

**Comment by Skulltrail192** [comment]
Fixed on version 2.10.0
