### ISSUE TITLE
ZXTune-qt r5010 doesn't work

### ISSUE THREAD

**Issue by Epictyphlosion** [Skulltrail192/One-Core-API-Binaries#87]
When trying to run the program on x64 edition, it will run in the background but no gui appears.

**Comment by Skulltrail192** [comment]
If is qt based application, maybe it is related with Directx (dwrite, in true). Maybe deleting dwrite it's works.

**Comment by Skulltrail192** [comment]
![Ztune](https://github.com/Skulltrail192/One-Core-API-Binaries/assets/5159776/e3bc3bd3-adf1-46ab-b4fb-541dfa7f8185)
Seem working on newer versions.
