### ISSUE TITLE
DriverStoreExplorer problem

### ISSUE THREAD

**Issue by jonm58** [Skulltrail192/One-Core-API-Binaries#88]
https://github.com/lostindark/DriverStoreExplorer
Windows XP OCAPI 2.8.1
![Windows XP-2022-08-07-16-24-27](https://user-images.githubusercontent.com/73036321/183282153-ee071dd7-c5d1-484c-bd66-1c6ab4d5dd6c.png)

log:
[Rapr.log](https://github.com/Skulltrail192/One-Core-API-Binaries/files/9276439/Rapr.log)

**Comment by Skulltrail192** [comment]
I think that program use new Windows Driver Store, present only on Windows Vista or above. So, it is right, doesn't have any file because driver store not exists!

**Comment by Skulltrail192** [comment]
You can see on file what program search on C:\Windows\System32\DriverStore\FileRepository folder:

https://github.com/lostindark/DriverStoreExplorer/blob/27d7bd87e1d8d7cc999e8e25794d534e823de72e/Rapr/Utils/DriverStoreRepository.cs

What exist on XP CASE you installed custom drivers, is: 
C:\Windows\System32\DRVSTORE

**Comment by jonm58** [comment]
> You can see on file what program search on C:\Windows\System32\DriverStore\FileRepository folder:
> 
> https://github.com/lostindark/DriverStoreExplorer/blob/27d7bd87e1d8d7cc999e8e25794d534e823de72e/Rapr/Utils/DriverStoreRepository.cs
> 
> What exist on XP CASE you installed custom drivers, is: C:\Windows\System32\DRVSTORE

Thanks
