### ISSUE TITLE
License (60 days) revoked

### ISSUE THREAD

**Issue by lyoneofficial** [Skulltrail192/One-Core-API-Binaries#89]
When i install One Core API after restarting my 60 days trial stop working.

**Comment by Skulltrail192** [comment]
What have 60 days?

**Comment by lyoneofficial** [comment]
60 days XP trial

**Comment by lyoneofficial** [comment]
Because it’s Professional x64

**Comment by Skulltrail192** [comment]
Windows Activation, is that?

**Comment by lyoneofficial** [comment]
Yep

**Comment by lyoneofficial** [comment]
Hey

**Comment by Skulltrail192** [comment]
Fixed on version 2.9. Now, close this issue.
