### ISSUE TITLE
I/O APIC ACPI HAL is always loaded regardless of the hardware

### ISSUE THREAD

**Issue by blueclouds8666** [Skulltrail192/One-Core-API-Binaries#90]
I have noticed that the base installer for One-Core-API always installs [halaacpi.dll](https://github.com/Skulltrail192/One-Core-API-Binaries/blob/master/Packages/x86/Base%20Installer/update/update_winxp.inf#L515) (HAL for APIC and ACPI-compatible systems) as the system hardware abstraction layer for uniprocessors/single core processors, regardless of the hardware availability of these features.

This works fine most of the time, however, on some other instances, it can pose a problem for both older hardware and virtualization environments, given that the I/O APIC feature might not always be available or enabled in the system. Examples include VirtualBox (APIC disabled by default), Microsoft Virtual PC (APIC is not available, One-Core-API cannot be installed with default configurations) and QEMU.

I think it would be a good idea to load halacpi.dll (HAL for ACPI-compatible systems, no APIC required) instead, as it would make One-Core-API more compatible with those other systems.

Regards.

**Comment by Skulltrail192** [comment]
Known issue, equals to #49, so, will be closed
