### ISSUE TITLE
Fix stability on real systems

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [Skulltrail192/One-Core-API-Binaries#91]

**Comment by Skulltrail192** [comment]
What is unstable? Provide more information.

**Comment by RetroSoftwareRepository** [comment]
Browsing the web with the API installed results in a BSOD. I had installed the 2018 version of the API I think at the time and it was unstable as hell. Don't think the newer versions are much better, considering it's based on ReactOS code... which is Alpha quality.

**Comment by Skulltrail192** [comment]
You must record a video or take a photo when BSOD occours. Remember: i can't test in all cenarios and can't prevent if BSOD can happen. I'm not from Microsoft. (Even Microsoft every time launch hotfix what break own systems)

**Comment by RetroSoftwareRepository** [comment]
How can I forget... they broke Windows 7 on SSE only systems.

**Comment by Smu1zel** [comment]
> How can I forget... they broke Windows 7 on SSE only systems.

POSReady 2009 isn't safe either, starting from around 2018, updates required SSE2.

**Comment by Skulltrail192** [comment]
> How can I forget... they broke Windows 7 on SSE only systems.

I don't understand. It is related with One-Core-API or Windows 7?

**Comment by Smu1zel** [comment]
> > How can I forget... they broke Windows 7 on SSE only systems.
> 
> I don't understand. It is related with One-Core-API or Windows 7? As i said, give image of BSOD (photo). I can know what is happening if i can't see.

He's referring to how Windows 7 updates from around 2018 and onwards started crashing on non SSE2 systems (pre-Pentium 4 and Athlon XP were affected). There was a fix in the works, but they instead just told you to basically upgrade your PC. Making 2018 the de facto EOL for these systems.

**Comment by Skulltrail192** [comment]
How the issue's creator don't provided evidences to try reproduce the issue, it will be closed.
