### ISSUE TITLE
More issues

### ISSUE THREAD

**Issue by cesar300** [Skulltrail192/One-Core-API-Binaries#92]
I have installed all packages from 2.9.0. and I detected more issues:
- DirectX runtime won't install.
- VCredist 2008 won't install.
- I cannot run Sniper Elite V2 when previously could run it. (Internal error 0x0A).
- Can I run last version of dgvoodoo2?
I attach some screenshots.
![dgvoodoo2](https://user-images.githubusercontent.com/43586856/188182337-8c47ef4b-621c-4561-8da3-b6cb3f23dd26.PNG)
![dxerror](https://user-images.githubusercontent.com/43586856/188182343-5906d09c-9bd0-448c-866a-5947401e833b.PNG)
![sev2](https://user-images.githubusercontent.com/43586856/188182345-145dc2e4-cb2d-4f01-934a-cbff6a127e26.PNG)
![vcredist2008](https://user-images.githubusercontent.com/43586856/188182346-d85e3af2-c506-477b-a37b-210c8b4aefc3.PNG)

**Comment by Skulltrail192** [comment]
dgvoodoo2 is for run old games?

**Comment by cesar300** [comment]
> dgvoodoo2 is for run old games?

Yes

**Comment by Skulltrail192** [comment]
And run normally on Windows Xp? And with old verions of One-core-API?

**Comment by Skulltrail192** [comment]
> I have installed all packages from 2.9.0. and I detected more issues:
> 
>     * DirectX runtime won't install.
> 
>     * VCredist 2008 won't install.
> 
>     * I cannot run Sniper Elite V2 when previously could run it. (Internal error 0x0A).
> 
>     * Can I run last version of dgvoodoo2?
>       I attach some screenshots.
>       ![dgvoodoo2](https://user-images.githubusercontent.com/43586856/188182337-8c47ef4b-621c-4561-8da3-b6cb3f23dd26.PNG)
>       ![dxerror](https://user-images.githubusercontent.com/43586856/188182343-5906d09c-9bd0-448c-866a-5947401e833b.PNG)
>       ![sev2](https://user-images.githubusercontent.com/43586856/188182345-145dc2e4-cb2d-4f01-934a-cbff6a127e26.PNG)
>       ![vcredist2008](https://user-images.githubusercontent.com/43586856/188182346-d85e3af2-c506-477b-a37b-210c8b4aefc3.PNG)

What Windows XP version used? I tested on XP SP3 with updates and DX and VC++ install without problems.

**Comment by cesar300** [comment]
These errors occurs after install one core api 2.9.0. With previous versions I got the DEADBEEF bsod.
I used Windows XP Pro SP3 spanish but without updates.

**Comment by posreadyxp** [comment]
> These errors occurs after install one core api 2.9.0. With previous versions I got the DEADBEEF bsod. I used Windows XP Pro SP3 spanish but without updates.

Try to install post sp3 updates

**Comment by Skulltrail192** [comment]
> These errors occurs after install one core api 2.9.0. With previous versions I got the DEADBEEF bsod. I used Windows XP Pro SP3 spanish but without updates.

Are you used io win XP SP3 (Customized Option; 1,2,3,4,A,B,C,D,E).iso?
