### ISSUE TITLE
Nightlizard problem

### ISSUE THREAD

**Issue by jonm58** [Skulltrail192/One-Core-API-Binaries#93]
Just a small problem, can you fix the button? (Although it is Alpha, there are no serious bugs)
![image](https://user-images.githubusercontent.com/73036321/188206780-22dba003-f43b-4288-a3b4-a26e2afe970a.png)
![image](https://user-images.githubusercontent.com/73036321/188206908-e08a29d6-e283-4fb4-b25d-c15c4e88a3e1.png)

Nightlizard:https://nightlizard.libinfo.science/

**Comment by Skulltrail192** [comment]
Please, more information. What is this navigator? What configuration?

**Comment by jonm58** [comment]
information:Windows XP Professional SP3 x86 - Integral Edition 2022.6.16

Bugs caused by Windows 7 compatibility:
![image](https://user-images.githubusercontent.com/73036321/188228664-b56e62fe-9707-454a-bc49-d2ea88bdd23a.png)
Compatibility is not set:
![image](https://user-images.githubusercontent.com/73036321/188229418-0f3a4755-d2c1-43bb-9819-d135f5c217a1.png)

**Comment by Skulltrail192** [comment]
I think it is not really relevant. It's probably occours because theme engine is different betweeen Windows XP and Windows Vista/7. So, firefox use a different metrics to calculate position and type of resources. Maybe cannot be solved!

**Comment by jonm58** [comment]
OK
