### ISSUE TITLE
Adding localizations for One-Core-Api

### ISSUE THREAD

**Issue by ghost** [Skulltrail192/One-Core-API-Binaries#94]
I think it's needed for other languages in Windows XP, so maybe add this feature? (I know it's hard, but maybe You can add!)

**Comment by Skulltrail192** [comment]
Hello friend. It's in true is not hard. However, require time to do it. Maybe every version i need  do it. I can't time for now. Maybe in future i add MuI files, since One-Core-API give MUI support like Windows Vista.

**Comment by posreadyxp** [comment]
> Hello friend. It's in true is not hard. However, require time to do it. Maybe every version i need do it. I can't time for now. Maybe in future i add MuI files, since One-Core-API give MUI support like Windows Vista.

OK. If You need help to localize in RU language, contact me!

**Comment by Skulltrail192** [comment]
Due i created a Internacionalization Main Thread, this issue will be closed.
