### ISSUE TITLE
Add support for LibreOffice 7.x

### ISSUE THREAD

**Issue by EgorKuzevanov** [Skulltrail192/One-Core-API-Binaries#95]
On Windows XP Professional SP3 (x86) with One Core API 2.9.0 installed, portable versions of LibreOffice 7.x from PortableApps.com won't run and give a **crypt32.dll** error.

https://youtu.be/mtQsok-_Qh4?t=348

**Comment by Skulltrail192** [comment]
Added these functions on Crypt32, however, LibreOffice 7+ is partial supported. On installable version, programs crash.

**Comment by Skulltrail192** [comment]
Added function, however, programs keep crashing.
