### ISSUE TITLE
Is there a way to use this/simular patch set on Windows 7?

### ISSUE THREAD

**Issue by HyperSoop** [Skulltrail192/One-Core-API-Binaries#96]
More people out there use Win7, and forwards compatibility modes will probably be easier to implement for it.

**Comment by Skulltrail192** [comment]
Hello friend! Do you mean create a one-core-api version to Windows 7?

**Comment by HyperSoop** [comment]
> Hello friend! Do you mean create a one-core-api version to Windows 7?

Yeah, something like that.

**Comment by Skulltrail192** [comment]
Well, i have plans to do it, however, for now, i don't have time. I started tests on Windows Vista. And, Windows Vista or above not support Windows Hotfix system from Windows XP/2003. Need a new installer method

**Comment by gliczide** [comment]
> More people out there use Win7, and forwards compatibility modes will probably be easier to implement for it.

Hey, There's [VxKex](https://github.com/vxiiduu/VxKex).

**Comment by Skulltrail192** [comment]
Well, since for now One-core-API has only target for XP/2003, this issue will be closed.

**Comment by HyperSoop** [comment]
> > More people out there use Win7, and forwards compatibility modes will probably be easier to implement for it.
> 
> Hey, Atleast There's [VxKex](https://github.com/vxiiduu/VxKex).

That's an interensting one, though I'd like to see the applications it allows to support, the way it's installed and updated, etc. before trying

**Comment by Ricco95** [comment]
this work is very impressive! is it possible to implement something similar in Windows 10? it used to be in windows 10 version 1607. compatibility mode in this version was fine: several old games lost their bugs, and one of them even started, although it was initially available only on win 95, but in later versions of windows-it stopped working as well as in version 1607. As an OLD gamer, I was very happy with this fix, and was extremely upset when it was messed up
