### ISSUE TITLE
Add support for Windows 7 Calculator/Paint/Wordpad

### ISSUE THREAD

**Issue by rryan22** [Skulltrail192/One-Core-API-Binaries#98]
On Windows XP Professional SP3 (x86), does Windows 7 Calculator/Paint/Wordpad work with OneCore API?

**Comment by Skulltrail192** [comment]
Paint is already supported. However, wordpad yet crash and Calculator has graphics issues and crash if selected other mode otherwise the default mode. And, for now, i don't know how fix it.

**Comment by rryan22** [comment]
Calculator and WordPad from Windows 7 needed to be fixed for the release!

**Comment by Skulltrail192** [comment]
Same #135

**Comment by Skulltrail192** [comment]
Only rest calculator, wordpad and Paint already done.
