### ISSUE TITLE
My Windows XP machine is not booting up

### ISSUE THREAD

**Issue by TBRHS** [Skulltrail192/One-Core-API-Binaries#99]
Hello
I installed all of the packages in my Windows XP Professional SP3 PT-BR machine, and it's not booting up.
I have no idea how to make it working.
Please fix this issue.

**Comment by TBRHS** [comment]
I DID THIS IN MY WINDOWS XP ENGLISH VM WITH SAME SP AND IT GOT KILLED IT JUST FREEZES

**Comment by Smu1zel** [comment]
> Hello I installed all of the packages in my Windows XP Professional SP3 PT-BR machine, and it's not booting up. I have no idea how to make it working. Please fix this issue.

I've had a similar issue shortly after boot up with too much RAM. If you have around 3GB, try to remove some. If that doesn't work, try safe mode and do a repair upgrade.

Just don't hate on the project maintainer, this project isn't finished and there will be bugs.

**Comment by Skulltrail192** [comment]
> I DID THIS IN MY WINDOWS XP ENGLISH VM WITH SAME SP AND IT GOT KILLED IT JUST FREEZES

What VM? Virtual Box?

**Comment by Skulltrail192** [comment]
> Hello I installed all of the packages in my Windows XP Professional SP3 PT-BR machine, and it's not booting up. I have no idea how to make it working. Please fix this issue.

Please, be more specific. Take a photo if get a BSOD. If computer restart aumatically, press "F8", and Select "Disable automatic restart". What configuration of computer?

**Comment by Skulltrail192** [comment]
And, what config? It is real hardware or VM too?

> Hello I installed all of the packages in my Windows XP Professional SP3 PT-BR machine, and it's not booting up. I have no idea how to make it working. Please fix this issue.

**Comment by TBRHS** [comment]
> > Hello I installed all of the packages in my Windows XP Professional SP3 PT-BR machine, and it's not booting up. I have no idea how to make it working. Please fix this issue.
> 
> Please, be more specific. Take a photo if get a BSOD. If computer restart aumatically, press "F8", and Select "Disable automatic restart". What configuration of computer?

Didn't get a BSOD

**Comment by TBRHS** [comment]
> > I DID THIS IN MY WINDOWS XP ENGLISH VM WITH SAME SP AND IT GOT KILLED IT JUST FREEZES
> 
> What VM? Virtual Box?

Yes, it was Virtualbox.

**Comment by Skulltrail192** [comment]
And what happens?

**Comment by Skulltrail192** [comment]
> Hello I installed all of the packages in my Windows XP Professional SP3 PT-BR machine, and it's not booting up. I have no idea how to make it working. Please fix this issue.

Are you installed in Virtual box too?

**Comment by Skulltrail192** [comment]
This problem is already known. See Readme.md and #49 . For now, use Vmware or Enable "APIC option on Virtual Box. See #49 to see how enable or search on google.

**Comment by Skulltrail192** [comment]
The issue what Windows XP not boot up on Virtual box are solved and will be avaliable on next release. However, as commented, Mouse pointer not working with virtual box tools installed. It is by investigation.

**Comment by Skulltrail192** [comment]
I hope solved on version 2.10.0
